const data14 = [
    // --- İsimler ---
    { id: 571, category: 'isimler', germanWord: 'der Maßstab /"e', pronunciation: 'der taas-ştaap', germanSentence: 'Wir müssen strengere Maßstäbe anlegen.', turkishWord: 'ölçüt, standart, kıstas', turkishSentence: 'Daha sıkı standartlar(ölçütler) belirlemeliyiz.' },
    { id: 572, category: 'isimler', germanWord: 'die Mentalität /-en', pronunciation: 'di men-ta-li-teet', germanSentence: 'Die deutsche Mentalität legt Wert auf Pünktlichkeit.', turkishWord: 'zihniyet, anlayış', turkishSentence: 'Alman zihniyeti dakikliğe değer verir.' },
    { id: 573, category: 'isimler', germanWord: 'das Motiv /-e', pronunciation: 'das mo-tiif', germanSentence: 'Das Motiv für die Tat ist noch völlig unklar.', turkishWord: 'gerekçe, saik', turkishSentence: 'Suçun(eylemin) gerekçesi hala tamamen belirsiz.' },
    { id: 574, category: 'isimler', germanWord: 'der Mythos', pronunciation: 'der mü-tos', germanSentence: 'Es rankt sich ein Mythos um dieses alte Schloss.', turkishWord: 'efsane, mit', turkishSentence: 'Bu eski şatonun etrafında bir efsane dolaşıyor.' },
    { id: 575, category: 'isimler', germanWord: 'der Nerv /-en', pronunciation: 'der nerf', germanSentence: 'Lärm geht mir sehr auf die Nerven.', turkishWord: 'sinir', turkishSentence: 'Gürültü sinirlerimi çok bozuyor (sinirlerime dokunuyor).' },
    { id: 576, category: 'isimler', germanWord: 'das Prestige', pronunciation: 'das pres-tiij', germanSentence: 'Dieser Job bringt viel Prestige mit sich.', turkishWord: 'prestij, saygınlık', turkishSentence: 'Bu iş beraberinde çok fazla prestij getiriyor.' },
    { id: 577, category: 'isimler', germanWord: 'die Prognose /-n', pronunciation: 'di prog-noo-zı', germanSentence: 'Die wirtschaftliche Prognose ist düster.', turkishWord: 'tahmin, öngörü', turkishSentence: 'Ekonomik tahmin karamsar(karanlık).' },
    { id: 578, category: 'isimler', germanWord: 'das Referat /-e', pronunciation: 'das re-fe-raat', germanSentence: 'Sie hält heute ein Referat über Goethe.', turkishWord: 'sunum, bildiri', turkishSentence: 'Bugün Goethe hakkında bir sunum yapıyor.' },
    { id: 579, category: 'isimler', germanWord: 'das Ressort /-s', pronunciation: 'das re-soor', germanSentence: 'Das Umweltministerium ist sein Ressort.', turkishWord: 'iş bölümü, yetki alanı, departman', turkishSentence: 'Çevre Bakanlığı onun yetki alanıdır.' },
    { id: 580, category: 'isimler', germanWord: 'der Rivale /-n', pronunciation: 'der ri-vaa-lı', germanSentence: 'Er besiegte seinen größten Rivalen.', turkishWord: 'rakip', turkishSentence: 'O en büyük rakibini yendi.' },

    // --- Fiiller ---
    { id: 581, category: 'fiiller', germanWord: 'trösten', pronunciation: 'trös-tın', germanSentence: 'Sie versuchte, das weinende Kind zu trösten.', turkishWord: 'teselli etmek', turkishSentence: 'Ağlayan çocuğu teselli etmeye çalıştı.' },
    { id: 582, category: 'fiiller', germanWord: 'verbergen', pronunciation: 'fer-ber-gın', germanSentence: 'Er konnte seine Wut nicht länger verbergen.', turkishWord: 'gizlemek, saklamak', turkishSentence: 'Öfkesini daha fazla gizleyemedi.' },
    { id: 583, category: 'fiiller', germanWord: 'verdauen', pronunciation: 'fer-dau-ın', germanSentence: 'Ich muss diese schlechte Nachricht erst einmal verdauen.', turkishWord: 'sindirmek, hazmetmek', turkishSentence: 'Öncelikle bu kötü haberi sindirmeliyim.' },
    { id: 584, category: 'fiiller', germanWord: 'verdrängen', pronunciation: 'fer-dren-gın', germanSentence: 'Sie hat dieses traumatische Erlebnis verdrängt.', turkishWord: 'bastırmak (psikoloji), yerinden etmek', turkishSentence: 'O travmatik deneyimi (bilinçaltına) bastırdı.' },
    { id: 585, category: 'fiiller', germanWord: 'verschaffen', pronunciation: 'fer-şa-fın', germanSentence: 'Das verschafft uns einen großen Zeitvorteil.', turkishWord: 'sağlamak, temin etmek', turkishSentence: 'Bu bize büyük bir zaman avantajı sağlıyor.' },
    { id: 586, category: 'fiiller', germanWord: 'widmen (sich)', pronunciation: 'vit-mın', germanSentence: 'Er widmet sein ganzes Leben der Kunst.', turkishWord: 'adamak', turkishSentence: 'O tüm hayatını sanata adıyor.' },
    { id: 587, category: 'fiiller', germanWord: 'widerrufen', pronunciation: 'vi-dır-ru-fın', germanSentence: 'Sie können den Vertrag binnen zwei Wochen widerrufen.', turkishWord: 'geri almak, iptal etmek', turkishSentence: 'Sözleşmeyi iki hafta içinde iptal edebilirsiniz (geri alabilirsiniz).' },
    { id: 588, category: 'fiiller', germanWord: 'zentrieren', pronunciation: 'tsen-trii-rın', germanSentence: 'Bitte zentrieren Sie den Text auf der Seite.', turkishWord: 'ortalamak, merkeze yerleştirmek', turkishSentence: 'Lütfen metni sayfada ortalayın.' },
    { id: 589, category: 'fiiller', germanWord: 'zögern', pronunciation: 'tsö-gırn', germanSentence: 'Wer zögert, verliert.', turkishWord: 'tereddüt etmek, duraksamak', turkishSentence: 'Tereddüt eden kaybeder.' },
    { id: 590, category: 'fiiller', germanWord: 'zurückweisen', pronunciation: 'tsu-rük-vay-zın', germanSentence: 'Das Gericht hat die Klage als unbegründet zurückgewiesen.', turkishWord: 'reddetmek, geri çevirmek', turkishSentence: 'Mahkeme davayı asılsız bularak reddetti.' },

    // --- Sıfatlar ---
    { id: 591, category: 'sıfatlar', germanWord: 'ironisch', pronunciation: 'i-roo-niş', germanSentence: 'Er lächelte ironisch.', turkishWord: 'ironik, alaycı', turkishSentence: 'O ironik bir şekilde gülümsedi.' },
    { id: 592, category: 'sıfatlar', germanWord: 'isoliert', pronunciation: 'i-zo-liirt', germanSentence: 'Sie lebten auf einem isolierten Bauernhof.', turkishWord: 'izole, yalıtılmış', turkishSentence: 'Onlar izole edilmiş bir çiftlikte yaşıyorlardı.' },
    { id: 593, category: 'sıfatlar', germanWord: 'juvenil', pronunciation: 'yu-ve-niil', germanSentence: 'Das ist eine Erkrankung, die oft in der juvenilen Phase auftritt.', turkishWord: 'gençliğe ait', turkishSentence: 'Bu sıklıkla gençlik evresinde ortaya çıkan bir hastalıktır.' },
    { id: 594, category: 'sıfatlar', germanWord: 'katastrophal', pronunciation: 'ka-tas-tro-faal', germanSentence: 'Die Arbeitsbedingungen sind hier katastrophal.', turkishWord: 'felaket', turkishSentence: 'Çalışma koşulları burada felaket/korkunç.' },
    { id: 595, category: 'sıfatlar', germanWord: 'kognitiv', pronunciation: 'kog-ni-tiif', germanSentence: 'Das Gedächtnis ist eine wichtige kognitive Funktion.', turkishWord: 'bilişsel', turkishSentence: 'Hafıza önemli bir bilişsel işlevdir.' },
    { id: 596, category: 'sıfatlar', germanWord: 'kompakt', pronunciation: 'kom-pakt', germanSentence: 'Das Auto ist klein und kompakt.', turkishWord: 'kompakt, sıkı', turkishSentence: 'Araba küçük ve kompakttır.' },
    { id: 597, category: 'sıfatlar', germanWord: 'präzise', pronunciation: 'pre-tsii-zı', germanSentence: 'Bitte formulieren Sie das präziser.', turkishWord: 'kesin, net, tam', turkishSentence: 'Lütfen bunu daha net/kesin ifade edin.' },
    { id: 598, category: 'sıfatlar', germanWord: 'radikal', pronunciation: 'ra-di-kaal', germanSentence: 'Sie fordert einen radikalen Wandel.', turkishWord: 'radikal, köklü', turkishSentence: 'O köklü/radikal bir değişim talep ediyor.' },
    { id: 599, category: 'sıfatlar', germanWord: 'rigoros', pronunciation: 'ri-go-roos', germanSentence: 'Sie gehen rigoros gegen Steuersünder vor.', turkishWord: 'katı, sert, amansız', turkishSentence: 'Vergi kaçakçılarına karşı katı(amansız) bir tutum sergiliyorlar.' },
    { id: 600, category: 'sıfatlar', germanWord: 'spezifisch', pronunciation: 'şpe-tsii-fiş', germanSentence: 'Wir müssen dieses Problem spezifisch betrachten.', turkishWord: 'spesifik, özel, özgül', turkishSentence: 'Bu sorunu spesifik olarak ele almalıyız.' },

    // --- Bağlaçlar / Zarflar / İfadeler ---
    { id: 601, category: 'bağlaçlar', germanWord: 'anlässlich', pronunciation: 'an-les-lih', germanSentence: 'Anlässlich seines Geburtstags gab es eine große Feier.', turkishWord: 'münasebetiyle, vesilesiyle', turkishSentence: 'Doğum günü münasebetiyle büyük bir kutlama yapıldı.' },
    { id: 602, category: 'bağlaçlar', germanWord: 'angesichts', pronunciation: 'an-ge-zihts', germanSentence: 'Angesichts der Gefahr mussten wir umkehren.', turkishWord: 'karşısında, göz önünde bulundurarak', turkishSentence: 'Tehlike karşısında geri dönmek zorunda kaldık.' },
    { id: 603, category: 'bağlaçlar', germanWord: 'anhand', pronunciation: 'an-hant', germanSentence: 'Anhand dieses Beispiels erkläre ich die Regel.', turkishWord: 'dayanarak, yardımıyla', turkishSentence: 'Bu örneğin yardımıyla kuralı açıklıyorum.' },
    { id: 604, category: 'bağlaçlar', germanWord: 'inmitten', pronunciation: 'in-mi-tın', germanSentence: 'Inmitten des Waldes stand eine kleine Hütte.', turkishWord: 'ortasında', turkishSentence: 'Ormanın tam ortasında küçük bir kulübe duruyordu.' },
    { id: 605, category: 'bağlaçlar', germanWord: 'mangels', pronunciation: 'man-gıls', germanSentence: 'Mangels Beweisen wurde das Verfahren eingestellt.', turkishWord: 'eksikliğinden', turkishSentence: 'Kanıt eksikliğinden dava düşürüldü / durduruldu.' },
    { id: 606, category: 'bağlaçlar', germanWord: 'seitens', pronunciation: 'zay-tıns', germanSentence: 'Seitens der Regierung gab es keine Bestätigung.', turkishWord: 'tarafından, açısından', turkishSentence: 'Hükümet tarafından bir doğrulama olmadı.' },
    { id: 607, category: 'bağlaçlar', germanWord: 'insofern', pronunciation: 'in-zo-fern', germanSentence: 'Insofern bin ich mit dem Bericht zufrieden, als er pünktlich ist.', turkishWord: '-mesi bakımından, bu açıdan', turkishSentence: 'Zamanında gelmesi bakımından bu rapordan memnunum.' },
    { id: 608, category: 'bağlaçlar', germanWord: 'ungeachtet', pronunciation: 'un-ge-ah-tıt', germanSentence: 'Ungeachtet der Verluste kämpften sie weiter.', turkishWord: 'rağmen, dikkate almadan', turkishSentence: 'Kayıplara rağmen/Kayıpları dikkate almadan savaşmaya devam ettiler.' },
    { id: 609, category: 'bağlaçlar', germanWord: 'zugunsten', pronunciation: 'tsu-guns-tın', germanSentence: 'Das Gericht entschied zugunsten des Angeklagten.', turkishWord: 'lehine, yararına', turkishSentence: 'Mahkeme sanığın lehine karar verdi.' },
    { id: 610, category: 'bağlaçlar', germanWord: 'zulasten', pronunciation: 'tsu-las-tın', germanSentence: 'Die Reform geht zulasten der ärmeren Familien.', turkishWord: 'zararına, aleyhine', turkishSentence: 'Bu reform daha fakir ailelerin aleyhinedir.' },

    // --- İsimler ---
    { id: 611, category: 'isimler', germanWord: 'das Schicksal /-e', pronunciation: 'das şik-zaal', germanSentence: 'Niemand kann seinem Schicksal entkommen.', turkishWord: 'kader, alın yazısı', turkishSentence: 'Kimse kaderinden kaçamaz.' },
    { id: 612, category: 'isimler', germanWord: 'der Vorbehalt /-e', pronunciation: 'der for-be-halt', germanSentence: 'Ich stimme dem Plan nur unter dem Vorbehalt zu, dass...', turkishWord: 'çekince', turkishSentence: 'Plana sadece şu çekinceyle(şartla) onay veriyorum...' },
    { id: 613, category: 'isimler', germanWord: 'die Zuversicht', pronunciation: 'di tsu-fer-ziht', germanSentence: 'Mit großer Zuversicht gehen wir in das neue Jahr.', turkishWord: 'umut, güven, iyimserlik', turkishSentence: 'Büyük bir umut/güvenle yeni yıla giriyoruz.' },
    { id: 614, category: 'isimler', germanWord: 'das Zögern', pronunciation: 'das tsö-gırn', germanSentence: 'Nach kurzem Zögern sagte sie Ja.', turkishWord: 'tereddüt, duraksama', turkishSentence: 'Kısa bir tereddütten sonra Evet dedi.' },
    { id: 615, category: 'isimler', germanWord: 'der Zusammenbruch', pronunciation: 'der tsu-za-mın-bruh', germanSentence: 'Er erlitt einen nervlichen Zusammenbruch.', turkishWord: 'çöküş, kriz', turkishSentence: 'O bir sinir krizi/çöküşü yaşadı.' },
    { id: 616, category: 'isimler', germanWord: 'die Alternative /-n', pronunciation: 'di al-ter-na-ti-vı', germanSentence: 'Es gibt keine ernstzunehmende Alternative dazu.', turkishWord: 'alternatif, seçenek', turkishSentence: 'Bunun için ciddiye alınacak bir alternatif yok.' },
    { id: 617, category: 'isimler', germanWord: 'die Beschaffenheit', pronunciation: 'di be-şa-fın-hayt', germanSentence: 'Die Beschaffenheit des Bodens ist hier sehr sandig.', turkishWord: 'yapı, özellik, nitelik', turkishSentence: 'Buradaki toprağın yapısı oldukça kumludur.' },
    { id: 618, category: 'isimler', germanWord: 'das Detail /-s', pronunciation: 'das de-tay', germanSentence: 'Der Plan stimmt bis ins kleinste Detail.', turkishWord: 'detay, ayrıntı', turkishSentence: 'Plan en ince ayrıntısına kadar doğru.' },
    { id: 619, category: 'isimler', germanWord: 'die Distanz', pronunciation: 'di dis-tants', germanSentence: 'Bitte wahren Sie die körperliche Distanz.', turkishWord: 'mesafe', turkishSentence: 'Lütfen fiziksel mesafeyi koruyun.' },
    { id: 620, category: 'isimler', germanWord: 'die Effizienz', pronunciation: 'di e-fi-tsiyents', germanSentence: 'Die neue Software steigert unsere Effizienz enorm.', turkishWord: 'verimlilik', turkishSentence: 'Yeni yazılım verimliliğimizi devasa ölçüde artırıyor.' },

    // --- Fiiller ---
    { id: 621, category: 'fiiller', germanWord: 'abstimmen (sich)', pronunciation: 'ap-şti-mın', germanSentence: 'Wir müssen uns über das weitere Vorgehen abstimmen.', turkishWord: 'mutabakata varmak, fikir birliğine varmak', turkishSentence: 'İleriki adımlar konusunda mutabakata varmalıyız.' },
    { id: 622, category: 'fiiller', germanWord: 'aneignen (sich)', pronunciation: 'an-ayg-nın', germanSentence: 'Er hat sich das Wissen selbst angeeignet.', turkishWord: 'edinmek (bilgi/beceri)', turkishSentence: 'Bilgiyi kendi kendine edindi.' },
    { id: 623, category: 'fiiller', germanWord: 'berücksichtigen', pronunciation: 'be-rük-zih-ti-gın', germanSentence: 'Das müssen wir bei der Planung unbedingt berücksichtigen.', turkishWord: 'dikkate almak, göz önünde bulundurmak', turkishSentence: 'Bunu planlamada mutlaka dikkate almalıyız.' },
    { id: 624, category: 'fiiller', germanWord: 'deduzieren', pronunciation: 'de-du-tsii-rın', germanSentence: 'Aus diesen Prämissen lässt sich diese Schlussfolgerung deduzieren.', turkishWord: 'tümdengelim yapmak, sonuç çıkarmak', turkishSentence: 'Bu öncüllerden bu sonuç çıkarılabilir(tümdengelim).' },
    { id: 625, category: 'fiiller', germanWord: 'demonstrieren', pronunciation: 'de-mon-strii-rın', germanSentence: 'Die Studenten demonstrieren für mehr Klimaschutz.', turkishWord: 'gösteri yapmak, göstermek', turkishSentence: 'Öğrenciler daha fazla iklim koruması için gösteri yapıyor.' },
    { id: 626, category: 'fiiller', germanWord: 'diskriminieren', pronunciation: 'dis-kri-mi-nii-rın', germanSentence: 'Niemand darf aufgrund seines Geschlechts diskriminiert werden.', turkishWord: 'ayrımcılık yapmak', turkishSentence: 'Kimseye cinsiyeti nedeniyle ayrımcılık yapılamaz.' },
    { id: 627, category: 'fiiller', germanWord: 'dokumentieren', pronunciation: 'do-ku-men-tii-rın', germanSentence: 'Alle Fortschritte müssen genau dokumentiert werden.', turkishWord: 'belgelemek, dokümante etmek', turkishSentence: 'Tüm ilerlemeler tam olarak belgelenmelidir.' },
    { id: 628, category: 'fiiller', germanWord: 'dominieren', pronunciation: 'do-mi-nii-rın', germanSentence: 'Dieses Thema dominiert derzeit die Medien.', turkishWord: 'hükmetmek, baskın olmak, hakim olmak', turkishSentence: 'Bu konu şu anda medyaya hakim(baskın).' },
    { id: 629, category: 'fiiller', germanWord: 'durchsetzen (sich)', pronunciation: 'durh-zet-sın', germanSentence: 'Ich bin sicher, dass du dich am Ende durchsetzen wirst.', turkishWord: 'sözünü geçirmek, kendini kabul ettirmek', turkishSentence: 'Sonunda kendini kabul ettireceğinden(başaracağından) eminim.' },
    { id: 630, category: 'fiiller', germanWord: 'eingreifen', pronunciation: 'ayn-gray-fın', germanSentence: 'Der Schiedsrichter musste in das Spiel eingreifen.', turkishWord: 'müdahale etmek', turkishSentence: 'Hakem maça müdahale etmek zorunda kaldı.' },

    // --- Sıfatlar ---
    { id: 631, category: 'sıfatlar', germanWord: 'strukturell', pronunciation: 'ştruk-tu-rel', germanSentence: 'Die Firma hat viele strukturelle Probleme.', turkishWord: 'yapısal', turkishSentence: 'Şirketin birçok yapısal problemi var.' },
    { id: 632, category: 'sıfatlar', germanWord: 'stur', pronunciation: 'ştuur', germanSentence: 'Er kann manchmal sehr stur sein.', turkishWord: 'inatçı', turkishSentence: 'O bazen çok inatçı olabiliyor.' },
    { id: 633, category: 'sıfatlar', germanWord: 'taktlos', pronunciation: 'takt-loos', germanSentence: 'Diese Frage fand ich äußerst taktlos.', turkishWord: 'patavatsız, düşüncesiz', turkishSentence: 'Bu soruyu son derece patavatsızca buldum.' },
    { id: 634, category: 'sıfatlar', germanWord: 'tolerant', pronunciation: 'to-le-rant', germanSentence: 'Unsere Gesellschaft sollte toleranter werden.', turkishWord: 'hoşgörülü', turkishSentence: 'Toplumumuz daha hoşgörülü olmalı.' },
    { id: 635, category: 'sıfatlar', germanWord: 'tragisch', pronunciation: 'tra-giş', germanSentence: 'Der Unfall endete tragisch.', turkishWord: 'trajik', turkishSentence: 'Kaza trajik bir şekilde sonuçlandı.' },
    { id: 636, category: 'sıfatlar', germanWord: 'umstritten', pronunciation: 'um-ştri-tın', germanSentence: 'Dieses Gesetz ist politisch sehr umstritten.', turkishWord: 'tartışmalı, ihtilaflı', turkishSentence: 'Bu yasa siyasi açıdan oldukça tartışmalı.' },
    { id: 637, category: 'sıfatlar', germanWord: 'unablässig', pronunciation: 'un-ap-les-ik', germanSentence: 'Es regnete unablässig den ganzen Tag.', turkishWord: 'durmaksızın', turkishSentence: 'Bütün gün durmaksızın yağmur yağdı.' },
    { id: 638, category: 'sıfatlar', germanWord: 'unberechenbar', pronunciation: 'un-be-reh-ın-baar', germanSentence: 'Das Wetter in den Bergen ist unberechenbar.', turkishWord: 'hesaplanamaz, kestirilemez', turkishSentence: 'Dağlarda hava kestirilemezdir.' },
    { id: 639, category: 'sıfatlar', germanWord: 'unglaublich', pronunciation: 'un-glaup-lih', germanSentence: 'Das ist eine unglaublich gute Nachricht!', turkishWord: 'inanılmaz', turkishSentence: 'Bu inanılmaz iyi bir haber!' },
    { id: 640, category: 'sıfatlar', germanWord: 'umfangreich', pronunciation: 'um-fang-rayh', germanSentence: 'Das ist ein sehr umfangreiches Projekt.', turkishWord: 'kapsamlı, geniş çaplı', turkishSentence: 'Bu çok kapsamlı bir projedir.' }

];

export default data14;
