const data18 = [
    // --- Sürekli İlerleyiş (B2-C1 Kelimeleri) ---
    { id: 831, category: 'sıfatlar', germanWord: 'fachkundig', pronunciation: 'fah-kun-dik', germanSentence: 'Wir brauchen eine fachkundige Meinung.', turkishWord: 'uzman, işinin ehli', turkishSentence: 'Uzman (işinin ehli) bir görüşe ihtiyacımız var.' },
    { id: 832, category: 'sıfatlar', germanWord: 'famos', pronunciation: 'fa-moos', germanSentence: 'Das war eine famose Leistung!', turkishWord: 'harika, mükemmel', turkishSentence: 'Bu harika(mükemmel) bir performanstı!' },
    { id: 833, category: 'sıfatlar', germanWord: 'fanatisch', pronunciation: 'fa-naa-tiş', germanSentence: 'Die Fans jubelten fast schon fanatisch.', turkishWord: 'fanatik, bağnazca', turkishSentence: 'Taraftarlar neredeyse fanatikçe seviniyordu.' },
    { id: 834, category: 'sıfatlar', germanWord: 'feige', pronunciation: 'fay-gı', germanSentence: 'Das war ein sehr feiger Angriff.', turkishWord: 'korkak, namert', turkishSentence: 'Bu çok korkakça/namert bir saldırıydı.' },
    { id: 835, category: 'sıfatlar', germanWord: 'fiktiv', pronunciation: 'fik-tiif', germanSentence: 'Alle Charaktere hier sind fiktiv.', turkishWord: 'kurgusal, hayali, uydurma', turkishSentence: 'Buradaki tüm karakterler kurgusaldır.' },
    { id: 836, category: 'sıfatlar', germanWord: 'fidel', pronunciation: 'fi-deel', germanSentence: 'Opa ist heute sehr fidel.', turkishWord: 'neşeli, canlı, hayat dolu', turkishSentence: 'Büyükbaba bugün çok hayat dolu/neşeli.' },
    { id: 837, category: 'sıfatlar', germanWord: 'formidabel', pronunciation: 'for-mi-daa-bıl', germanSentence: 'Er bot eine formidable Vorstellung.', turkishWord: 'devasa, korkunç derecede iyi, muazzam', turkishSentence: 'O muazzam bir gösteri sundu.' },
    { id: 838, category: 'sıfatlar', germanWord: 'furios', pronunciation: 'fu-riy-oos', germanSentence: 'Das Spiel endete mit einem furiosen Finale.', turkishWord: 'coşkulu, fırtına gibi, ateşli', turkishSentence: 'Oyun coşkulu (fırtına gibi) bir finalle sona erdi.' },
    { id: 839, category: 'sıfatlar', germanWord: 'galant', pronunciation: 'ga-lant', germanSentence: 'Er war stets sehr höflich und galant.', turkishWord: 'kibar (kadınlara karşı), centilmen', turkishSentence: 'O daima çok kibar ve centilmendi.' },
    { id: 840, category: 'sıfatlar', germanWord: 'generös', pronunciation: 'ge-ne-röös', germanSentence: 'Das ist ein sehr generöser Vorschlag.', turkishWord: 'cömert', turkishSentence: 'Bu çok cömert bir teklif.' },

    // --- İsimler ---
    { id: 841, category: 'isimler', germanWord: 'das Gen', pronunciation: 'das geen', germanSentence: 'Das Talent liegt ihm in den Genen.', turkishWord: 'gen (biyoloji)', turkishSentence: 'Yetenek onun genlerinde var.' },
    { id: 842, category: 'isimler', germanWord: 'die Hybris', pronunciation: 'di hüüb-ris', germanSentence: 'Seine Hybris führte schließlich zum Untergang.', turkishWord: 'kibir, aşırı gurur', turkishSentence: 'Aşırı kibri(gururu) sonunda çöküşüne yol açtı.' },
    { id: 843, category: 'isimler', germanWord: 'die Instanz', pronunciation: 'di ins-tants', germanSentence: 'Das Gericht ist die höchste Instanz in diesem Fall.', turkishWord: 'mercii, makam, derece', turkishSentence: 'Mahkeme bu davada en yüksek merciidir.' },
    { id: 844, category: 'isimler', germanWord: 'das Individuum', pronunciation: 'das in-di-vii-du-um', germanSentence: 'Jedes Individuum ist einzigartig.', turkishWord: 'birey, fert', turkishSentence: 'Her birey eşsizdir.' },
    { id: 845, category: 'isimler', germanWord: 'der Impuls', pronunciation: 'der im-puls', germanSentence: 'Sie handelte aus einem plötzlichen Impuls heraus.', turkishWord: 'itki, dürtü, uyarı', turkishSentence: 'O ani bir dürtüyle/itkiyle hareket etti.' },
    { id: 846, category: 'isimler', germanWord: 'der Idealismus', pronunciation: 'der idea-lis-mus', germanSentence: 'Ohne seinen Idealismus hätten wir aufgegeben.', turkishWord: 'idealizm, ülkücülük', turkishSentence: 'Onun idealizmi olmasaydı pes ederdik.' },
    { id: 847, category: 'isimler', germanWord: 'die Ironie', pronunciation: 'di iroo-nii', germanSentence: 'Die Ironie des Schicksals ist unverkennbar.', turkishWord: 'ironi, alay', turkishSentence: 'Kaderin ironisi apaçık(inkar edilemez).' },
    { id: 848, category: 'isimler', germanWord: 'die Illusion', pronunciation: 'di ilu-zyon', germanSentence: 'Geben Sie sich keinen Illusionen hin.', turkishWord: 'illüzyon, yanılgı, asılsız hayal', turkishSentence: 'Kendinizi asılsız hayallere(yanılgılara) kaptırmayın.' },
    { id: 849, category: 'isimler', germanWord: 'die Kontroverse /-n', pronunciation: 'di kon-tro-ver-zı', germanSentence: 'Dies löste eine große politische Kontroverse aus.', turkishWord: 'tartışma, ihtilaf', turkishSentence: 'Bu büyük bir siyasi tartışmayı tetikledi.' },
    { id: 850, category: 'isimler', germanWord: 'die Kulisse /-n', pronunciation: 'di ku-li-sı', germanSentence: 'Das Schloss bot die perfekte Kulisse für den Film.', turkishWord: 'kulise, arka plan, dekor', turkishSentence: 'Şato film için mükemmel bir arka plan(dekor) sundu.' },

    // --- Fiiller ---
    { id: 851, category: 'fiiller', germanWord: 'generieren', pronunciation: 'ge-ne-rii-rın', germanSentence: 'Das System muss mehr Umsatz generieren.', turkishWord: 'üretmek, oluşturmak, meydana getirmek', turkishSentence: 'Sistem daha fazla ciro/gelir üretmelidir.' },
    { id: 852, category: 'fiiller', germanWord: 'gewährleisten', pronunciation: 'ge-veer-lays-tın', germanSentence: 'Die Sicherheit muss stets gewährleistet sein.', turkishWord: 'garanti etmek, sağlamak', turkishSentence: 'Güvenlik her zaman garanti edilmelidir(sağlanmalıdır).' },
    { id: 853, category: 'fiiller', germanWord: 'glorifizieren', pronunciation: 'glo-ri-fi-tsii-rın', germanSentence: 'Die Vergangenheit wird oft glorifiziert.', turkishWord: 'yüceltmek, övmek', turkishSentence: 'Geçmiş genellikle yüceltilir.' },
    { id: 854, category: 'fiiller', germanWord: 'halluzinieren', pronunciation: 'ha-lu-tsi-nii-rın', germanSentence: 'Unter dem Einfluss des Gifts begann er zu halluzinieren.', turkishWord: 'halüsinasyon görmek', turkishSentence: 'Zehirin etkisi altında halüsinasyon görmeye başladı.' },
    { id: 855, category: 'fiiller', germanWord: 'harmonisieren', pronunciation: 'har-mo-ni-zii-rın', germanSentence: 'Wir müssen die Arbeitsabläufe harmonisieren.', turkishWord: 'uyumlaştırmak, ahenk sağlamak', turkishSentence: 'İş akışlarını uyumlu hale getirmeliyiz.' },
    { id: 856, category: 'fiiller', germanWord: 'heiraten (mecaz)', pronunciation: 'hay-ra-tın', germanSentence: 'Er hat sich mit dieser Firma richtig verheiratet.', turkishWord: 'bağlanmak, kopamamak (mecaz)', turkishSentence: 'O bu şirketle adeta evlendi (bağlandı kopamıyor).' },
    { id: 857, category: 'fiiller', germanWord: 'improvisieren', pronunciation: 'im-pro-vi-zii-rın', germanSentence: 'Als das Mikrofon ausfiel, mussten wir improvisieren.', turkishWord: 'doğaçlama yapmak', turkishSentence: 'Mikrofon bozulduğunda doğaçlama yapmak zorunda kaldık.' },
    { id: 858, category: 'fiiller', germanWord: 'initiieren', pronunciation: 'i-ni-tsiy-ii-rın', germanSentence: 'Wir wollen ein neues Forschungsprojekt initiieren.', turkishWord: 'başlatmak, önayak olmak', turkishSentence: 'Yeni bir araştırma projesi başlatmak istiyoruz.' },
    { id: 859, category: 'fiiller', germanWord: 'investieren', pronunciation: 'in-ves-tii-rın', germanSentence: 'Du musst mehr Zeit in das Projekt investieren.', turkishWord: 'yatırım yapmak', turkishSentence: 'Projeye daha fazla zaman ayırmalı/yatırmalısın.' },
    { id: 860, category: 'fiiller', germanWord: 'irritieren', pronunciation: 'i-ri-tii-rın', germanSentence: 'Lass dich nicht von ihr irritieren.', turkishWord: 'sinirlendirmek, şaşırtmak, kafa karıştırmak', turkishSentence: 'Onun senin kafanı karıştırmasına (seni sinirlendirmesine) izin verme.' },

    // --- Sıfatlar/Zarflar ---
    { id: 861, category: 'sıfatlar', germanWord: 'galaktisch', pronunciation: 'ga-lak-tiş', germanSentence: 'Die Ausmaße des Projekts sind geradezu galaktisch.', turkishWord: 'galaktik, devasa, muazzam', turkishSentence: 'Projenin boyutları adeta devasa(galaktik).' },
    { id: 862, category: 'sıfatlar', germanWord: 'gravierend', pronunciation: 'gra-vii-rınt', germanSentence: 'Das sind gravierende Fehler im System.', turkishWord: 'ciddi, ağır, mühim', turkishSentence: 'Bunlar sistemdeki ciddi/ağır hatalardır.' },
    { id: 863, category: 'sıfatlar', germanWord: 'grotesk', pronunciation: 'gro-tesk', germanSentence: 'Diese Anschuldigungen sind völlig grotesk.', turkishWord: 'gülünç, absürt, tuhaf', turkishSentence: 'Bu suçlamalar tamamen gülünçtür(absürttür).' },
    { id: 864, category: 'sıfatlar', germanWord: 'harmonisch', pronunciation: 'har-mo-niş', germanSentence: 'Sie führen eine sehr harmonische Ehe.', turkishWord: 'uyumlu, ahenkli', turkishSentence: 'Çok uyumlu bir evlilik yürütüyorlar.' },
    { id: 865, category: 'sıfatlar', germanWord: 'heikel', pronunciation: 'hay-kıl', germanSentence: 'Diese Angelegenheit ist politisch sehr heikel.', turkishWord: 'hassas, çetrefilli, nazik', turkishSentence: 'Bu mesele siyasi açıdan oldukça çetrefilli/hassastır.' },
    { id: 866, category: 'sıfatlar', germanWord: 'heroisch', pronunciation: 'he-ro-iş', germanSentence: 'Es war ein heroischer Versuch, alle zu retten.', turkishWord: 'kahramanca', turkishSentence: 'Herkesi kurtarmak kahramanca bir girişimdi.' },
    { id: 867, category: 'sıfatlar', germanWord: 'hysterisch', pronunciation: 'hüs-tee-riş', germanSentence: 'Bitte reagier doch nicht gleich so hysterisch!', turkishWord: 'histerik', turkishSentence: 'Lütfen hemen bu kadar histerik tepki verme!' },
    { id: 868, category: 'sıfatlar', germanWord: 'ignorant', pronunciation: 'ig-no-rant', germanSentence: 'Sein arrogantes und ignorantes Verhalten stört mich.', turkishWord: 'cahil, bilmezlikten gelen, umursamaz', turkishSentence: 'Onun kibirli ve umursamaz davranışı beni rahatsız ediyor.' },
    { id: 869, category: 'sıfatlar', germanWord: 'immateriell', pronunciation: 'i-ma-te-ri-yel', germanSentence: 'Liebe ist ein immaterieller Wert.', turkishWord: 'manevi, maddi olmayan', turkishSentence: 'Sevgi manevi (maddi olmayan) bir değerdir.' },
    { id: 870, category: 'sıfatlar', germanWord: 'immens', pronunciation: 'i-mens', germanSentence: 'Der Aufwand für das Projekt war immens.', turkishWord: 'muazzam, devasa', turkishSentence: 'Proje için harcanan emek muazzamdı.' },

    // --- Kombin: Bağlaç ve İsimler ---
    { id: 871, category: 'bağlaçlar', germanWord: 'gelegentlich', pronunciation: 'ge-ley-gınt-lih', germanSentence: 'Wir sehen uns gelegentlich in der Stadt.', turkishWord: 'ara sıra, fırsat düştükçe', turkishSentence: 'Şehirde ara sıra görüşüyoruz.' },
    { id: 872, category: 'bağlaçlar', germanWord: 'gleichbedeutend', pronunciation: 'glayh-be-doy-tınt', germanSentence: 'Schweigen ist hier oft gleichbedeutend mit Zustimmung.', turkishWord: 'eşanlamlı, aynı anlama gelen', turkishSentence: 'Burada susmak genellikle onayla eşanlamlıdır.' },
    { id: 873, category: 'bağlaçlar', germanWord: 'gößtenteils', pronunciation: 'grös-tın-tayls', germanSentence: 'Die Arbeit ist größtenteils erledigt.', turkishWord: 'büyük bir kısmıyla, çoğunlukla', turkishSentence: 'İşin büyük bir kısmı (çoğunlukla) tamamlandı.' },
    { id: 874, category: 'bağlaçlar', germanWord: 'insgeheim', pronunciation: 'ins-ge-haym', germanSentence: 'Insgeheim wusste sie, dass er recht hatte.', turkishWord: 'gizliden gizliye, içten içe', turkishSentence: 'İçten içe onun haklı olduğunu biliyordu.' },
    { id: 875, category: 'bağlaçlar', germanWord: 'unmittelbar', pronunciation: 'un-mi-tıl-baar', germanSentence: 'Das geschah unmittelbar nach dem Krieg.', turkishWord: 'doğrudan, hemen (ardından/öncesinde)', turkishSentence: 'Bu savaştan hemen sonra gerçekleşti.' },
    { id: 876, category: 'isimler', germanWord: 'die Komplexität', pronunciation: 'kom-plek-si-teet', germanSentence: 'Die Komplexität des Systems wird oft unterschät.', turkishWord: 'karmaşıklık', turkishSentence: 'Sistemin karmaşıklığı sıklıkla hafife alınır.' },
    { id: 877, category: 'isimler', germanWord: 'der Konsens', pronunciation: 'der kon-zens', germanSentence: 'Wir müssen versuchen, einen Konsens zu finden.', turkishWord: 'uzlaşma, fikir birliği', turkishSentence: 'Bir fikir birliği (uzlaşı) bulmaya çalışmalıyız.' },
    { id: 878, category: 'isimler', germanWord: 'das Kriterium /-ien', pronunciation: 'das kri-tee-riyum', germanSentence: 'Was waren die Kriterien für diese Entscheidung?', turkishWord: 'ölçüt, kıstas', turkishSentence: 'Bu karar için ölçütler neydi?' },
    { id: 879, category: 'isimler', germanWord: 'die Kritik /-en', pronunciation: 'di kri-tik', germanSentence: 'Konstruktive Kritik ist immer willkommen.', turkishWord: 'eleştiri', turkishSentence: 'Yapıcı eleştiri her zaman hoş karşılanır.' },
    { id: 880, category: 'isimler', germanWord: 'das Labyrinth /-e', pronunciation: 'das la-bü-rint', germanSentence: 'Ich verirrte mich in dem Labyrinth der Gassen.', turkishWord: 'labirent', turkishSentence: 'Sokakların labirentinde kayboldum.' },

    // --- Ekstra Kelimeler ---
    { id: 881, category: 'fiiller', germanWord: 'isolieren', pronunciation: 'i-zo-lii-rın', germanSentence: 'Man musste den kranken Patienten sofort isolieren.', turkishWord: 'izole etmek, yalıtmak', turkishSentence: 'Hasta hastayı derhal izole etmek gerekti.' },
    { id: 882, category: 'fiiller', germanWord: 'kalkulieren', pronunciation: 'kal-ku-lii-rın', germanSentence: 'Ich habe solche Verzögerungen nicht kalkuliert.', turkishWord: 'hesaplamak', turkishSentence: 'Böyle gecikmeleri hesaba katmadım (hesaplamadım).' },
    { id: 883, category: 'fiiller', germanWord: 'karikieren', pronunciation: 'ka-ri-kii-rın', germanSentence: 'Der Zeichner liebte es, die Politiker zu karikieren.', turkishWord: 'karikatürize etmek', turkishSentence: 'Çizer/Ressam, politikacıları karikatürize etmeyi seviyordu.' },
    { id: 884, category: 'fiiller', germanWord: 'kommentieren', pronunciation: 'ko-men-tii-rın', germanSentence: 'Ich möchte das Gerücht nicht kommentieren.', turkishWord: 'yorumlamak, yorum yapmak', turkishSentence: 'Bu dedikoduyu yorumlamak istemiyorum.' },
    { id: 885, category: 'fiiller', germanWord: 'konditionieren', pronunciation: 'kon-di-tsiyo-nii-rın', germanSentence: 'Viele Hunde lassen sich leicht konditionieren.', turkishWord: 'şartlandırmak', turkishSentence: 'Birçok köpek kolayca şartlandırılabilir.' },
    { id: 886, category: 'sıfatlar', germanWord: 'immun', pronunciation: 'i-muun', germanSentence: 'Niemand ist völlig immun gegen Schmeicheleien.', turkishWord: 'bağışık, etkilenmeyen', turkishSentence: 'Kimse dalkavukluğa karşı tamamen bağışık/etkisiz değildir.' },
    { id: 887, category: 'sıfatlar', germanWord: 'impulsiv', pronunciation: 'im-pul-ziif', germanSentence: 'Sie ist ein sehr impulsiver Mensch.', turkishWord: 'dürtüsel, içtepisel, fevri', turkishSentence: 'O çok fevri (dürtüsel) bir insandır.' },
    { id: 888, category: 'sıfatlar', germanWord: 'inadäquat', pronunciation: 'in-a-de-kvaat', germanSentence: 'Dieses Verhalten ist völlig inadäquat.', turkishWord: 'uygun olmayan, yetersiz', turkishSentence: 'Bu davranış tamamen uygunsuzdur.' },
    { id: 889, category: 'sıfatlar', germanWord: 'indiskret', pronunciation: 'in-dis-kreet', germanSentence: 'Das ist eine etwas indiskrete Frage.', turkishWord: 'patavatsız, sır tutmayan, sırnaşık', turkishSentence: 'Bu biraz patavatsızca (gizliliği bozan) bir sorudur.' },
    { id: 890, category: 'sıfatlar', germanWord: 'infernialisch', pronunciation: 'in-fer-naa-liş', germanSentence: 'Der Lärm der Maschinen war infernalisch.', turkishWord: 'cehennem gibi, şeytani (gürültülü vb.)', turkishSentence: 'Makinelerin gürültüsü cehennemi/korkunç derecedeydi.' }
];

export default data18;
