const data10 = [
    // --- İsimler ---
    { id: 406, category: 'isimler', germanWord: 'der Ablauf', pronunciation: 'der ap-lauf', germanSentence: 'Wir müssen den Ablauf der Veranstaltung planen.', turkishWord: 'işleyiş, akış', turkishSentence: 'Etkinliğin akışını planlamalıyız.' },
    { id: 407, category: 'isimler', germanWord: 'die Bedrohung /-en', pronunciation: 'di be-dro-ung', germanSentence: 'Die globale Erwärmung ist eine ernsthafte Bedrohung.', turkishWord: 'tehdit', turkishSentence: 'Küresel ısınma ciddi bir tehdittir.' },
    { id: 408, category: 'isimler', germanWord: 'das Bedürfnis /-se', pronunciation: 'das be-dürf-nis', germanSentence: 'Jeder Mensch hat das Bedürfnis nach Anerkennung.', turkishWord: 'ihtiyaç, gereksinim', turkishSentence: 'Her insanın takdir edilme ihtiyacı vardır.' },
    { id: 409, category: 'isimler', germanWord: 'die Beförderung /-en', pronunciation: 'di be-för-de-rung', germanSentence: 'Herzlichen Glückwunsch zu deiner Beförderung!', turkishWord: 'terfi, taşıma', turkishSentence: 'Terfiniz için tebrikler (kalpten tebrikler)!' },
    { id: 410, category: 'isimler', germanWord: 'die Begegnung /-en', pronunciation: 'di be-geyg-nung', germanSentence: 'Das war eine sehr interessante Begegnung.', turkishWord: 'karşılaşma, görüşme', turkishSentence: 'Bu çok ilginç bir karşılaşmaydı.' },
    { id: 411, category: 'isimler', germanWord: 'der Bestandteil /-e', pronunciation: 'der be-ştant-tayl', germanSentence: 'Motivation ist ein wichtiger Bestandteil des Erfolgs.', turkishWord: 'bileşen, unsur', turkishSentence: 'Motivasyon başarının önemli bir unsurudur.' },
    { id: 412, category: 'isimler', germanWord: 'die Beteiligung /-en', pronunciation: 'di be-tay-li-gung', germanSentence: 'Wir danken Ihnen für Ihre rege Beteiligung.', turkishWord: 'katılım', turkishSentence: 'Canlı katılımınız için size teşekkür ederiz.' },
    { id: 413, category: 'isimler', germanWord: 'das Einkommen /-', pronunciation: 'das ayn-ko-mın', germanSentence: 'Viele Familien haben nur ein geringes Einkommen.', turkishWord: 'gelir, kazanç', turkishSentence: 'Birçok ailenin sadece düşük bir geliri var.' },
    { id: 414, category: 'isimler', germanWord: 'die Einschränkung /-en', pronunciation: 'di ayn-şren-kung', germanSentence: 'Wir müssen mit einigen Einschränkungen rechnen.', turkishWord: 'kısıtlama, sınırlama', turkishSentence: 'Bazı kısıtlamaları hesaba katmalıyız.' },
    { id: 415, category: 'isimler', germanWord: 'die Empfehlung /-en', pronunciation: 'di emp-fey-lung', germanSentence: 'Ich kann dieses Buch als Empfehlung weitergeben.', turkishWord: 'tavsiye, öneri', turkishSentence: 'Bu kitabı bir tavsiye olarak aktarabilirim.' },

    // --- Fiiller ---
    { id: 416, category: 'fiiller', germanWord: 'widerspiegeln', pronunciation: 'vi-dır-şpii-gıln', germanSentence: 'Das Ergebnis widerspiegelt unsere echten Bemühungen.', turkishWord: 'yansıtmak', turkishSentence: 'Sonuç, gerçek çabalarımızı yansıtıyor.' },
    { id: 417, category: 'fiiller', germanWord: 'wiederherstellen', pronunciation: 'vii-dır-heer-şte-lın', germanSentence: 'Wir müssen das alte System wiederherstellen.', turkishWord: 'eski haline getirmek, restore etmek', turkishSentence: 'Eski sistemi tekrar geri yüklemeliyiz.' },
    { id: 418, category: 'fiiller', germanWord: 'überschätzen', pronunciation: 'ü-bır-şet-sın', germanSentence: 'Er hat seine eigenen Fähigkeiten maßlos überschätzt.', turkishWord: 'gözünde büyütmek, abartmak', turkishSentence: 'Kendi yeteneklerini aşırı derecede abarttı (gözünde büyüttü).' },
    { id: 419, category: 'fiiller', germanWord: 'verschaffen (sich)', pronunciation: 'fer-şa-fın', germanSentence: 'Ich muss mir erst einen Überblick verschaffen.', turkishWord: 'sağlamak, elde etmek', turkishSentence: 'Öncelikle genel bir bakış(izlenim) sağlamalıyım.' },
    { id: 420, category: 'fiiller', germanWord: 'verabscheuen', pronunciation: 'fer-ap-şoy-ın', germanSentence: 'Ich verabscheue jede Form von Gewalt.', turkishWord: 'iğrenmek, nefret etmek', turkishSentence: 'Şiddetin her türlüsünden nefret ediyorum.' },
    { id: 421, category: 'fiiller', germanWord: 'verallgemeinern', pronunciation: 'fer-al-ge-may-nırn', germanSentence: 'Man darf dieses Problem nicht verallgemeinern.', turkishWord: 'genelleme yapmak', turkishSentence: 'Bu sorunu genellememek (genelleştirmemek) gerekir.' },
    { id: 422, category: 'fiiller', germanWord: 'vereinfachen', pronunciation: 'fer-ayn-fa-hın', germanSentence: 'Diese Maßnahme wird das Verfahren sehr vereinfachen.', turkishWord: 'basitleştirmek, kolaylaştırmak', turkishSentence: 'Bu önlem prosedürü oldukça basitleştirecek.' },
    { id: 423, category: 'fiiller', germanWord: 'verherrlichen', pronunciation: 'fer-her-li-hın', germanSentence: 'In diesem Film wird der Krieg nicht verherrlicht.', turkishWord: 'yüceltmek, göklere çıkarmak', turkishSentence: 'Bu filmde savaş yüceltilmiyor.' },
    { id: 424, category: 'fiiller', germanWord: 'unterschätzen', pronunciation: 'un-tır-şet-sın', germanSentence: 'Unterschätze niemals die Macht der Gewohnheit.', turkishWord: 'küçümsemek, hafife almak', turkishSentence: 'Alışkanlığın gücünü asla hafife alma.' },
    { id: 425, category: 'fiiller', germanWord: 'entwerten', pronunciation: 'ent-ver-tın', germanSentence: 'Bitte entwerten Sie Ihr Ticket vor Fahrtantritt.', turkishWord: 'değerden düşürmek, iptal/valide etmek', turkishSentence: 'Lütfen yolculuğa başlamadan önce biletinizi onaylatın (valide edin).' },

    // --- Sıfatlar ---
    { id: 426, category: 'sıfatlar', germanWord: 'unentbehrlich', pronunciation: 'un-ent-beer-lih', germanSentence: 'Sie ist eine unentbehrliche Mitarbeiterin geworden.', turkishWord: 'vazgeçilmez, elzem', turkishSentence: 'O vazgeçilmez bir çalışan haline geldi.' },
    { id: 427, category: 'sıfatlar', germanWord: 'unerbittlich', pronunciation: 'un-er-bit-lih', germanSentence: 'Die Zeit vergeht unerbittlich schnell.', turkishWord: 'amansız, acımasız', turkishSentence: 'Zaman amansızca hızlı geçiyor.' },
    { id: 428, category: 'sıfatlar', germanWord: 'unermüdlich', pronunciation: 'un-er-müüt-lih', germanSentence: 'Er setzte sich unermüdlich für die Armen ein.', turkishWord: 'yorulmak bilmeyen, bıkıp usanmayan', turkishSentence: 'Fakirler için bıkıp usanmadan çaba gösterdi.' },
    { id: 429, category: 'sıfatlar', germanWord: 'unerwartet', pronunciation: 'un-er-var-tıt', germanSentence: 'Der Besuch kam für uns völlig unerwartet.', turkishWord: 'beklenmedik', turkishSentence: 'Ziyaret bizim için tamamen beklenmedik oldu.' },
    { id: 430, category: 'sıfatlar', germanWord: 'ungewiss', pronunciation: 'un-ge-vis', germanSentence: 'Die weitere Entwicklung ist völlig ungewiss.', turkishWord: 'belirsiz, meçhul', turkishSentence: 'İleriki gelişim völlig(tamamen) belirsiz.' },
    { id: 431, category: 'sıfatlar', germanWord: 'unvermeidlich', pronunciation: 'un-fer-mayt-lih', germanSentence: 'Ein Konflikt war in dieser Lage unvermeidlich.', turkishWord: 'kaçınılmaz', turkishSentence: 'Bu durumda bir çatışma kaçınılmazdı.' },
    { id: 432, category: 'sıfatlar', germanWord: 'verantwortungsvoll', pronunciation: 'fer-ant-vor-tunks-fol', germanSentence: 'Sie füllt diese verantwortungsvolle Position gut aus.', turkishWord: 'sorumluluk sahibi, sorumluluk gerektiren', turkishSentence: 'O bu sorumluluk gerektiren pozisyonu iyi dolduruyor.' },
    { id: 433, category: 'sıfatlar', germanWord: 'vergeblich', pronunciation: 'fer-gep-lih', germanSentence: 'All unsere Mühen waren leider vergeblich.', turkishWord: 'nafile, boşuna', turkishSentence: 'Tüm çabalarımız maalesef nafile(boşuna) idi.' },
    { id: 434, category: 'sıfatlar', germanWord: 'vorsorglich', pronunciation: 'for-zork-lih', germanSentence: 'Ich habe vorsorglich schon mal einen Tisch reserviert.', turkishWord: 'önlem olarak, ihtiyaten', turkishSentence: 'Ne olur ne olmaz diye önlem olarak bir masa ayırttım.' },
    { id: 435, category: 'sıfatlar', germanWord: 'zögerlich', pronunciation: 'tsö-gır-lih', germanSentence: 'Sie stimmte seinem Vorschlag nur zögerlich zu.', turkishWord: 'duraksayarak, çekingen', turkishSentence: 'Onun teklifini sadece çekingen(!tereddütle) kabul etti.' },

    // --- Bağlaçlar / Zarflar ---
    { id: 436, category: 'bağlaçlar', germanWord: 'dessentwegen', pronunciation: 'de-sı-nt-vey-gın', germanSentence: 'Er war krank, und dessentwegen kam er nicht.', turkishWord: 'bundan dolayı, bu yüzden', turkishSentence: 'O hastaydı ve bundan dolayı gelmedi.' },
    { id: 437, category: 'bağlaçlar', germanWord: 'fernerhin', pronunciation: 'fer-nır-hin', germanSentence: 'Wir wollen fernerhin in Kontakt bleiben.', turkishWord: 'bundan böyle, ileride de', turkishSentence: 'Bundan böyle de iletişimde kalmak istiyoruz.' },
    { id: 438, category: 'bağlaçlar', germanWord: 'je nachdem', pronunciation: 'yey nah-deem', germanSentence: 'Wir gehen raus oder bleiben, je nachdem wie das Wetter wird.', turkishWord: 'duruma göre, -e bağlı olarak', turkishSentence: 'Havanın nasıl olacağına bağlı olarak dışarı çıkacağız veya kalacağız.' },
    { id: 439, category: 'bağlaçlar', germanWord: 'kurzum', pronunciation: 'kurt-sum', germanSentence: 'Es war teuer, schlecht – kurzum: ein Desaster.', turkishWord: 'kısacası, sözün kısası', turkishSentence: 'Pahalıydı, kötüydü – kısacası: bir felaketti.' },
    { id: 440, category: 'bağlaçlar', germanWord: 'schlimmstenfalls', pronunciation: 'şlim-stın-fals', germanSentence: 'Schlimmstenfalls müssen wir alles noch mal machen.', turkishWord: 'en kötü ihtimalle', turkishSentence: 'En kötü ihtimalle her şeyi tekrar yapmak zorundayız.' }
];

export default data10;
