const data15 = [
    // --- Bağlaçlar / Zarflar / İfadeler ---
    { id: 641, category: 'bağlaçlar', germanWord: 'allenfalls', pronunciation: 'a-lın-fals', germanSentence: 'Es waren allenfalls 20 Personen anwesend.', turkishWord: 'olsa olsa, en fazla', turkishSentence: 'Orada olsa olsa 20 kişi mevcuttu.' },
    { id: 642, category: 'bağlaçlar', germanWord: 'allmählich', pronunciation: 'al-mee-lih', germanSentence: 'Mir wird allmählich kalt.', turkishWord: 'yavaş yavaş, gitgide', turkishSentence: 'Yavaş yavaş üşüyorum(bana soğuk geliyor).' },
    { id: 643, category: 'bağlaçlar', germanWord: 'andererseits', pronunciation: 'an-de-rır-zayts', germanSentence: 'Einerseits möchte ich gehen, andererseits auch bleiben.', turkishWord: 'öte yandan, diğer taraftan', turkishSentence: 'Bir yandan gitmek istiyorum, öte yandan da kalmak.' },
    { id: 644, category: 'bağlaçlar', germanWord: 'anschließend', pronunciation: 'an-şlii-zınt', germanSentence: 'Wir gehen essen, anschließend ins Kino.', turkishWord: 'ardından, akabinde', turkishSentence: 'Yemeğe gidiyoruz, ardından sinemaya.' },
    { id: 645, category: 'bağlaçlar', germanWord: 'aufeinander', pronunciation: 'auf-ayn-an-dır', germanSentence: 'Die Probleme folgten dicht aufeinander.', turkishWord: 'birbiri ardına, üst üste', turkishSentence: 'Sorunlar sıkı bir şekilde üst üste takip etti.' },
    { id: 646, category: 'bağlaçlar', germanWord: 'ausgerechnet', pronunciation: 'aus-ge-reh-nıt', germanSentence: 'Ausgerechnet heute muss es regnen!', turkishWord: 'aksilik bu ya, tam da, bula bula', turkishSentence: 'Aksilik bu ya, tam da bugün yağmur yağması gerekiyor!' },
    { id: 647, category: 'bağlaçlar', germanWord: 'demnach', pronunciation: 'dem-naah', germanSentence: 'Das Geschäft ist demnach geschlossen.', turkishWord: 'buna göre, şuna bakılırsa', turkishSentence: 'Buna göre dükkan kapalı.' },
    { id: 648, category: 'bağlaçlar', germanWord: 'deshalb', pronunciation: 'des-halp', germanSentence: 'Ich bin müde, deshalb gehe ich ins Bett.', turkishWord: 'bu nedenle, o yüzden', turkishSentence: 'Yorgunum, bu nedenle yatağa gidiyorum.' },
    { id: 649, category: 'bağlaçlar', germanWord: 'einerseits', pronunciation: 'ay-nır-zayts', germanSentence: 'Einerseits ist das gut, aber andererseits teuer.', turkishWord: 'bir yandan, bir taraftan', turkishSentence: 'Bir taraftan bu iyi, ama diğer taraftan pahalı.' },
    { id: 650, category: 'bağlaçlar', germanWord: 'weitgehend', pronunciation: 'vayt-gey-ınt', germanSentence: 'Das Problem ist mittlerweile weitgehend gelöst.', turkishWord: 'büyük ölçüde, geniş çapta', turkishSentence: 'Sorun bu arada büyük ölçüde çözüldü.' },

    // --- İsimler ---
    { id: 651, category: 'isimler', germanWord: 'die Faszination', pronunciation: 'fas-tsi-na-tsion', germanSentence: 'Die Faszination des Weltraums ist grenzenlos.', turkishWord: 'büyü, cazibe, çekicilik', turkishSentence: 'Uzayın cazibesi(büyüsü) sınırsızdır.' },
    { id: 652, category: 'isimler', germanWord: 'der Fortschritt /-e', pronunciation: 'fort-şrit', germanSentence: 'Wir haben einen großen Fortschritt gemacht.', turkishWord: 'ilerleme, gelişme', turkishSentence: 'Büyük bir ilerleme kaydettik.' },
    { id: 653, category: 'isimler', germanWord: 'der Gehalt', pronunciation: 'der ge-halt', germanSentence: 'Der Film hat keinen philosophischen Gehalt.', turkishWord: 'içerik (anlamsal), muhteva', turkishSentence: 'Filmin felsefi bir içeriği yok. (Not: das Gehalt = maaş)' },
    { id: 654, category: 'isimler', germanWord: 'der Genuss /"e', pronunciation: 'der ge-nus', germanSentence: 'Das Konzert war ein echter Ohrenschmaus und Genuss.', turkishWord: 'zevk, keyif, ziyafet', turkishSentence: 'Konser gerçek bir müzik ziyafeti ve keyifti.' },
    { id: 655, category: 'isimler', germanWord: 'die Gerechtigkeit', pronunciation: 'di ge-reh-tih-kayt', germanSentence: 'Alle streben nach sozialer Gerechtigkeit.', turkishWord: 'adalet', turkishSentence: 'Herkes sosyal adaleti (sağlamayı) çabalıyor.' },
    { id: 656, category: 'isimler', germanWord: 'der Glaube', pronunciation: 'der glau-bı', germanSentence: 'Er hat den Glauben an sich selbst nie verloren.', turkishWord: 'inanç', turkishSentence: 'Kendine olan inancını hiç kaybetmedi.' },
    { id: 657, category: 'isimler', germanWord: 'die Grundlage /-n', pronunciation: 'di grunt-la-gı', germanSentence: 'Vertrauen ist die Grundlage jeder Beziehung.', turkishWord: 'temel, zemin', turkishSentence: 'Güven her ilişkinin temelidir.' },
    { id: 658, category: 'isimler', germanWord: 'die Haftung', pronunciation: 'di haf-tung', germanSentence: 'Wir übernehmen keine Haftung für Garderobe.', turkishWord: 'sorumluluk, yükümlülük', turkishSentence: 'Gardırop için hiçbir sorumluluk kabul etmiyoruz.' },
    { id: 659, category: 'isimler', germanWord: 'die Identifikation', pronunciation: 'di i-den-ti-fi-ka-tsion', germanSentence: 'Die Identifikation mit der Firma ist hoch.', turkishWord: 'özdeşleşme, kimlik belirleme', turkishSentence: 'Şirketle özdeşleşme (bağ kurma) oranı yüksektir.' },
    { id: 660, category: 'isimler', germanWord: 'die Illusion /-en', pronunciation: 'di i-lu-tsion', germanSentence: 'Ich mache mir keine Illusionen über ihn.', turkishWord: 'hayal, kuruntu, yanılgı', turkishSentence: 'Onun hakkında hiçbir hayale(kuruntuya) kapılmıyorum.' },

    // --- Fiiller ---
    { id: 661, category: 'fiiller', germanWord: 'einmischen (sich)', pronunciation: 'ayn-mi-şın', germanSentence: 'Misch dich bitte nicht in meine Angelegenheiten ein.', turkishWord: 'araya girmek, karışmak', turkishSentence: 'Lütfen benim meselelerime karışma.' },
    { id: 662, category: 'fiiller', germanWord: 'einnisten (sich)', pronunciation: 'ayn-nis-tın', germanSentence: 'Das Virus hat sich im System eingenistet.', turkishWord: 'yuvalanmak, yerleşmek', turkishSentence: 'Virüs sisteme yuvalandı(yerleşti).' },
    { id: 663, category: 'fiiller', germanWord: 'entbehren', pronunciation: 'ent-bee-rın', germanSentence: 'Diese Behauptung entbehrt jeder Grundlage.', turkishWord: 'yoksun olmak, mahrum olmak', turkishSentence: 'Bu iddia her türlü temelden yoksundur.' },
    { id: 664, category: 'fiiller', germanWord: 'entwerfen', pronunciation: 'ent-ver-fın', germanSentence: 'Der Architekt hat ein neues Haus entworfen.', turkishWord: 'tasarlamak, çizmek', turkishSentence: 'Mimar yeni bir ev tasarladı.' },
    { id: 665, category: 'fiiller', germanWord: 'erfassen', pronunciation: 'er-fa-sın', germanSentence: 'Es ist schwer, das Problem komplett zu erfassen.', turkishWord: 'kavramak, idrak etmek, kayıt altına almak', turkishSentence: 'Sorunu tamamen kavramak(idrak etmek) zor.' },
    { id: 666, category: 'fiiller', germanWord: 'erklimmen', pronunciation: 'er-kli-mın', germanSentence: 'Sie konnte endlich den Gipfel erklimmen.', turkishWord: 'tırmanmak (zorlukla)', turkishSentence: 'Sonunda zirveye tırmanabildi.' },
    { id: 667, category: 'fiiller', germanWord: 'erstatten', pronunciation: 'er-şta-tın', germanSentence: 'Wir erstatten Ihnen den Kaufpreis.', turkishWord: 'iade etmek, geri ödemek', turkishSentence: 'Size satın alma bedelini iade ediyoruz.' },
    { id: 668, category: 'fiiller', germanWord: 'evaluieren', pronunciation: 'e-va-lu-ii-rın', germanSentence: 'Die Ergebnisse müssen neu evaluiert werden.', turkishWord: 'değerlendirmek', turkishSentence: 'Sonuçlar yeniden değerlendirilmelidir.' },
    { id: 669, category: 'fiiller', germanWord: 'faszinieren', pronunciation: 'fas-tsi-nii-rın', germanSentence: 'Sein Vortrag hat die Zuhörer fasziniert.', turkishWord: 'büyülemek, hayran bırakmak', turkishSentence: 'Sunumu dinleyicileri büyüledi.' },
    { id: 670, category: 'fiiller', germanWord: 'fluktuieren', pronunciation: 'fluk-tu-ii-rın', germanSentence: 'Die Preise fluktuieren momentan sehr stark.', turkishWord: 'dalgalanmak', turkishSentence: 'Fiyatlar şu anda çok güçlü bir şekilde dalgalanıyor.' },

    // --- Sıfatlar ---
    { id: 671, category: 'sıfatlar', germanWord: 'unerlässlich', pronunciation: 'un-er-les-lih', germanSentence: 'Gute Computerkenntnisse sind heute unerlässlich.', turkishWord: 'elzem, vazgeçilmez', turkishSentence: 'İyi bilgisayar bilgisi bugün elzemdir.' },
    { id: 672, category: 'sıfatlar', germanWord: 'unmündig', pronunciation: 'un-mün-dik', germanSentence: 'Das Kind ist rechtlich noch unmündig.', turkishWord: 'reşit olmayan', turkishSentence: 'Çocuk yasal olarak henüz reşit değil.' },
    { id: 673, category: 'sıfatlar', germanWord: 'unnahbar', pronunciation: 'un-naa-baar', germanSentence: 'Er wirkt immer sehr kalt und unnahbar.', turkishWord: 'ulaşılmaz, soğuk duran', turkishSentence: 'Her zaman çok soğuk ve ulaşılmaz görünüyor.' },
    { id: 674, category: 'sıfatlar', germanWord: 'unproportional', pronunciation: 'un-pro-por-tsiyo-naal', germanSentence: 'Die Strafen sind unproportional hoch.', turkishWord: 'orantısız', turkishSentence: 'Cezalar orantısız derecede yüksektir.' },
    { id: 675, category: 'sıfatlar', germanWord: 'unrentabel', pronunciation: 'un-ren-taa-bıl', germanSentence: 'Das Geschäft wurde als unrentabel eingestuft.', turkishWord: 'kârsız, verimsiz', turkishSentence: 'İşletme kârsız(verimsiz) olarak sınıflandırıldı.' },
    { id: 676, category: 'sıfatlar', germanWord: 'unscheinbar', pronunciation: 'un-şayn-baar', germanSentence: 'Von außen wirkt das Haus sehr unscheinbar.', turkishWord: 'gösterişsiz, dikkati çekmeyen', turkishSentence: 'Ev dışarıdan çok gösterişsiz(sıradan) görünüyor.' },
    { id: 677, category: 'sıfatlar', germanWord: 'unübertroffen', pronunciation: 'un-ü-bır-tro-fın', germanSentence: 'Ihre Leistung bei den Spielen war unübertroffen.', turkishWord: 'aşılamaz, rakipsiz, emsalsiz', turkishSentence: 'Oyunlardaki performansı rakipsizdi (emsalsizdi).' },
    { id: 678, category: 'sıfatlar', germanWord: 'unverblümt', pronunciation: 'un-fer-blümt', germanSentence: 'Er sagte ihr unverblümt die Wahrheit.', turkishWord: 'açıkça, sakınmadan, pat diye', turkishSentence: 'Ona gerçeği (lafı dolandırmadan) açıkça söyledi.' },
    { id: 679, category: 'sıfatlar', germanWord: 'urtümlich', pronunciation: 'ur-tüm-lih', germanSentence: 'Wir wanderten durch eine urtümliche Landschaft.', turkishWord: 'ilkel, asıl, bozulmamış', turkishSentence: 'Bozulmamış (ilkel) bir manzarada yürüyüş yaptık.' },
    { id: 680, category: 'sıfatlar', germanWord: 'velourartig', pronunciation: 've-luur-ar-tik', germanSentence: 'Der Stoff fühlt sich velourartig an.', turkishWord: 'kadifemsi', turkishSentence: 'Kumaş kadifemsi bir his veriyor.' },

    // --- Bağlaçlar / Zarflar / İfadeler ---
    { id: 681, category: 'bağlaçlar', germanWord: 'gewissermaßen', pronunciation: 'ge-vi-sır-ma-sın', germanSentence: 'Er ist gewissermaßen der Boss hier.', turkishWord: 'bir bakıma, adeta', turkishSentence: 'O bir bakıma buranın patronudur.' },
    { id: 682, category: 'bağlaçlar', germanWord: 'hinweg', pronunciation: 'hin-vek', germanSentence: 'Sie half ihm über die schwere Zeit hinweg.', turkishWord: 'ötesine, boyu, üzerinden', turkishSentence: 'Zor zamanı atlatmasına (üzerinden geçmesine) yardım etti.' },
    { id: 683, category: 'bağlaçlar', germanWord: 'insbesondere', pronunciation: 'ins-be-zon-de-rı', germanSentence: 'Ich mag Obst, insbesondere Äpfel.', turkishWord: 'özellikle, bilhassa', turkishSentence: 'Meyve severim, özellikle elmaları.' },
    { id: 684, category: 'bağlaçlar', germanWord: 'mitunter', pronunciation: 'mit-un-tır', germanSentence: 'Mitunter kann er sehr anstrengend sein.', turkishWord: 'bazen, zaman zaman', turkishSentence: 'Bazen çok yorucu/bıktırıcı olabiliyor.' },
    { id: 685, category: 'bağlaçlar', germanWord: 'nichtsdestoweniger', pronunciation: 'nih-tsdes-to-ve-ni-gır', germanSentence: 'Er ist arm, nichtsdestoweniger ist er glücklich.', turkishWord: 'buna rağmen, yinede', turkishSentence: 'O fakir, yine de mutludur.' },
    { id: 686, category: 'bağlaçlar', germanWord: 'schlechthin', pronunciation: 'şleht-hin', germanSentence: 'Paris ist die Stadt der Liebe schlechthin.', turkishWord: 'sözün tam anlamıyla', turkishSentence: 'Paris sözün tam anlamıyla aşk şehridir.' },
    { id: 687, category: 'bağlaçlar', germanWord: 'seinerseits', pronunciation: 'zay-nır-zayts', germanSentence: 'Er seinerseits hat keine Einwände.', turkishWord: 'kendi payına, onun açısından', turkishSentence: 'Kendi açısından/Kendi adına onun itirazı yok.' },
    { id: 688, category: 'bağlaçlar', germanWord: 'ungemein', pronunciation: 'un-ge-mayn', germanSentence: 'Die Prüfung war ungemein schwierig.', turkishWord: 'son derece, fevkalade', turkishSentence: 'Sınav son derece zordu.' },
    { id: 689, category: 'bağlaçlar', germanWord: 'vollkommen', pronunciation: 'fol-ko-mın', germanSentence: 'Ich stimme dir vollkommen zu.', turkishWord: 'tamamen, kusursuzca', turkishSentence: 'Sana tamamen katılıyorum.' },
    { id: 690, category: 'bağlaçlar', germanWord: 'zusehends', pronunciation: 'tsu-zey-ınts', germanSentence: 'Die Lage verschlechtert sich zusehends.', turkishWord: 'gözle görülür biçimde', turkishSentence: 'Durum gözle görülür biçimde kötüleşiyor.' },

    // --- Ekstra İsimler (Zorluk seviyesi C1) ---
    { id: 691, category: 'isimler', germanWord: 'das Novum', pronunciation: 'das no-vum', germanSentence: 'Ein solches System war damals ein absolutes Novum.', turkishWord: 'yenilik, ilk kez olan şey', turkishSentence: 'Böyle bir sistem o zamanlar tamamen bir yenilikti.' },
    { id: 692, category: 'isimler', germanWord: 'das Paradoxon', pronunciation: 'das pa-ra-dok-son', germanSentence: 'Dies führt zu einem unauflösbaren Paradoxon.', turkishWord: 'kısır döngü, paradoks, çelişki', turkishSentence: 'Bu çözülemeyen bir paradoksa yol açar.' },
    { id: 693, category: 'isimler', germanWord: 'das Phänomen /-e', pronunciation: 'das feno-meen', germanSentence: 'Gewitter sind ein interessantes Naturphänomen.', turkishWord: 'olgu, fenomen', turkishSentence: 'Gök gürültülü fırtınalar ilginç bir doğa olgusudur.' },
    { id: 694, category: 'isimler', germanWord: 'das Plagiat /-e', pronunciation: 'das pla-gi-yaat', germanSentence: 'Der Vorwurf des Plagiats führte zu seinem Rücktritt.', turkishWord: 'intihal, eser hırsızlığı', turkishSentence: 'İntihal suçlaması onun istifasına yol açtı.' },
    { id: 695, category: 'isimler', germanWord: 'das Prämisse /-n', pronunciation: 'di pre-mi-sı', germanSentence: 'Wir gehen von der Prämisse aus, dass alle zustimmen.', turkishWord: 'öncül, varsayım', turkishSentence: 'Herkesin kabul ettiği varsayımından yola çıkıyoruz.' },
    { id: 696, category: 'isimler', germanWord: 'der Profit /-e', pronunciation: 'der pro-fiit', germanSentence: 'Aus Profitgier wurde die Umwelt zerstört.', turkishWord: 'kâr, kazanç', turkishSentence: 'Kâr hırsı nedeniyle çevre yok edildi.' },
    { id: 697, category: 'isimler', germanWord: 'das Protokoll /-e', pronunciation: 'das pro-to-kol', germanSentence: 'Das Protokoll der Sitzung wird später verschickt.', turkishWord: 'tutanak, protokol', turkishSentence: 'Toplantı tutanağı daha sonra gönderilecek.' },
    { id: 698, category: 'isimler', germanWord: 'das Quintessenz', pronunciation: 'di kvin-te-zents', germanSentence: 'Die Quintessenz der Geschichte ist einfach.', turkishWord: 'özet, asıl mesele, ana fikir', turkishSentence: 'Hikayenin ana fikri (özeti) basittir.' },
    { id: 699, category: 'isimler', germanWord: 'das Refugium', pronunciation: 'das re-fu-gi-yum', germanSentence: 'Der Garten war sein privates Refugium.', turkishWord: 'sığınak, inziva yeri', turkishSentence: 'Bahçe onun özel sığınağıydı.' },
    { id: 700, category: 'isimler', germanWord: 'das Relikt /-e', pronunciation: 'das re-likt', germanSentence: 'Dieses Gesetz ist ein Relikt aus dem Mittelalter.', turkishWord: 'kalıntı, bakiye', turkishSentence: 'Bu yasa Orta Çağ\'dan kalma bir kalıntıdır.' },

    // --- Ekstra Fiiller / Sıfatlar ---
    { id: 701, category: 'fiiller', germanWord: 'formulieren', pronunciation: 'for-mu-lii-rın', germanSentence: 'Er formulierte seine Bedenken sehr höflich.', turkishWord: 'ifade etmek, formüle etmek', turkishSentence: 'Çekincelerini çok kibarca ifade etti / dile getirdi.' },
    { id: 702, category: 'fiiller', germanWord: 'fungieren', pronunciation: 'fun-gii-rın', germanSentence: 'Er fungierte als Vermittler zwischen den Parteien.', turkishWord: 'işlev görmek, olarak görev yapmak', turkishSentence: 'Taraflar arasında arabulucu olarak görev yaptı.' },
    { id: 703, category: 'fiiller', germanWord: 'gedeihen', pronunciation: 'ge-day-ın', germanSentence: 'Die Pflanzen gedeihen im Schatten besser.', turkishWord: 'gelişmek, büyümek', turkishSentence: 'Bitkiler gölgede daha iyi gelişiyor(büyüyor).' },
    { id: 704, category: 'fiiller', germanWord: 'gipfeln', pronunciation: 'gip-fıln', germanSentence: 'Der Streit gipfelte in einer Schlägerei.', turkishWord: 'doruğa ulaşmak, ile sonuçlanmak', turkishSentence: 'Tartışma kavgaya dönüşerek doruğa ulaştı.' },
    { id: 705, category: 'fiiller', germanWord: 'haften', pronunciation: 'haf-tın', germanSentence: 'Eltern haften für ihre Kinder.', turkishWord: 'sorumlu olmak, yükümlü olmak', turkishSentence: 'Ebeveynler çocuklarından sorumludur.' },
    { id: 706, category: 'sıfatlar', germanWord: 'versiert', pronunciation: 'ver-ziirt', germanSentence: 'Er ist ein technisch versierter Experte.', turkishWord: 'deneyimli, ehil, usta', turkishSentence: 'O teknik açıdan yetkin/usta bir uzmandır.' },
    { id: 707, category: 'sıfatlar', germanWord: 'vital', pronunciation: 'vi-taal', germanSentence: 'Es ist von vitaler Bedeutung für das Land.', turkishWord: 'hayati, yaşamsal', turkishSentence: 'Ülke için hayati bir öneme sahiptir.' },
    { id: 708, category: 'sıfatlar', germanWord: 'winzig', pronunciation: 'vin-tsik', germanSentence: 'Der Fehler war nur ein winziges Detail.', turkishWord: 'ufacık, minik', turkishSentence: 'Hata sadece ufacık bir detaydı.' },
    { id: 709, category: 'sıfatlar', germanWord: 'wünschenswert', pronunciation: 'vün-şıns-veert', germanSentence: 'Eine schnelle Lösung wäre sehr wünschenswert.', turkishWord: 'arzu edilen, istenen', turkishSentence: 'Hızlı bir çözüm çok arzu edilir(istenen) bir durum olurdu.' },
    { id: 710, category: 'sıfatlar', germanWord: 'zeitgemäß', pronunciation: 'tsayt-ge-mees', germanSentence: 'Diese Ansichten sind nicht mehr zeitgemäß.', turkishWord: 'çağdaş, çağa uygun', turkishSentence: 'Bu görüşler artık çağa uygun (çağdaş) değildir.' }
];

export default data15;
