const data19 = [
    // --- Sürekli İlerleyiş (B2-C1 Kelimeleri) ---
    { id: 891, category: 'sıfatlar', germanWord: 'introvertiert', pronunciation: 'in-tro-ver-tiirt', germanSentence: 'Sie ist eher introvertiert und mag keine großen Partys.', turkishWord: 'içe dönük', turkishSentence: 'O daha çok içe dönüktür ve büyük partileri sevmez.' },
    { id: 892, category: 'sıfatlar', germanWord: 'infantil', pronunciation: 'in-fan-tiil', germanSentence: 'Hör auf mit diesem infantilen Verhalten!', turkishWord: 'çocuksu, çocukça', turkishSentence: 'Bu çocuksu davranışı bırak!' },
    { id: 893, category: 'sıfatlar', germanWord: 'informell', pronunciation: 'in-for-mel', germanSentence: 'Das Treffen hatte einen völlig informellen Charakter.', turkishWord: 'resmi olmayan, senli benli', turkishSentence: 'Toplantı tamamen resmi olmayan bir yapıya(karaktere) sahipti.' },
    { id: 894, category: 'sıfatlar', germanWord: 'inhärent', pronunciation: 'in-he-rent', germanSentence: 'Dieses Risiko ist dem System inhärent.', turkishWord: 'yapısında var olan, doğasında olan', turkishSentence: 'Bu risk sistemin doğasında (yapısında) var.' },
    { id: 895, category: 'sıfatlar', germanWord: 'inspektorisch', pronunciation: 'ins-pek-too-riş', germanSentence: 'Er hatte fast einen inspektorischen Blick.', turkishWord: 'denetleyici tarzda, teftiş eden', turkishSentence: 'Neredeyse denetleyici(teftiş eden) bir bakışı vardı.' },
    { id: 896, category: 'sıfatlar', germanWord: 'intellektuell', pronunciation: 'in-te-lek-tu-el', germanSentence: 'Das ist eine große intellektuelle Herausforderung.', turkishWord: 'entelektüel, zihinsel', turkishSentence: 'Bu büyük bir zihinsel/entelektüel meydan okumadır.' },
    { id: 897, category: 'sıfatlar', germanWord: 'kursorisch', pronunciation: 'kur-zoo-riş', germanSentence: 'Ich habe den Text nur kursorisch gelesen.', turkishWord: 'üstünkörü, hızlıca', turkishSentence: 'Metni sadece üstünkörü okudum.' },
    { id: 898, category: 'sıfatlar', germanWord: 'labial', pronunciation: 'la-bi-yaal', germanSentence: 'Der Laut wird labial gebildet.', turkishWord: 'dudakla ilgili (dilbilgisi)', turkishSentence: 'Bu ses dudak(sıl) olarak oluşturulur.' },
    { id: 899, category: 'sıfatlar', germanWord: 'lakonisch', pronunciation: 'la-koo-niş', germanSentence: 'Er antwortete nur mit einem lakonischen Nicken.', turkishWord: 'kısa ve öz, lafı uzatmayan', turkishSentence: 'Sadece kısa ve öz bir kafa sallamayla cevap verdi.' },
    { id: 900, category: 'sıfatlar', germanWord: 'latent', pronunciation: 'la-tent', germanSentence: 'Eine latente Gefahr ist immer am schlimmsten.', turkishWord: 'gizli, belirti göstermeyen (örtük)', turkishSentence: 'Gizli(örtük) bir tehlike her zaman en kötüsüdür.' },

    // --- İsimler ---
    { id: 901, category: 'isimler', germanWord: 'die Manie', pronunciation: 'ma-nii', germanSentence: 'Er hat eine wahre Manie fürs Kontrollieren entwickelt.', turkishWord: 'mani, aşırı düşkünlük, saplantı', turkishSentence: 'Kontrol etme konusunda gerçek bir saplantı geliştirdi.' },
    { id: 902, category: 'isimler', germanWord: 'das Mantra', pronunciation: 'man-tra', germanSentence: 'Das Team wiederholt dieses Motto wie ein Mantra.', turkishWord: 'kavramsal nakarat, mantra', turkishSentence: 'Takım bu sloganı bir mantra gibi tekrarlıyor.' },
    { id: 903, category: 'isimler', germanWord: 'die Maxime /-n', pronunciation: 'mak-sii-mı', germanSentence: 'Das ist meine oberste Maxime im Geschäftsleben.', turkishWord: 'ilke, temel kural', turkishSentence: 'Bu iş hayatındaki en önemli ilkemdir(kurallarımdandır).' },
    { id: 904, category: 'isimler', germanWord: 'die Methodik', pronunciation: 'me-too-dik', germanSentence: 'Die Methodik der Studie ist umstritten.', turkishWord: 'yöntembilim', turkishSentence: 'Çalışmanın yöntemi/yöntembilimi tartışmalıdır.' },
    { id: 905, category: 'isimler', germanWord: 'das Monopol /-e', pronunciation: 'mo-no-pool', germanSentence: 'Das staatliche Monopol auf diesen Sektor wurde gebrochen.', turkishWord: 'tekel', turkishSentence: 'Bu sektör üzerindeki devlet tekeli kırıldı.' },
    { id: 906, category: 'isimler', germanWord: 'das Mysterium /-ien', pronunciation: 'müs-tee-riyum', germanSentence: 'Das Gehirn bleibt ein großes Mysterium.', turkishWord: 'gizem, sır', turkishSentence: 'Beyin hala büyük bir gizem(sır) olmaya devam ediyor.' },
    { id: 907, category: 'isimler', germanWord: 'der Mythos (die Mythen)', pronunciation: 'mü-tos', germanSentence: 'Es gibt viele Mythen über alte Zivilisationen.', turkishWord: 'mit, efsane', turkishSentence: 'Eski medeniyetler hakkında birçok efsane(mit) vardır.' },
    { id: 908, category: 'isimler', germanWord: 'das Vakuum', pronunciation: 'va-ku-um', germanSentence: 'Der Rückzug des Militärs hinterließ ein Machtvakuum.', turkishWord: 'boşluk (güç/fizik boşluğu)', turkishSentence: 'Ordunun geri çekilmesi bir güç boşluğu bıraktı.' },
    { id: 909, category: 'isimler', germanWord: 'die Nostalgie', pronunciation: 'nos-tal-gii', germanSentence: 'Sie verspürte eine Welle der Nostalgie.', turkishWord: 'nostalji, geçmişe özlem', turkishSentence: 'Bir nostalji(geçmişe özlem) dalgası hissetti.' },
    { id: 910, category: 'isimler', germanWord: 'das Novum', pronunciation: 'no-vum', germanSentence: 'Das war ein völliges Novum in der Geschichte des Landes.', turkishWord: 'yenilik', turkishSentence: 'Bu ülke tarihinde tamamen bir yenilikti.' },

    // --- Fiiller ---
    { id: 911, category: 'fiiller', germanWord: 'konfiszieren', pronunciation: 'kon-fis-tsii-rın', germanSentence: 'Die Polizei hat das Beweismaterial konfisziert.', turkishWord: 'müsadere etmek, el koymak', turkishSentence: 'Polis delillere el koydu.' },
    { id: 912, category: 'fiiller', germanWord: 'kongruieren', pronunciation: 'kon-gru-ii-rın', germanSentence: 'Die Zeugenaussagen kongruieren in allen Punkten.', turkishWord: 'uyuşmak, birbirini tutmak', turkishSentence: 'Tanık ifadeleri her noktada uyuşuyor.' },
    { id: 913, category: 'fiiller', germanWord: 'kontaminieren', pronunciation: 'kon-ta-mi-nii-rın', germanSentence: 'Der Boden wurde durch Chemikalien kontaminiert.', turkishWord: 'kirletmek (radyasyon/kimyasal)', turkishSentence: 'Toprak kimyasallar aracılığıyla kirletildi.' },
    { id: 914, category: 'fiiller', germanWord: 'kodifizieren', pronunciation: 'ko-di-fi-tsii-rın', germanSentence: 'Das Gewohnheitsrecht wurde schließlich kodifiziert.', turkishWord: 'yazılı yasa haline getirmek', turkishSentence: 'Geleneksel hukuk en sonunda yazılı(kurallı) hale getirildi.' },
    { id: 915, category: 'fiiller', germanWord: 'konsolidieren', pronunciation: 'kon-zo-li-dii-rın', germanSentence: 'Die Firma muss erst einmal ihre Finanzen konsolidieren.', turkishWord: 'sağlamlaştırmak', turkishSentence: 'Firma öncelikle finansını (mali durumunu) sağlamlaştırmalıdır.' },
    { id: 916, category: 'fiiller', germanWord: 'kreieren', pronunciation: 'kre-ii-rın', germanSentence: 'Der Chefkoch hat ein neues Menü kreiert.', turkishWord: 'yaratmak, oluşturmak (tasarım/sanat)', turkishSentence: 'Aşçıbaşı yeni bir menü yarattı.' },
    { id: 917, category: 'fiiller', germanWord: 'konzipieren', pronunciation: 'kon-tsi-pii-rın', germanSentence: 'Das Projekt wurde von einer Agentur konzipiert.', turkishWord: 'tasarlamak, taslağını oluşturmak', turkishSentence: 'Projenin taslağı bir ajans tarafından tasarlandı/oluşturuldu.' },
    { id: 918, category: 'fiiller', germanWord: 'kultivieren', pronunciation: 'kul-ti-vii-rın', germanSentence: 'Er hat diese Leidenschaft seit Jahren kultiviert.', turkishWord: 'yetiştirmek, özenle geliştirmek', turkishSentence: 'Bu tutkuyu yıllardır özenle geliştirdi/yetiştirdi.' },
    { id: 919, category: 'fiiller', germanWord: 'liquidieren', pronunciation: 'lik-vi-dii-rın', germanSentence: 'Die Firma musste liquidiert werden.', turkishWord: 'tasfiye etmek (şirketi vs.)', turkishSentence: 'Şirket tasfiye edilmek (kapatılmak) zorunda kaldı.' },
    { id: 920, category: 'fiiller', germanWord: 'manipulieren', pronunciation: 'ma-ni-pu-lii-rın', germanSentence: 'Lass dich nicht von ihm manipulieren.', turkishWord: 'manipüle etmek', turkishSentence: 'Onun seni manipüle etmesine izin verme.' },

    // --- Sıfatlar/Zarflar ---
    { id: 921, category: 'sıfatlar', germanWord: 'legitim', pronunciation: 'le-gi-tiim', germanSentence: 'Ihre Forderungen sind durchaus legitim.', turkishWord: 'yasal, haklı, meşru', turkishSentence: 'Talepleriniz kesinlikle haklı (meşru).' },
    { id: 922, category: 'sıfatlar', germanWord: 'lethargisch', pronunciation: 'le-tar-giş', germanSentence: 'Sie war tagein, tagaus nur müde und lethargisch.', turkishWord: 'uyuşuk, halsiz', turkishSentence: 'Günler boyunca sadece yorgun ve halsiz/uyuşuktu.' },
    { id: 923, category: 'sıfatlar', germanWord: 'lukullisch', pronunciation: 'lu-ku-liş', germanSentence: 'Wir genossen ein lukullisches Mahl.', turkishWord: 'zengin ve bol yemekli (şölen gibi)', turkishSentence: 'Zengin (şölen gibi) bir yemeğin tadını çıkardık.' },
    { id: 924, category: 'sıfatlar', germanWord: 'makaber', pronunciation: 'ma-kaa-bır', germanSentence: 'Er erzählte einen sehr makabren Witz.', turkishWord: 'ürkütücü, kan donduran, korkunç (mizah)', turkishSentence: 'Oldukça ürkütücü(ölümle ilgili, kara mizah) bir fıkra anlattı.' },
    { id: 925, category: 'sıfatlar', germanWord: 'marginal', pronunciation: 'mar-gi-naal', germanSentence: 'Der Unterschied ist wirklich nur marginal.', turkishWord: 'önemsiz ölçüde küçük, marjinal', turkishSentence: 'Fark gerçekten sadece küçük/önemsiz boyutta.' },
    { id: 926, category: 'sıfatlar', germanWord: 'martialisch', pronunciation: 'mar-tsi-yaa-liş', germanSentence: 'Sein Auftreten war sehr martialisch.', turkishWord: 'savaşçı gibi, askeri (görünümlü)', turkishSentence: 'Onun görünümü oldukça savaşçı gibiydi(sertti).' },
    { id: 927, category: 'sıfatlar', germanWord: 'melancholisch', pronunciation: 'me-lan-koo-liş', germanSentence: 'Bist du oft melancholisch?', turkishWord: 'melankolik, hüzünlü', turkishSentence: 'Sık sık hüzünlü (melankolik) müsün?' },
    { id: 928, category: 'sıfatlar', germanWord: 'militant', pronunciation: 'mi-li-tant', germanSentence: 'Eine militante Gruppe formierte sich.', turkishWord: 'saldırgan eğilimli, militan', turkishSentence: 'Militan (saldırgan) bir grup oluştu.' },
    { id: 929, category: 'sıfatlar', germanWord: 'monumental', pronunciation: 'mo-nu-men-taal', germanSentence: 'Das ist ein monumentales Kunstwerk.', turkishWord: 'anıtsal, muazzam', turkishSentence: 'Bu anıtsal (muazzam büyüklükte) bir sanat eseridir.' },
    { id: 930, category: 'sıfatlar', germanWord: 'morbid', pronunciation: 'mor-biid', germanSentence: 'Er hat eine morbide Faszination für Friedhöfe.', turkishWord: 'marazi, hastalık derecesinde, hastalıklı', turkishSentence: 'Mezarlıklara karşı hastalık derecesinde bir ilgisi/büyüsü var.' },

    // --- Karışık (Bağlaçlar vb.) ---
    { id: 931, category: 'bağlaçlar', germanWord: 'ebenso ... wie', pronunciation: 'e-bın-zo ... vi', germanSentence: 'Er ist ebenso fleißig wie talentiert.', turkishWord: 'kadar ... (ayrıca)', turkishSentence: 'Yetenekli olduğu kadar da çalışkan.' },
    { id: 932, category: 'bağlaçlar', germanWord: 'weder ... noch', pronunciation: 've-dır ... noh', germanSentence: 'Ich habe weder Zeit noch Geld.', turkishWord: 'ne ... ne de', turkishSentence: 'Ne zamanım ne de param var.' },
    { id: 933, category: 'bağlaçlar', germanWord: 'zwar ... aber', pronunciation: 'tsvaar ... a-bır', germanSentence: 'Das Buch ist zwar kurz, aber schwer verständlich.', turkishWord: 'gerçi ... ama', turkishSentence: 'Kitap gerçi kısa, ama anlaşılması zordur.' },
    { id: 934, category: 'bağlaçlar', germanWord: 'entweder ... oder', pronunciation: 'ent-ve-dır ... o-dır', germanSentence: 'Entweder wir gehen jetzt, oder wir bleiben hier.', turkishWord: 'ya ... ya da', turkishSentence: 'Ya şimdi gideriz, ya da burada kalırız.' },
    { id: 935, category: 'bağlaçlar', germanWord: 'teils ... teils', pronunciation: 'tayls ... tayls', germanSentence: 'Die Antwort war teils richtig, teils falsch.', turkishWord: 'kısmen ... kısmen', turkishSentence: 'Cevap kısmen doğru, kısmen yanlıştı.' },
    { id: 936, category: 'isimler', germanWord: 'die Nuance /-n', pronunciation: 'nu-an-sı', germanSentence: 'Es gibt viele feine Nuancen in der deutschen Sprache.', turkishWord: 'nüans, ince ayrıntı', turkishSentence: 'Alman dilinde birçok ince ayrıntı(nüans) vardır.' },
    { id: 937, category: 'isimler', germanWord: 'die Prärogative', pronunciation: 'pre-ro-ga-ti-vı', germanSentence: 'Dieses Recht ist die Prärogative des Chefs.', turkishWord: 'imtiyaz, ayrıcalık hak', turkishSentence: 'Bu hak patronun ayrıcalığıdır/imtiyazıdır.' },
    { id: 938, category: 'isimler', germanWord: 'die Rebellion /-en', pronunciation: 're-be-li-yon', germanSentence: 'Die junge Generation neigt oft zur Rebellion.', turkishWord: 'isyan', turkishSentence: 'Genç nesil genellikle isyana meyleder.' },
    { id: 939, category: 'isimler', germanWord: 'die Ressonanz', pronunciation: 're-zo-nants', germanSentence: 'Das Projekt fand bei den Mitarbeitern große Resonanz.', turkishWord: 'yankı, tepki', turkishSentence: 'Proje çalışanlar arasında büyük yankı (olumlu tepki) buldu.' },
    { id: 940, category: 'isimler', germanWord: 'die Rhetorik', pronunciation: 're-too-rik', germanSentence: 'Ihre politische Rhetorik ist extrem scharf.', turkishWord: 'hitabet', turkishSentence: 'Onun politik hitabeti(söz sanatı) aşırı derecede keskindir.' },

    // --- Ekstra Kelimeler ---
    { id: 941, category: 'fiiller', germanWord: 'minimalisieren', pronunciation: 'mi-ni-ma-li-zii-rın', germanSentence: 'Wir müssen versuchen, die Risiken zu minimalisieren.', turkishWord: 'en aza indirgemek', turkishSentence: 'Riskleri en aza indirgemeye çalışmalıyız.' },
    { id: 942, category: 'fiiller', germanWord: 'multiplizieren', pronunciation: 'mul-ti-pli-tsii-rın', germanSentence: 'Die Probleme scheinen sich zu multiplizieren.', turkishWord: 'çoğaltmak, katlamak', turkishSentence: 'Sorunlar katlanarak çoğalıyor gibi görünüyor.' },
    { id: 943, category: 'fiiller', germanWord: 'narren', pronunciation: 'na-rın', germanSentence: 'Ich lasse mich nicht länger von dir narren!', turkishWord: 'kandırmak, aptal yerine koymak', turkishSentence: 'Artık senin tarafından aptal yerine konulmayacağım(kandırılmayacağım)!' },
    { id: 944, category: 'fiiller', germanWord: 'obsolet werden', pronunciation: 'o-pso-leet ver-dın', germanSentence: 'Schreibmaschinen sind inzwischen völlig obsolet geworden.', turkishWord: 'modası geçmek, kullanımdan kalkmak', turkishSentence: 'Daktilolar o zamandan beri tamamen modası geçmiş hale geldi(kullanımdan kalktı).' },
    { id: 945, category: 'fiiller', germanWord: 'optieren', pronunciation: 'op-tii-rın', germanSentence: 'Wir optieren für die friedliche Lösung.', turkishWord: 'seçmek, karar kılmak', turkishSentence: 'Biz barışçıl çözümden yana karar kıldık (seçtik).' },
    { id: 946, category: 'sıfatlar', germanWord: 'mythisch', pronunciation: 'müü-tiş', germanSentence: 'Das ist eine mythische Figur.', turkishWord: 'efsanevi, mitsel', turkishSentence: 'Bu efsanevi(mitsel) bir figürdür.' },
    { id: 947, category: 'sıfatlar', germanWord: 'naiv', pronunciation: 'na-iif', germanSentence: 'Du bist manchmal wirklich zu naiv.', turkishWord: 'saf, naif, tecrübesiz', turkishSentence: 'Bazen gerçekten fazla safsın.' },
    { id: 948, category: 'sıfatlar', germanWord: 'objektiv', pronunciation: 'op-yek-tiif', germanSentence: 'Ein Richter muss stets objektiv bleiben.', turkishWord: 'nesnel, tarafsız', turkishSentence: 'Bir hakim her zaman nesnel kalmalıdır.' },
    { id: 949, category: 'sıfatlar', germanWord: 'obskur', pronunciation: 'ops-kuur', germanSentence: 'Das ist eine völlig obskure Regelung.', turkishWord: 'anlaşılmaz, karanlık, şüpheli', turkishSentence: 'Bu tamamen anlaşılmaz (karanlık) bir düzenlemedir.' },
    { id: 950, category: 'sıfatlar', germanWord: 'ordinär', pronunciation: 'or-di-neer', germanSentence: 'Seine Ausdrucksweise ist leider ziemlich ordinär.', turkishWord: 'bayağı, sıradan, avam', turkishSentence: 'Onun ifade tarzı maalesef oldukça bayağı(avam).' }
];

export default data19;
