const data11 = [
    // --- İsimler ---
    { id: 441, category: 'isimler', germanWord: 'der Zusammenstoß /"e', pronunciation: 'der tsu-za-mın-ştoos', germanSentence: 'Beim Zusammenstoß zweier Züge gab es Verletzte.', turkishWord: 'çarpışma', turkishSentence: 'İki trenin çarpışmasında yaralananlar oldu.' },
    { id: 442, category: 'isimler', germanWord: 'die Zuordnung /-en', pronunciation: 'di tsu-ort-nung', germanSentence: 'Die genaue Zuordnung der Aufgaben ist wichtig.', turkishWord: 'tahsis, sınıflandırma, eşleştirme', turkishSentence: 'Görevlerin kesin tahsisi(eşleştirmesi) önemlidir.' },
    { id: 443, category: 'isimler', germanWord: 'der Vorsatz /"e', pronunciation: 'der for-zats', germanSentence: 'Mein guter Vorsatz fürs neue Jahr ist Sport.', turkishWord: 'niyet, maksat', turkishSentence: 'Yeni yıl için iyi niyetim (kararım) spor yapmak.' },
    { id: 444, category: 'isimler', germanWord: 'die Präsenz', pronunciation: 'di pre-zents', germanSentence: 'Seine physische Präsenz im Raum war spürbar.', turkishWord: 'bulunma, mevcudiyet', turkishSentence: 'Odadaki fiziksel mevcudiyeti hissediliyordu.' },
    { id: 445, category: 'isimler', germanWord: 'die Prävention /-en', pronunciation: 'di pre-ven-tsion', germanSentence: 'Kriminalprävention ist eine wichtige Aufgabe.', turkishWord: 'önleme, koruma', turkishSentence: 'Suç önleme önemli bir görevdir.' },
    { id: 446, category: 'isimler', germanWord: 'der Rückhalt', pronunciation: 'der rük-halt', germanSentence: 'Er hat den vollen Rückhalt seiner Familie.', turkishWord: 'destek, arka çıkma', turkishSentence: 'Ailesinin tam desteğine sahip.' },
    { id: 447, category: 'isimler', germanWord: 'die Schonung', pronunciation: 'di şoo-nung', germanSentence: 'Dieser Eingriff erfordert eine längere Schonung.', turkishWord: 'dinlenme, sakınma', turkishSentence: 'Bu müdahale daha uzun bir dinlenme gerektirir.' },
    { id: 448, category: 'isimler', germanWord: 'das Spekulation /-en', pronunciation: 'das şpe-ku-la-tsion', germanSentence: 'Das sind alles nur haltlose Spekulationen.', turkishWord: 'spekülasyon, söylenti', turkishSentence: 'Bunların hepsi sadece asılsız spekülasyonlar.' },
    { id: 449, category: 'isimler', germanWord: 'der Stichtag /-e', pronunciation: 'der ştih-taak', germanSentence: 'Der 31. März ist der Stichtag für die Abgabe.', turkishWord: 'son teslim tarihi', turkishSentence: '31 Mart teslimat için son tarihtir.' },
    { id: 450, category: 'isimler', germanWord: 'das Syndrom /-e', pronunciation: 'das zün-droom', germanSentence: 'Das Burnout-Syndrom tritt oft bei Managern auf.', turkishWord: 'sendrom', turkishSentence: 'Tükenmişlik sendromu yöneticilerde sık görülür.' },

    // --- Fiiller ---
    { id: 451, category: 'fiiller', germanWord: 'abbringen (von)', pronunciation: 'ap-brin-gın', germanSentence: 'Sie ließ sich nicht von ihrem Plan abbringen.', turkishWord: 'vazgeçirmek', turkishSentence: 'Planından vazgeçirilemedi (kendini vazgeçirmedi).' },
    { id: 452, category: 'fiiller', germanWord: 'aufschlüsseln', pronunciation: 'auf-şlü-sıln', germanSentence: 'Können Sie diese Kosten bitte genau aufschlüsseln?', turkishWord: 'ayrıntılarına ayırmak, kalem kalem ayırmak', turkishSentence: 'Lütfen bu maliyetleri tam olarak ayırabilir misiniz?' },
    { id: 453, category: 'fiiller', germanWord: 'beauftragen', pronunciation: 'be-auf-tra-gın', germanSentence: 'Wir haben eine Architekturfirma damit beauftragt.', turkishWord: 'görevlendirmek', turkishSentence: 'Bunun için bir mimarlık şirketini görevlendirdik.' },
    { id: 454, category: 'fiiller', germanWord: 'beschwichtigen', pronunciation: 'be-şvih-ti-gın', germanSentence: 'Er versuchte, die wütende Menge zu beschwichtigen.', turkishWord: 'yatıştırmak, sakinleştirmek', turkishSentence: 'Öfkeli kalabalığı yatıştırmaya çalıştı.' },
    { id: 455, category: 'fiiller', germanWord: 'bewilligen', pronunciation: 'be-vi-li-gın', germanSentence: 'Der Antrag auf Fördermittel wurde bewilligt.', turkishWord: 'onaylamak, izin/ödenek vermek', turkishSentence: 'Teşvik fonu başvurusu onaylandı.' },
    { id: 456, category: 'fiiller', germanWord: 'delegieren', pronunciation: 'de-le-gii-rın', germanSentence: 'Ein guter Chef kann Aufgaben gut delegieren.', turkishWord: 'devretmek', turkishSentence: 'İyi bir patron görevleri iyi devredebilir.' },
    { id: 457, category: 'fiiller', germanWord: 'empfinden', pronunciation: 'emp-fin-dın', germanSentence: 'Ich empfinde große Dankbarkeit für deine Hilfe.', turkishWord: 'hissetmek, duymak (duygu)', turkishSentence: 'Yardımın için büyük bir minnettarlık hissediyorum.' },
    { id: 458, category: 'fiiller', germanWord: 'entkräften', pronunciation: 'ent-kref-tın', germanSentence: 'Die Argumente konnten von uns entkräftet werden.', turkishWord: 'çürütmek, etkisini azaltmak', turkishSentence: 'Argümanlar bizim tarafımızdan çürütülebildi.' },
    { id: 459, category: 'fiiller', germanWord: 'entrichten', pronunciation: 'ent-rih-tın', germanSentence: 'Die Steuer ist jährlich zu entrichten.', turkishWord: 'ödemek', turkishSentence: 'Vergi yıllık olarak ödenmelidir.' },
    { id: 460, category: 'fiiller', germanWord: 'erschließen', pronunciation: 'er-şlii-sın', germanSentence: 'Wir müssen neue Märkte auf dem Kontinent erschließen.', turkishWord: 'açmak, yararlanılır hale getirmek, keşfetmek', turkishSentence: 'Kıtada yeni pazarlar açmalıyız.' },

    // --- Sıfatlar ---
    { id: 461, category: 'sıfatlar', germanWord: 'abfällig', pronunciation: 'ap-fe-lik', germanSentence: 'Mach bitte keine abfälligen Bemerkungen.', turkishWord: 'küçümseyici, aşağılayıcı', turkishSentence: 'Lütfen küçümseyici yorumlar(açıklamalar) yapma.' },
    { id: 462, category: 'sıfatlar', germanWord: 'aufdringlich', pronunciation: 'auf-dring-lih', germanSentence: 'Der Verkäufer war mir viel zu aufdringlich.', turkishWord: 'sırnaşık, yüzsüz, zorla kendini kabul ettiren', turkishSentence: 'Satıcı bana çok sırnaşık(yüzsüz) geldi.' },
    { id: 463, category: 'sıfatlar', germanWord: 'barmherzig', pronunciation: 'barm-her-tsik', germanSentence: 'Es war eine wahrhaft barmherzige Tat.', turkishWord: 'merhametli', turkishSentence: 'Bu gerçekten merhametli bir eylemdi.' },
    { id: 464, category: 'sıfatlar', germanWord: 'beharrlich', pronunciation: 'be-har-lih', germanSentence: 'Er verfolgt beharrlich sein großes Ziel.', turkishWord: 'ısrarcı, sebatkar', turkishSentence: 'Büyük hedefini ısrarla takip ediyor.' },
    { id: 465, category: 'sıfatlar', germanWord: 'brüsk', pronunciation: 'brüsk', germanSentence: 'Ihre brüske Antwort hat ihn ziemlich verletzt.', turkishWord: 'ters, ani ve kaba', turkishSentence: 'Onun ters (kaba) cevabı onu oldukça incitti.' },
    { id: 466, category: 'sıfatlar', germanWord: 'diffizil', pronunciation: 'di-fi-tsil', germanSentence: 'Die Sache ist äußerst diffizil und heikel.', turkishWord: 'zor, ince, çetrefilli', turkishSentence: 'Durum son derece çetrefilli ve hassas.' },
    { id: 467, category: 'sıfatlar', germanWord: 'eloquent', pronunciation: 'e-lo-kvent', germanSentence: 'Er ist ein charmanter und eloquenter Redner.', turkishWord: 'güzel/etkili konuşan, sözü geçen', turkishSentence: 'O çekici ve etkili konuşan bir hatiptir.' },
    { id: 468, category: 'sıfatlar', germanWord: 'feindselig', pronunciation: 'faynt-zey-lik', germanSentence: 'Die Stimmung im Raum war spürbar feindselig.', turkishWord: 'düşmanca', turkishSentence: 'Odadaki atmosfer gözle görülür şekilde düşmancaydı.' },
    { id: 469, category: 'sıfatlar', germanWord: 'grob', pronunciation: 'groop', germanSentence: 'Das ist eine sehr grobe Fehleinschätzung.', turkishWord: 'kaba, çok büyük (hata vb.)', turkishSentence: 'Bu çok büyük (kaba) bir yanlış değerlendirmedir.' },
    { id: 470, category: 'sıfatlar', germanWord: 'heterogen', pronunciation: 'he-te-ro-geen', germanSentence: 'Diese Schulklasse ist sprachlich extrem heterogen.', turkishWord: 'heterojen, türdeş olmayan', turkishSentence: 'Bu sınıf dilsel olarak aşırı heterojendir.' },

    // --- Bağlaçlar / Zarflar ---
    { id: 471, category: 'bağlaçlar', germanWord: 'annähernd', pronunciation: 'an-nee-ırnt', germanSentence: 'Wir haben annähernd die gleichen Ansichten.', turkishWord: 'yaklaşık olarak, hemen hemen', turkishSentence: 'Hemen hemen aynı görüşlere sahibiz.' },
    { id: 472, category: 'bağlaçlar', germanWord: 'augenscheinlich', pronunciation: 'au-gın-şayn-lih', germanSentence: 'Augenscheinlich gab es ein tiefes Missverständnis.', turkishWord: 'görünüşe göre, aşikar (olarak)', turkishSentence: 'Görünüşe göre derin bir yanlış anlaşılma oldu.' },
    { id: 473, category: 'bağlaçlar', germanWord: 'beizeiten', pronunciation: 'bay-tsay-tın', germanSentence: 'Wir müssen beizeiten los, um pünktlich ankommen.', turkishWord: 'erkenden, vakitlice', turkishSentence: 'Zamanında varmak için erkenden yola çıkmalıyız.' },
    { id: 474, category: 'bağlaçlar', germanWord: 'derart', pronunciation: 'dee-art', germanSentence: 'Er war derart wütend, dass er sofort kündigte.', turkishWord: 'öylesine, o derece', turkishSentence: 'O derece öfkeliydi ki hemen istifa etti.' },
    { id: 475, category: 'bağlaçlar', germanWord: 'eher', pronunciation: 'ey-ır', germanSentence: 'Ich würde eher sagen, das ist riskant.', turkishWord: 'daha ziyade, daha çok', turkishSentence: 'Daha ziyade bunun riskli olduğunu söyleyebilirim.' },
    { id: 476, category: 'bağlaçlar', germanWord: 'fortan', pronunciation: 'fort-an', germanSentence: 'Fortan lebten sie alle glücklich in Frieden.', turkishWord: 'bundan (şu andan) itibaren', turkishSentence: 'Şu andan itibaren hepsi barış içinde mutlu yaşadılar.' },
    { id: 477, category: 'bağlaçlar', germanWord: 'indessen', pronunciation: 'in-de-sın', germanSentence: 'Sie arbeitete hart, indessen er nur ausschlief.', turkishWord: 'bununla birlikte, bu sırada', turkishSentence: 'O sıkı çalıştı, bu sırada o (erkek) sadece uyudu.' },
    { id: 478, category: 'bağlaçlar', germanWord: 'mithin', pronunciation: 'mit-hin', germanSentence: 'Er verlor; mithin ist das Spiel endgültig aus.', turkishWord: 'demek ki, şu halde, bu nedenle', turkishSentence: 'Kaybetti; bu nedenle oyun tamamen bitti.' },
    { id: 479, category: 'bağlaçlar', germanWord: 'seitdem', pronunciation: 'zayt-deem', germanSentence: 'Er hatte den Unfall, seitdem fährt er nicht mehr.', turkishWord: '-den beri, o zamandan beri', turkishSentence: 'Kaza geçirdi, o zamandan beri araç kullanmıyor.' },
    { id: 480, category: 'bağlaçlar', germanWord: 'überdies', pronunciation: 'ü-bır-diis', germanSentence: 'Sie war zu spät und überdies sehr unhöflich.', turkishWord: 'üstelik, bundan başka', turkishSentence: 'Geç kalmıştı ve üstelik çok kabaydı.' }
];

export default data11;
