const data9 = [
    // --- İsimler ---
    { id: 366, category: 'isimler', germanWord: 'der Rückgang', pronunciation: 'der rük-gank', germanSentence: 'Es gibt einen starken Rückgang der Geburtenrate.', turkishWord: 'düşüş, gerileme', turkishSentence: 'Doğum oranında güçlü bir gerileme/düşüş var.' },
    { id: 367, category: 'isimler', germanWord: 'die Sehnsucht /"e', pronunciation: 'di zeyn-zuht', germanSentence: 'Ihre Sehnsucht nach Freiheit war groß.', turkishWord: 'özlem, hasret', turkishSentence: 'Özgürlüğe olan hasreti/özlemi büyüktü.' },
    { id: 368, category: 'isimler', germanWord: 'das Symptom /-e', pronunciation: 'das zümp-toom', germanSentence: 'Welche Symptome haben Sie?', turkishWord: 'belirti, semptom', turkishSentence: 'Ne gibi belirtileriniz(semptomlarınız) var?' },
    { id: 369, category: 'isimler', germanWord: 'der Triumph /-e', pronunciation: 'der tri-yumf', germanSentence: 'Der Sieg fühlte sich wie ein großer Triumph an.', turkishWord: 'zafer, başarı', turkishSentence: 'Bu galibiyet büyük bir zafer gibi hissettirdi.' },
    { id: 370, category: 'isimler', germanWord: 'der Übergang /"e', pronunciation: 'der ü-bır-gank', germanSentence: 'Der Übergang zur Demokratie dauerte Jahre.', turkishWord: 'geçiş (süreci)', turkishSentence: 'Demokrasiye geçiş yıllar sürdü.' },
    { id: 371, category: 'isimler', germanWord: 'die Übereinstimmung /-en', pronunciation: 'di ü-bır-ayn-şti-mung', germanSentence: 'Es gibt eine hohe Übereinstimmung der Daten.', turkishWord: 'uyuşma, mutabakat, uygunluk', turkishSentence: 'Veriler arasında yüksek bir uygunluk(uyuşma) var.' },
    { id: 372, category: 'isimler', germanWord: 'das Unbehagen', pronunciation: 'das un-be-ha-gın', germanSentence: 'Ein leichtes Unbehagen machte sich breit.', turkishWord: 'huzursuzluk, rahatsızlık', turkishSentence: 'Hafif bir huzursuzluk yayıldı.' },
    { id: 373, category: 'isimler', germanWord: 'die Ursache /-n', pronunciation: 'di ur-za-hı', germanSentence: 'Die Ursache des Feuers ist noch unklar.', turkishWord: 'neden, sebep', turkishSentence: 'Yangının nedeni henüz belirsiz.' },
    { id: 374, category: 'isimler', germanWord: 'die Variante /-n', pronunciation: 'di va-ri-yan-tı', germanSentence: 'Wir müssen eine andere Variante ausprobieren.', turkishWord: 'seçenek, varyant', turkishSentence: 'Başka bir seçenek(varyant) denemeliyiz.' },
    { id: 375, category: 'isimler', germanWord: 'der Vorbehalt /-e', pronunciation: 'der for-be-halt', germanSentence: 'Ich stimme unter Vorbehalt zu.', turkishWord: 'çekince, şart', turkishSentence: 'Çekincelerle (bazı şartlarla) kabul ediyorum.' },

    // --- Fiiller ---
    { id: 376, category: 'fiiller', germanWord: 'recherchieren', pronunciation: 're-şer-şii-rın', germanSentence: 'Er musste stundenlang für den Artikel recherchieren.', turkishWord: 'araştırmak, bilgi toplamak', turkishSentence: 'Makale için saatlerce araştırma yapması gerekti.' },
    { id: 377, category: 'fiiller', germanWord: 'reflektieren', pronunciation: 're-flek-tii-rın', germanSentence: 'Man sollte sein eigenes Verhalten öfter reflektieren.', turkishWord: 'yansıtmak, üzerinde düşünmek', turkishSentence: 'İnsan kendi davranışları üzerinde daha sık düşünmelidir.' },
    { id: 378, category: 'fiiller', germanWord: 'repräsentieren', pronunciation: 're-pre-zen-tii-rın', germanSentence: 'Er wird unser Land im Ausland repräsentieren.', turkishWord: 'temsil etmek', turkishSentence: 'O, ülkemizi yurtdışında temsil edecek.' },
    { id: 379, category: 'fiiller', germanWord: 'stornieren', pronunciation: 'ştoor-nii-rın', germanSentence: 'Ich muss meinen Flug leider stornieren.', turkishWord: 'iptal etmek, vazgeçmek', turkishSentence: 'Maalesef uçağımı iptal etmek zorundayım.' },
    { id: 380, category: 'fiiller', germanWord: 'strapazieren', pronunciation: 'ştra-pa-tsii-rın', germanSentence: 'Diese Arbeit strapaziert meine Nerven sehr.', turkishWord: 'yıpratmak, yormak, aşırı yüklenmek', turkishSentence: 'Bu iş sinirlerimi çok yıpratıyor.' },
    { id: 381, category: 'fiiller', germanWord: 'tendieren', pronunciation: 'ten-dii-rın', germanSentence: 'Ich tendiere eher zu der ersten Lösung.', turkishWord: 'eğilimi olmak, meyl etmek', turkishSentence: 'Daha çok birinci çözüme eğilimliyim (meylediyorum).' },
    { id: 382, category: 'fiiller', germanWord: 'tolerieren', pronunciation: 'to-le-rii-rın', germanSentence: 'Solches Verhalten können wir nicht tolerieren.', turkishWord: 'hoş görmek, göz yummak, tolerans göstermek', turkishSentence: 'Böyle bir davranışı hoş göremeyiz (tolere edemeyiz).' },
    { id: 383, category: 'fiiller', germanWord: 'transformieren', pronunciation: 'trans-for-mii-rın', germanSentence: 'Das System muss komplett transformiert werden.', turkishWord: 'dönüştürmek', turkishSentence: 'Sistem tamamen dönüştürülmelidir.' },
    { id: 384, category: 'fiiller', germanWord: 'übertrumpfen', pronunciation: 'ü-bır-trum-fın', germanSentence: 'Sie wollte ihren Kollegen immer übertrumpfen.', turkishWord: 'bastırmak, üstün gelmek', turkishSentence: 'Meslektaşından her zaman daha üstün olmak istiyordu.' },
    { id: 385, category: 'fiiller', germanWord: 'vergewissern (sich)', pronunciation: 'fer-ge-vi-sırn', germanSentence: 'Bitte vergewissern Sie sich der Richtigkeit der Daten.', turkishWord: 'emin olmak', turkishSentence: 'Lütfen verilerin doğruluğundan emin olunuz.' },

    // --- Sıfatlar ---
    { id: 386, category: 'sıfatlar', germanWord: 'spektakulär', pronunciation: 'şpek-ta-ku-leer', germanSentence: 'Das war ein wirklich spektakuläres Ereignis.', turkishWord: 'görkemli, olağanüstü, dikkat çekici', turkishSentence: 'Bu gerçekten görkemli/olağanüstü bir olaydı.' },
    { id: 387, category: 'sıfatlar', germanWord: 'spontan', pronunciation: 'şpon-taan', germanSentence: 'Meine Entscheidung war sehr spontan.', turkishWord: 'kendiliğinden, anlık, spontane', turkishSentence: 'Kararım çok anlık/spontaneydi.' },
    { id: 388, category: 'sıfatlar', germanWord: 'stabil', pronunciation: 'şta-biil', germanSentence: 'Sein Gesundheitszustand ist mittlerweile stabil.', turkishWord: 'sağlam, istikrarlı', turkishSentence: 'Onun sağlık durumu bu arada(sonunda) istikrarlı.' },
    { id: 389, category: 'sıfatlar', germanWord: 'stationär', pronunciation: 'şta-tsiy-o-neer', germanSentence: 'Die Patienten werden stationär behandelt.', turkishWord: 'yatarak (hastane), sabit', turkishSentence: 'Hastalar yatarak tedavi ediliyor.' },
    { id: 390, category: 'sıfatlar', germanWord: 'subtil', pronunciation: 'zup-tiil', germanSentence: 'Das war eine sehr subtile Anspielung.', turkishWord: 'ince, hemen göze çarpmayan', turkishSentence: 'Bu çok ince (gizli/üstü kapalı) bir imaydı.' },
    { id: 391, category: 'sıfatlar', germanWord: 'summarisch', pronunciation: 'zu-ma-riş', germanSentence: 'Er gab einen summarischen Überblick.', turkishWord: 'özet olarak, kısaca', turkishSentence: 'Kısaca bir özet (genel bakış) sundu.' },
    { id: 392, category: 'sıfatlar', germanWord: 'symbolisch', pronunciation: 'züm-boo-liş', germanSentence: 'Dieser Betrag ist nur symbolisch gemeint.', turkishWord: 'sembolik', turkishSentence: 'Bu meblağ sadece sembolik anlam taşıyor.' },
    { id: 393, category: 'sıfatlar', germanWord: 'synchron', pronunciation: 'zün-kroon', germanSentence: 'Die Bewegungen müssen synchron ablaufen.', turkishWord: 'eşzamanlı, senkronize', turkishSentence: 'Hareketler eşzamanlı (senkronize) yürütülmelidir.' },
    { id: 394, category: 'sıfatlar', germanWord: 'systematisch', pronunciation: 'züs-te-ma-tiş', germanSentence: 'Wir müssen diesem Problem systematisch begegnen.', turkishWord: 'sistemli, planlı', turkishSentence: 'Bu soruna karşı sistemli yaklaşmalıyız / karşı koymalıyız.' },
    { id: 395, category: 'sıfatlar', germanWord: 'tendenziell', pronunciation: 'ten-dentsi-yel', germanSentence: 'Das Wetter wird tendenziell besser.', turkishWord: 'eğilim olarak, genelde', turkishSentence: 'Hava genelde (eğilimsel olarak) daha iyi oluyor.' },

    // --- Bağlaçlar / Zarflar ---
    { id: 396, category: 'bağlaçlar', germanWord: 'demgemäß', pronunciation: 'dem-ge-mees', germanSentence: 'Demgemäß müssen wir unsere Strategie anpassen.', turkishWord: 'buna uygun olarak', turkishSentence: 'Buna uygun olarak stratejimizi ayarlamalıyız.' },
    { id: 397, category: 'bağlaçlar', germanWord: 'ebendeshalb', pronunciation: 'e-bın-des-halp', germanSentence: 'Ebendeshalb habe ich dich ja gerufen.', turkishWord: 'tam da bu yüzden', turkishSentence: 'Seni de tam da bu yüzden çağırdım zaten.' },
    { id: 398, category: 'bağlaçlar', germanWord: 'wenngleich', pronunciation: 'ven-glayh', germanSentence: 'Wenngleich es schwer war, so gab sie nicht auf.', turkishWord: 'her ne kadar ...-se de', turkishSentence: 'Her ne kadar zor olsa da o pes etmedi.' },
    { id: 399, category: 'bağlaçlar', germanWord: 'wohingegen', pronunciation: 'vo-hin-gey-gın', germanSentence: 'Er liebt Kaffee, wohingegen sie Tee bevorzugt.', turkishWord: '-buna karşılık, ... oysaki', turkishSentence: 'O kahve sever, oysaki o(kadın) çay tercih eder.' },
    { id: 400, category: 'bağlaçlar', germanWord: 'zugleich', pronunciation: 'tsu-glayh', germanSentence: 'Er war Arzt und Forscher zugleich.', turkishWord: 'aynı zamanda', turkishSentence: 'O aynı zamanda doktordu ve araştırmacıydı.' },
    { id: 401, category: 'bağlaçlar', germanWord: 'somit', pronunciation: 'zo-mit', germanSentence: 'Ich habe bezahlt, somit ist die Sache erledigt.', turkishWord: 'böylece, bu nedenle', turkishSentence: 'Ödememi yaptım, böylece mesele halloldu.' },
    { id: 402, category: 'bağlaçlar', germanWord: 'derweil', pronunciation: 'der-vayl', germanSentence: 'Sie kochte, derweil er den Tisch deckte.', turkishWord: 'bu sırada, o esnada', turkishSentence: 'O yemek yapıyordu, o esnada o (erkek) masayı kurdu.' },
    { id: 403, category: 'bağlaçlar', germanWord: 'obgleich', pronunciation: 'op-glayh', germanSentence: 'Obgleich er müde war, half er uns.', turkishWord: 'olmasına rağmen, -diği halde', turkishSentence: 'Yorgun olmasına rağmen bize yardım etti.' },
    { id: 404, category: 'bağlaçlar', germanWord: 'vielmehr', pronunciation: 'fiil-meer', germanSentence: 'Es ist nicht kalt, vielmehr ist es windig.', turkishWord: 'daha ziyade, daha doğrusu', turkishSentence: 'Hava soğuk değil, daha doğrusu rüzgarlı.' },
    { id: 405, category: 'bağlaçlar', germanWord: 'dessen ungeachtet', pronunciation: 'de-sın un-ge-ah-tıt', germanSentence: 'Dessen ungeachtet müssen wir fortfahren.', turkishWord: 'buna bakılmaksızın, buna rağmen', turkishSentence: 'Buna bakılmaksızın devam etmeliyiz.' }
];

export default data9;
