const data16 = [
    // --- İsimler (Zorluk Seviyesi C1) ---
    { id: 711, category: 'isimler', germanWord: 'das Resümee /-s', pronunciation: 'das re-zü-mee', germanSentence: 'Wir können ein positives Resümee ziehen.', turkishWord: 'özet, sonuç', turkishSentence: 'Olumlu bir sonuç (özet) çıkarabiliriz.' },
    { id: 712, category: 'isimler', germanWord: 'die Routine /-n', pronunciation: 'di ru-tii-nı', germanSentence: 'Es ist wichtig, aus der täglichen Routine auszubrechen.', turkishWord: 'rutin, alışkanlık', turkishSentence: 'Günlük rutinden kopmak/çıkmak önemlidir.' },
    { id: 713, category: 'isimler', germanWord: 'die Sanktion /-en', pronunciation: 'di zank-tsion', germanSentence: 'Die UNO hat schwere wirtschaftliche Sanktionen verhängt.', turkishWord: 'yaptırım, müeyyide', turkishSentence: 'BM ağır ekonomik yaptırımlar uyguladı.' },
    { id: 714, category: 'isimler', germanWord: 'der Sektor /-en', pronunciation: 'der zek-toor', germanSentence: 'Der IT-Sektor wächst rasant.', turkishWord: 'sektör, kesim, alan', turkishSentence: 'Bilişim sektörü hızla büyüyor.' },
    { id: 715, category: 'isimler', germanWord: 'das Semester /-', pronunciation: 'das ze-mes-tır', germanSentence: 'Ich belege diesen Kurs im nächsten Semester.', turkishWord: 'sömestr, yarıyıl', turkishSentence: 'Bu dersi gelecek yarıyılda alıyorum.' },
    { id: 716, category: 'isimler', germanWord: 'das Seminar /-e', pronunciation: 'das ze-mi-naar', germanSentence: 'Das Seminar zum Thema Führung war sehr hilfreich.', turkishWord: 'seminer, çalışma grubu', turkishSentence: 'Liderlik konulu seminer çok yardımcıydı.' },
    { id: 717, category: 'isimler', germanWord: 'die Sensibilität', pronunciation: 'di zen-zi-bi-li-teet', germanSentence: 'Das Thema erfordert viel Sensibilität.', turkishWord: 'duyarlılık, hassasiyet', turkishSentence: 'Konu büyük bir hassasiyet/duyarlılık gerektiriyor.' },
    { id: 718, category: 'isimler', germanWord: 'das Spektrum', pronunciation: 'das şpek-trum', germanSentence: 'Das politische Spektrum spaltete sich.', turkishWord: 'yelpaze, çeşitlilik', turkishSentence: 'Siyasi yelpaze bölündü.' },
    { id: 719, category: 'isimler', germanWord: 'das Stadium', pronunciation: 'das ştaa-diyum', germanSentence: 'Die Krankheit befindet sich im Anfangsstadium.', turkishWord: 'evre, aşama', turkishSentence: 'Hastalık başlangıç evresinde bulunuyor.' },
    { id: 720, category: 'isimler', germanWord: 'die Stagnation', pronunciation: 'di ştag-na-tsiyon', germanSentence: 'Nach Jahren des Wachstums kam die Stagnation.', turkishWord: 'durgunluk, duraklama', turkishSentence: 'Büyüme yıllarından sonra durgunluk geldi.' },

    // --- Fiiller (Zorluk Seviyesi C1) ---
    { id: 721, category: 'fiiller', germanWord: 'hervorheben', pronunciation: 'her-foor-hey-bın', germanSentence: 'Ich möchte besonders ihren Einsatz hervorheben.', turkishWord: 'vurgulamak, öne çıkarmak', turkishSentence: 'Özellikle onun çabasını(katkısını) vurgulamak istiyorum.' },
    { id: 722, category: 'fiiller', germanWord: 'hinauszögern', pronunciation: 'hi-naus-tsö-gırn', germanSentence: 'Wir können die Entscheidung nicht länger hinauszögern.', turkishWord: 'geciktirmek, ertelemek', turkishSentence: 'Kararı daha fazla geciktiremeyiz.' },
    { id: 723, category: 'fiiller', germanWord: 'identifizieren (sich)', pronunciation: 'i-den-ti-fi-tsii-rın', germanSentence: 'Ich kann mich mit dieser Rolle nicht identifizieren.', turkishWord: 'özdeşleşmek', turkishSentence: 'Kendimi bu rolle özdeşleştiremiyorum.' },
    { id: 724, category: 'fiiller', germanWord: 'ignorieren', pronunciation: 'ig-no-rii-rın', germanSentence: 'Man darf diese Warnzeichen nicht ignorieren.', turkishWord: 'görmezden gelmek, umursamamak', turkishSentence: 'Bu uyarı işaretleri görmezden gelinemez.' },
    { id: 725, category: 'fiiller', germanWord: 'implementieren', pronunciation: 'im-ple-men-tii-rın', germanSentence: 'Die neue Software wird ab Montag implementiert.', turkishWord: 'uygulamak, hayata geçirmek', turkishSentence: 'Yeni yazılım pazartesiden itibaren uygulanacak(hayata geçirilecek).' },
    { id: 726, category: 'fiiller', germanWord: 'implizieren', pronunciation: 'im-pli-tsii-rın', germanSentence: 'Deine Aussage impliziert, dass ich gelogen habe.', turkishWord: 'ima etmek, kapsamak', turkishSentence: 'İfaden benim yalan söylediğimi ima ediyor.' },
    { id: 727, category: 'fiiller', germanWord: 'inspirieren', pronunciation: 'ins-pi-rii-rın', germanSentence: 'Seine Reise nach Indien hat dieses Buch inspiriert.', turkishWord: 'ilham vermek', turkishSentence: 'Onun Hindistan seyahati bu kitaba ilham verdi.' },
    { id: 728, category: 'fiiller', germanWord: 'integrieren', pronunciation: 'in-te-grii-rın', germanSentence: 'Die Einwanderer müssen in die Gesellschaft integriert werden.', turkishWord: 'entegre etmek, uyum sağlamak', turkishSentence: 'Göçmenler topluma entegre edilmelidir.' },
    { id: 729, category: 'fiiller', germanWord: 'intensivieren', pronunciation: 'in-ten-zi-vii-rın', germanSentence: 'Wir müssen unsere Bemühungen intensivieren.', turkishWord: 'yoğunlaştırmak', turkishSentence: 'Çabalarımızı yoğunlaştırmalıyız.' },
    { id: 730, category: 'fiiller', germanWord: 'interpretieren', pronunciation: 'in-ter-pre-tii-rın', germanSentence: 'Wie interpretieren Sie dieses Gedicht?', turkishWord: 'yorumlamak', turkishSentence: 'Bu şiiri nasıl yorumluyorsunuz?' },

    // --- Sıfatlar (Zorluk Seviyesi C1) ---
    { id: 731, category: 'sıfatlar', germanWord: 'abrupt', pronunciation: 'ap-rupt', germanSentence: 'Das Auto kam zu einem abrupten Halt.', turkishWord: 'ani, birdenbire', turkishSentence: 'Araba aniden (birdenbire) durdu.' },
    { id: 732, category: 'sıfatlar', germanWord: 'absolut', pronunciation: 'ap-zo-luut', germanSentence: 'Ich habe absolutes Vertrauen in dich.', turkishWord: 'mutlak, kesin, tam', turkishSentence: 'Sana olan güvenim mutlaktır(kesindir).' },
    { id: 733, category: 'sıfatlar', germanWord: 'absurd', pronunciation: 'ap-zurt', germanSentence: 'Diese Forderung ist völlig absurd.', turkishWord: 'saçma, abes', turkishSentence: 'Bu talep tamamen saçma.' },
    { id: 734, category: 'sıfatlar', germanWord: 'akzeptabel', pronunciation: 'ak-tsep-taa-bıl', germanSentence: 'Das ist eine akzeptable Lösung für alle Beteiligten.', turkishWord: 'kabul edilebilir', turkishSentence: 'Bu, katılan herkes için kabul edilebilir bir çözüm.' },
    { id: 735, category: 'sıfatlar', germanWord: 'analog', pronunciation: 'a-na-look', germanSentence: 'Das alte Telefonnetz war noch analog.', turkishWord: 'analog, benzer özellik gösteren', turkishSentence: 'Eski telefon ağı henüz analog idi.' },
    { id: 736, category: 'sıfatlar', germanWord: 'banal', pronunciation: 'ba-naal', germanSentence: 'Die Antwort auf diese komplexe Frage ist banal.', turkishWord: 'sıradan, bayağı, aşırı basit', turkishSentence: 'Bu karmaşık sorunun cevabı çok sıradandır.' },
    { id: 737, category: 'sıfatlar', germanWord: 'defekt', pronunciation: 'de-fekt', germanSentence: 'Der Drucker ist leider schon wieder defekt.', turkishWord: 'bozuk, arızalı', turkishSentence: 'Yazıcı maalesef yine bozulmuş(arızalı).' },
    { id: 738, category: 'sıfatlar', germanWord: 'definitiv', pronunciation: 'de-fi-ni-tiif', germanSentence: 'Das ist mein definitives Angebot.', turkishWord: 'kesin, nihai', turkishSentence: 'Bu benim kesin (nihai) teklifimdir.' },
    { id: 739, category: 'sıfatlar', germanWord: 'diskret', pronunciation: 'dis-kreet', germanSentence: 'Bitte behandeln Sie diese Information sehr diskret.', turkishWord: 'gizli, sır tutan, takdir yetkili', turkishSentence: 'Lütfen bu bilgiyi çok gizli (özel) olarak ele alın.' },
    { id: 740, category: 'sıfatlar', germanWord: 'drastisch', pronunciation: 'dras-tiş', germanSentence: 'Wir müssen drastische Maßnahmen ergreifen.', turkishWord: 'etkili, sert, şiddetli', turkishSentence: 'Şiddetli(etkili/sert) önlemler almalıyız.' },

    // --- Karışık (Bağlaçlar, Zarflar, Sıfatlar) ---
    { id: 741, category: 'bağlaçlar', germanWord: 'ebenso', pronunciation: 'e-bın-zo', germanSentence: 'Er ist ebenso begabt wie sein Bruder.', turkishWord: 'aynı şekilde, kadar (kıyaslama)', turkishSentence: 'O da erkek kardeşi kadar yetenekli.' },
    { id: 742, category: 'bağlaçlar', germanWord: 'demzufolge', pronunciation: 'dem-tsu-fol-gı', germanSentence: 'Es regnete stark, demzufolge fiel das Konzert aus.', turkishWord: 'buna göre, bunun sonucunda', turkishSentence: 'Çok yağmur yağdı, bunun sonucunda konser iptal oldu.' },
    { id: 743, category: 'bağlaçlar', germanWord: 'nichtsdestotrotz', pronunciation: 'nih-tsdes-to-trots', germanSentence: 'Es regnet, nichtsdestotrotz gehen wir spazieren.', turkishWord: 'yine de, buna rağmen', turkishSentence: 'Yağmur yağıyor, buna rağmen yürüyüşe çıkıyoruz.' },
    { id: 744, category: 'bağlaçlar', germanWord: 'obzwar', pronunciation: 'op-tsvaar', germanSentence: 'Obzwar er krank ist, geht er arbeiten.', turkishWord: 'gerçi, olmasına rağmen', turkishSentence: 'Gerçi hasta ama yine de çalışmaya gidiyor.' },
    { id: 745, category: 'bağlaçlar', germanWord: 'gleichwohl', pronunciation: 'glayh-vool', germanSentence: 'Das Haus ist alt, gleichwohl ist es sehr teuer.', turkishWord: 'bununla birlikte, yine de', turkishSentence: 'Ev eski, bununla birlikte (yine de) oldukça pahalı.' },
    { id: 746, category: 'isimler', germanWord: 'die Toleranz', pronunciation: 'di to-le-rants', germanSentence: 'Eine demokratische Gesellschaft erfordert Toleranz.', turkishWord: 'hoşgörü', turkishSentence: 'Demokratik bir toplum hoşgörü gerektirir.' },
    { id: 747, category: 'isimler', germanWord: 'die Tragödie /-n', pronunciation: 'di tra-göö-dih', germanSentence: 'Der zweite Weltkrieg war eine menschliche Tragödie.', turkishWord: 'trajedi, felaket', turkishSentence: 'İkinci Dünya Savaşı insani bir trajediydi.' },
    { id: 748, category: 'isimler', germanWord: 'die Transparenz', pronunciation: 'di trans-pa-rents', germanSentence: 'Die Bürger fordern mehr Transparenz in der Politik.', turkishWord: 'şeffaflık', turkishSentence: 'Vatandaşlar politikada daha fazla şeffaflık talep ediyor.' },
    { id: 749, category: 'isimler', germanWord: 'der Trend /-s', pronunciation: 'der trent', germanSentence: 'Dieser Modestil liegt total im Trend.', turkishWord: 'eğilim, moda, trend', turkishSentence: 'Bu moda stili tamamen trend (eğilim) doğrultusunda.' },
    { id: 750, category: 'isimler', germanWord: 'die Variante /-n', pronunciation: 'di va-ri-yan-tı', germanSentence: 'Wir haben uns für die günstigste Variante entschieden.', turkishWord: 'seçenek, uyarlama', turkishSentence: 'En uygun fiyatlı seçeneğe karar verdik.' },

    // --- Ekstra Fiiller / İsimler ---
    { id: 751, category: 'fiiller', germanWord: 'justieren', pronunciation: 'yus-tii-rın', germanSentence: 'Das Teleskop muss neu justiert werden.', turkishWord: 'ayarlamak, ince ayar yapmak', turkishSentence: 'Teleskop yeniden ayarlanmalıdır.' },
    { id: 752, category: 'fiiller', germanWord: 'kapitulieren', pronunciation: 'ka-pi-tu-lii-rın', germanSentence: 'Die feindliche Armee musste am Ende kapitulieren.', turkishWord: 'teslim olmak, silah bırakmak', turkishSentence: 'Düşman ordusu sonunda teslim olmak zorunda kaldı.' },
    { id: 753, category: 'fiiller', germanWord: 'kassieren', pronunciation: 'ka-sii-rın', germanSentence: 'Die Regierung will neue Steuern kassieren.', turkishWord: 'tahsil etmek, para almak', turkishSentence: 'Hükümet yeni vergiler tahsil etmek istiyor.' },
    { id: 754, category: 'fiiller', germanWord: 'koalieren', pronunciation: 'ko-a-lii-rın', germanSentence: 'Die beiden Parteien koalieren, um die Macht zu übernehmen.', turkishWord: 'koalisyon kurmak, birleşmek', turkishSentence: 'Her iki parti gücü devralmak için koalisyon kuruyor.' },
    { id: 755, category: 'fiiller', germanWord: 'kollidieren', pronunciation: 'ko-li-dii-rın', germanSentence: 'Zwei Züge sind auf freier Strecke kollidiert.', turkishWord: 'çarpışmak', turkishSentence: 'İki tren açık güzergahta(hatta) çarpıştı.' },
    { id: 756, category: 'isimler', germanWord: 'die Vision /-en', pronunciation: 'di vi-zi-yon', germanSentence: 'Er hat eine klare Vision von der Zukunft.', turkishWord: 'vizyon, öngörü', turkishSentence: 'Onun gelecekle ilgili net bir vizyonu var.' },
    { id: 757, category: 'isimler', germanWord: 'das Volumen', pronunciation: 'das vo-lu-mın', germanSentence: 'Das Handelsvolumen ist letztes Jahr deutlich gestiegen.', turkishWord: 'hacim, kapasite', turkishSentence: 'Ticaret hacmi geçen yıl belirgin bir şekilde arttı.' },
    { id: 758, category: 'isimler', germanWord: 'das Zitat /-e', pronunciation: 'das tsi-taat', germanSentence: 'Dieses Zitat stammt von Albert Einstein.', turkishWord: 'alıntı', turkishSentence: 'Bu alıntı Albert Einstein\'a aittir.' },
    { id: 759, category: 'isimler', germanWord: 'die Ära', pronunciation: 'di ey-ra', germanSentence: 'Mit dem Fall der Mauer begann eine neue Ära.', turkishWord: 'çağ, devir, dönem', turkishSentence: 'Duvarın yıkılmasıyla yeni bir devir(çağ) başladı.' },
    { id: 760, category: 'isimler', germanWord: 'die Ästhetik', pronunciation: 'di es-tee-tik', germanSentence: 'Die japanische Ästhetik ist sehr minimalistisch.', turkishWord: 'estetik', turkishSentence: 'Japon estetiği oldukça minimalisttir.' },

    // --- Sıfatlar/Zarflar ---
    { id: 761, category: 'sıfatlar', germanWord: 'absurd', pronunciation: 'ap-zurt', germanSentence: 'Sein Vorschlag ist komplett absurd.', turkishWord: 'absürt, mantıksız', turkishSentence: 'Onun önerisi tamamen mantıksızdır(absürttür).' },
    { id: 762, category: 'sıfatlar', germanWord: 'adäquat', pronunciation: 'a-de-kvaat', germanSentence: 'Dies war keine adäquate Reaktion auf die Bedrohung.', turkishWord: 'uygun, yeterli, denk', turkishSentence: 'Bu tehlikeye karşı yeterli/uygun bir tepki değildi.' },
    { id: 763, category: 'sıfatlar', germanWord: 'affektiv', pronunciation: 'a-fek-tiif', germanSentence: 'Seine Handlung war rein affektiv und unüberlegt.', turkishWord: 'duygusal (anlık hislerle)', turkishSentence: 'Eylemi tamamen duygusal(anlık) ve düşünülmeden yapılmıştı.' },
    { id: 764, category: 'sıfatlar', germanWord: 'agil', pronunciation: 'a-giil', germanSentence: 'Trotz seines Alters ist er geistig noch sehr agil.', turkishWord: 'çevik, atik, zinde', turkishSentence: 'Yaşına rağmen zihinsel olarak hala çok zinde.' },
    { id: 765, category: 'sıfatlar', germanWord: 'aggressiv', pronunciation: 'a-gre-siif', germanSentence: 'Der Hund reagierte extrem aggressiv.', turkishWord: 'agresif, saldırgan', turkishSentence: 'Köpek aşırı derecede saldırganca tepki verdi.' },
    { id: 766, category: 'sıfatlar', germanWord: 'ambivalent', pronunciation: 'am-bi-va-lent', germanSentence: 'Ich habe eine ambivalente Einstellung zu dieser Frage.', turkishWord: 'çelişik duygulu, kararsız', turkishSentence: 'Bu soruya(konuya) karşı çelişkili duygular içindeyim.' },
    { id: 767, category: 'sıfatlar', germanWord: 'anonym', pronunciation: 'a-no-nüm', germanSentence: 'Der Spender wollte anonym bleiben.', turkishWord: 'anonim, isimsiz', turkishSentence: 'Bağışçı isimsiz (anonim) kalmak istedi.' },
    { id: 768, category: 'sıfatlar', germanWord: 'antagonistisch', pronunciation: 'an-ta-go-nis-tiş', germanSentence: 'Sie vertraten völlig antagonistische Positionen.', turkishWord: 'zıt, çatışan', turkishSentence: 'Tamamen zıt (çatışan) pozisyonları savunuyorlardı.' },
    { id: 769, category: 'sıfatlar', germanWord: 'apathisch', pronunciation: 'a-pa-tiş', germanSentence: 'Nach dem Schock lag er apathisch auf dem Boden.', turkishWord: 'ilgisiz, tepkisiz', turkishSentence: 'Şoktan sonra tepkisizce yerde yatıyordu.' },
    { id: 770, category: 'sıfatlar', germanWord: 'arrogant', pronunciation: 'a-ro-gant', germanSentence: 'Sie fiel durch ihr extrem arrogantes Verhalten auf.', turkishWord: 'kibirli, küstah', turkishSentence: 'Aşırı kibirli davranışıyla dikkat çekti(göze battı).' }
];

export default data16;
