const data17 = [
    // --- Sürekli İlerleyiş ---
    { id: 771, category: 'sıfatlar', germanWord: 'autark', pronunciation: 'au-tark', germanSentence: 'Dieses Dorf versorgt sich komplett autark mit Energie.', turkishWord: 'kendine yeten, özerk', turkishSentence: 'Bu köy tamamen kendi kendine yeterek enerji sağlıyor.' },
    { id: 772, category: 'sıfatlar', germanWord: 'authentisch', pronunciation: 'au-ten-tiş', germanSentence: 'Ihr Dialekt klingt sehr authentisch.', turkishWord: 'sahici, otantik, aslına uygun', turkishSentence: 'Onun şivesi çok otantik(sahici) geliyor.' },
    { id: 773, category: 'sıfatlar', germanWord: 'autoritär', pronunciation: 'au-to-ri-teer', germanSentence: 'Er führt das Unternehmen mit sehr autoritärer Hand.', turkishWord: 'otoriter, baskıcı', turkishSentence: 'Şirketi çok otoriter bir elle yönetiyor.' },
    { id: 774, category: 'sıfatlar', germanWord: 'avantgardistisch', pronunciation: 'a-van-gaar-dis-tiş', germanSentence: 'Das Theaterstück war sehr avantgardistisch.', turkishWord: 'öncü, yenilikçi (sanat vb.)', turkishSentence: 'Tiyatro oyunu oldukça yenilikçiydi(öncüydü).' },
    { id: 775, category: 'sıfatlar', germanWord: 'barbarisch', pronunciation: 'bar-baa-riş', germanSentence: 'So ein barbarisches Verhalten ist inakzeptabel.', turkishWord: 'barbarca, vahşice', turkishSentence: 'Böyle barbarca bir davranış kabul edilemez.' },
    { id: 776, category: 'sıfatlar', germanWord: 'barmherzig', pronunciation: 'barm-her-tsik', germanSentence: 'Sie war eine barmherzige Samariterin.', turkishWord: 'merhametli, sevecen', turkishSentence: 'O merhametli bir Samiriyeliydi (yardımsever biriydi).' },
    { id: 777, category: 'sıfatlar', germanWord: 'bigott', pronunciation: 'bi-got', germanSentence: 'Seine Ansichten sind meiner Meinung nach sehr bigott.', turkishWord: 'bağnaz, yobaz, ikiyüzlü', turkishSentence: 'Bence onun görüşleri çok bağnazca.' },
    { id: 778, category: 'sıfatlar', germanWord: 'bizarr', pronunciation: 'bi-tsaar', germanSentence: 'Der Traum, den ich hatte, war völlig bizarr.', turkishWord: 'acayip, tuhaf, garip', turkishSentence: 'Gördüğüm rüya tamamen tuhaftı(acayipti).' },
    { id: 779, category: 'sıfatlar', germanWord: 'bombastisch', pronunciation: 'bom-bas-tiş', germanSentence: 'Dieses Erlebnis war einfach nur bombastisch!', turkishWord: 'görkemli, şatafatlı, harika', turkishSentence: 'Bu deneyim tek kelimeyle harikaydı(görkemliydi)!' },
    { id: 780, category: 'sıfatlar', germanWord: 'boshaft', pronunciation: 'boos-haft', germanSentence: 'Das war eine sehr boshafte Bemerkung.', turkishWord: 'kötü niyetli, hain', turkishSentence: 'Bu çok kötü niyetli bir açıklamaydı.' },

    // --- İsimler ---
    { id: 781, category: 'isimler', germanWord: 'die Analogie', pronunciation: 'a-na-lo-gii', germanSentence: 'Man kann hier eine klare Analogie ziehen.', turkishWord: 'benzerlik, andırış', turkishSentence: 'Burada net bir benzerlik kurulabilir.' },
    { id: 782, category: 'isimler', germanWord: 'die Anekdote', pronunciation: 'a-nek-doo-tı', germanSentence: 'Er erzählte eine lustige Anekdote aus seiner Jugend.', turkishWord: 'kısa ve ilginç hikaye, anekdot', turkishSentence: 'Gençliğinden komik bir çocukluk/kısa hikaye anlattı.' },
    { id: 783, category: 'isimler', germanWord: 'das Äquivalent', pronunciation: 'e-kvi-va-lent', germanSentence: 'Es gibt im Deutschen kein exaktes Äquivalent für dieses Wort.', turkishWord: 'eşdeğer, karşılık', turkishSentence: 'Bu kelimenin Almancada tam bir karşılığı(eşdeğeri) yoktur.' },
    { id: 784, category: 'isimler', germanWord: 'die Assoziation', pronunciation: 'a-so-tsi-ya-tsion', germanSentence: 'Welche Assoziationen weckt dieses Bild bei Ihnen?', turkishWord: 'çağrışım, dernek(bağlam dışı)', turkishSentence: 'Bu resim sizde hangi çağrışımları uyandırıyor?' },
    { id: 785, category: 'isimler', germanWord: 'das Attribut', pronunciation: 'a-tri-buut', germanSentence: 'Geduld ist ein wichtiges Attribut eines Lehrers.', turkishWord: 'niteleme, özellik, vasıf', turkishSentence: 'Sabır bir öğretmenin önemli bir vasfıdır.' },
    { id: 786, category: 'isimler', germanWord: 'die Authentizität', pronunciation: 'au-ten-ti-tsi-teet', germanSentence: 'Die Authentizität des Dokuments wird derzeit geprüft.', turkishWord: 'sahicilik, güvenilirlik, aslına uygunluk', turkishSentence: 'Belgenin sahiciliği(orijinalliği) şu an kontrol ediliyor.' },
    { id: 787, category: 'isimler', germanWord: 'die Autorität', pronunciation: 'au-to-ri-teet', germanSentence: 'Er ist eine anerkannte Autorität auf diesem Gebiet.', turkishWord: 'otorite, bilirkişi', turkishSentence: 'O bu alanda tanınmış bir otoritedir.' },
    { id: 788, category: 'isimler', germanWord: 'das Defizit', pronunciation: 'de-fi-tsit', germanSentence: 'Der Staatshaushalt weist ein riesiges Defizit auf.', turkishWord: 'açık (bütçe), eksiklik', turkishSentence: 'Devlet bütçesi devasa bir açık veriyor.' },
    { id: 789, category: 'isimler', germanWord: 'die Dekadenz', pronunciation: 'de-ka-dents', germanSentence: 'Die späte römische Republik war von Dekadenz geprägt.', turkishWord: 'çöküş, yozlaşma', turkishSentence: 'Geç Roma Cumhuriyeti çöküş(yozlaşma) ile karakterizeydi.' },
    { id: 790, category: 'isimler', germanWord: 'die Demagogie', pronunciation: 'de-ma-go-gii', germanSentence: 'Er benutzt reine Demagogie, um Wähler zu gewinnen.', turkishWord: 'halk avcılığı, demagoji', turkishSentence: 'Seçmen kazanmak için saf demagoji kullanıyor.' },

    // --- Fiiller ---
    { id: 791, category: 'fiiller', germanWord: 'akquirieren', pronunciation: 'a-kvi-rii-rın', germanSentence: 'Das Unternehmen will weitere Kunden akquirieren.', turkishWord: 'kazanmak (müşteri/şirket), elde etmek', turkishSentence: 'Şirket daha fazla müşteri kazanmak istiyor.' },
    { id: 792, category: 'fiiller', germanWord: 'agieren', pronunciation: 'a-gii-rın', germanSentence: 'In der Krise muss man schnell agieren.', turkishWord: 'hareket etmek, eyleme geçmek', turkishSentence: 'Kriz anında hızlı hareket etmek/eyleme geçmek gerekir.' },
    { id: 793, category: 'fiiller', germanWord: 'allokieren', pronunciation: 'a-lo-kii-rın', germanSentence: 'Wir müssen die Ressourcen effizient allokieren.', turkishWord: 'tahsis etmek (kaynak)', turkishSentence: 'Kaynakları verimli bir şekilde tahsis etmeliyiz.' },
    { id: 794, category: 'fiiller', germanWord: 'affirmieren', pronunciation: 'a-fir-mii-rın', germanSentence: 'Sie wollte ihre Loyalität noch einmal affirmieren.', turkishWord: 'doğrulamak, onaylamak, tasdik etmek', turkishSentence: 'Sadakatini bir kez daha tasdik etmek(onaylamak) istedi.' },
    { id: 795, category: 'fiiller', germanWord: 'boykottieren', pronunciation: 'boy-ko-tii-rın', germanSentence: 'Viele Aktivisten boykottieren diese Marke.', turkishWord: 'boykot etmek', turkishSentence: 'Birçok aktivist bu markayı boykot ediyor.' },
    { id: 796, category: 'fiiller', germanWord: 'brüskieren', pronunciation: 'brüs-kii-rın', germanSentence: 'Er hat den Gast durch sein Verhalten brüskiert.', turkishWord: 'kabalık etmek, gücendirmek', turkishSentence: 'Davranışıyla konuğu gücendirdi(tersledi).' },
    { id: 797, category: 'fiiller', germanWord: 'charakterisieren', pronunciation: 'ka-rak-te-ri-zii-rın', germanSentence: 'Wie würden Sie seinen Schreibstil charakterisieren?', turkishWord: 'vasıflandırmak, nitelendirmek, ayırt etmek', turkishSentence: 'Onun yazım stilini nasıl nitelendirirsiniz?' },
    { id: 798, category: 'fiiller', germanWord: 'dechiffrieren', pronunciation: 'de-şi-frii-rın', germanSentence: 'Es dauerte Wochen, um diesen Code zu dechiffrieren.', turkishWord: 'şifre çözmek', turkishSentence: 'Bu kodu çözmek haftalar aldı.' },
    { id: 799, category: 'fiiller', germanWord: 'delegieren', pronunciation: 'de-le-gii-rın', germanSentence: 'Du solltest mehr von diesen Aufgaben delegieren.', turkishWord: 'devretmek', turkishSentence: 'Bu görevlerden daha fazlasını devretmelisin.' },
    { id: 800, category: 'fiiller', germanWord: 'demaskieren', pronunciation: 'de-mas-kii-rın', germanSentence: 'Ihre Absichten wurden schließlich demaskiert.', turkishWord: 'maskesini düşürmek, gerçek yüzünü ortaya çıkarmak', turkishSentence: 'Onun niyetleri sonunda deşifre edildi(maskesi düşürüldü).' },

    // --- Sıfatlar ---
    { id: 801, category: 'sıfatlar', germanWord: 'cholerisch', pronunciation: 'ko-lee-riş', germanSentence: 'Sein Vorgesetzter hat oft cholerische Anfälle.', turkishWord: 'çabuk sinirlenen, asabi', turkishSentence: 'Amirinin sık sık asabiyet(öfke) nöbetleri oluyor.' },
    { id: 802, category: 'sıfatlar', germanWord: 'dekadent', pronunciation: 'de-ka-dent', germanSentence: 'Ihr luxuriöser Lebensstil wirkt fast schon dekadent.', turkishWord: 'yozlaşmış, çöküşte olan', turkishSentence: 'Onların lüks yaşam tarzı neredeyse yozlaşmış(çökmüş) görünüyor.' },
    { id: 803, category: 'sıfatlar', germanWord: 'diffus', pronunciation: 'di-fuus', germanSentence: 'Das Licht im Raum war sehr diffus.', turkishWord: 'dağınık, belirsiz, yayılmış', turkishSentence: 'Odadaki ışık oldukça belirsizdi(dağınıktı).' },
    { id: 804, category: 'sıfatlar', germanWord: 'dogmatisch', pronunciation: 'dog-maa-tiş', germanSentence: 'Man darf an diese Sache nicht dogmatisch herangehen.', turkishWord: 'dogmatik, peşin hükümlü', turkishSentence: 'Bu konuya dogmatik(önyargılı/peşin hükümlü) yaklaşılmamalı.' },
    { id: 805, category: 'sıfatlar', germanWord: 'düster', pronunciation: 'düs-tır', germanSentence: 'Die Zukunftsaussichten sind sehr düster.', turkishWord: 'karanlık, karamsar', turkishSentence: 'Gelecek beklentileri çok karanlık(karamsar).' },
    { id: 806, category: 'sıfatlar', germanWord: 'dynamisch', pronunciation: 'dü-na-miş', germanSentence: 'Wir leben in einer extrem dynamischen Welt.', turkishWord: 'dinamik, hareketli', turkishSentence: 'Aşırı dinamik/hareketli bir dünyada yaşıyoruz.' },
    { id: 807, category: 'sıfatlar', germanWord: 'egoistisch', pronunciation: 'e-go-is-tiş', germanSentence: 'Das war eine rein egoistische Entscheidung.', turkishWord: 'bencil', turkishSentence: 'Bu tamamen bencilce bir karardı.' },
    { id: 808, category: 'sıfatlar', germanWord: 'eklatant', pronunciation: 'ek-la-tant', germanSentence: 'Es gab eklatante Fehler in der Planung.', turkishWord: 'göze batan, bariz', turkishSentence: 'Planlamada göze batan (bariz) hatalar vardı.' },
    { id: 809, category: 'sıfatlar', germanWord: 'eleganz', pronunciation: 'e-le-gants', germanSentence: 'Sie betrat den Raum mit einer unglaublichen Eleganz. (adj: elegant)', turkishWord: 'zarif, şık', turkishSentence: 'Odaya inanılmaz bir zarafetle girdi. (Sıfat hali: elegant)' },
    { id: 810, category: 'sıfatlar', germanWord: 'elitär', pronunciation: 'e-li-teer', germanSentence: 'Dieser Club hat einen sehr elitären Ruf.', turkishWord: 'seçkinci, elitist', turkishSentence: 'Bu kulübün oldukça seçkinci bir ünü var.' },

    // --- Bağlaçlar / Zarflar / İfadeler ---
    { id: 811, category: 'bağlaçlar', germanWord: 'gleichwie', pronunciation: 'glayh-vii', germanSentence: 'Gleichwie man es betrachtet, es bleibt ein Problem.', turkishWord: 'nasıl olursa olsun, her ne şekilde', turkishSentence: 'Nasıl bakılırsa bakılsın, bu bir sorun olmaya devam ediyor.' },
    { id: 812, category: 'bağlaçlar', germanWord: 'unstreitig', pronunciation: 'un-ştray-tik', germanSentence: 'Ein unstreitig großer Erfolg für die Menschheit.', turkishWord: 'tartışmasız, su götürmez', turkishSentence: 'İnsanlık için tartışmasız büyük bir başarı.' },
    { id: 813, category: 'bağlaçlar', germanWord: 'widrigenfalls', pronunciation: 'vid-ri-gın-fals', germanSentence: 'Antworten Sie, widrigenfalls gehen wir vor Gericht.', turkishWord: 'aksi taktirde', turkishSentence: 'Cevap verin, aksi takdirde mahkemeye gideriz.' },
    { id: 814, category: 'bağlaçlar', germanWord: 'zudem', pronunciation: 'tsu-deem', germanSentence: 'Er war müde und zudem krank.', turkishWord: 'ayrıca, üstelik', turkishSentence: 'O yorgundu ve üstelik hastaydı.' },
    { id: 815, category: 'bağlaçlar', germanWord: 'zuliebe', pronunciation: 'tsu-lii-bı', germanSentence: 'Mache es mir zuliebe!', turkishWord: 'hatırı için, uğruna', turkishSentence: 'Benim hatırım için yap!' },
    { id: 816, category: 'bağlaçlar', germanWord: 'infolge', pronunciation: 'in-fol-gı', germanSentence: 'Viele starben infolge der Epidemie.', turkishWord: 'sonucunda', turkishSentence: 'Birçoğu salgın sonucunda(nedeniyle) öldü.' },
    { id: 817, category: 'isimler', germanWord: 'die Diskrepanz', pronunciation: 'dis-kre-pants', germanSentence: 'Da klafft eine enorme Diskrepanz auf.', turkishWord: 'farklılık, uyumsuzluk (geniş uçurum)', turkishSentence: 'Orada devasa bir uyumsuzluk/farklılık açılıyor(görünüyor).' },
    { id: 818, category: 'isimler', germanWord: 'der Euphemismus', pronunciation: 'oy-fe-mis-mus', germanSentence: 'Das Wort ist lediglich ein Euphemismus für Tod.', turkishWord: 'örtmece, acı bir şeyi tatlı söyleme', turkishSentence: 'Bu kelime basitçe(sadece) ölüm için bir örtmecedir.' },
    { id: 819, category: 'isimler', germanWord: 'das Fauxpas', pronunciation: 'fo-paa', germanSentence: 'Das war ein gesellschaftlicher Fauxpas.', turkishWord: 'gaf, pot, çam devirme', turkishSentence: 'Bu sosyal/toplumsal bir gaf(pot) idi.' },
    { id: 820, category: 'isimler', germanWord: 'der Hypochonder', pronunciation: 'hü-po-kon-dır', germanSentence: 'Bist du vielleicht ein Hypochonder?', turkishWord: 'hastalık hastası', turkishSentence: 'Sen belki bir hastalık hastası mısın?' },

    // --- Ekstra ---
    { id: 821, category: 'fiiller', germanWord: 'desavouieren', pronunciation: 'des-avu-ii-rın', germanSentence: 'Der Politiker hat sich komplett desavouiert.', turkishWord: 'itibarını düşürmek, inkar etmek', turkishSentence: 'Politikacı tamamen kendi itibarını düşürdü.' },
    { id: 822, category: 'fiiller', germanWord: 'eliminieren', pronunciation: 'e-li-mi-nii-rın', germanSentence: 'Wir müssen alle Fehlerquellen eliminieren.', turkishWord: 'yok etmek, elemek', turkishSentence: 'Tüm hata kaynaklarını yok(elemiş) etmeliyiz.' },
    { id: 823, category: 'fiiller', germanWord: 'emanzipieren', pronunciation: 'em-an-tsi-pii-rın', germanSentence: 'Wir müssen uns von alten Zwängen emanzipieren.', turkishWord: 'özgürleşmek, bağımsızlaşmak', turkishSentence: 'Kendimizi eski zorlamalardan kurtarmalı (özgürleştirmeli)yız.' },
    { id: 824, category: 'fiiller', germanWord: 'fingieren', pronunciation: 'fin-gii-rın', germanSentence: 'Der Tod wurde nur fingiert.', turkishWord: 'uydurmak, numara yapmak, sahte (süs) vermek', turkishSentence: 'Ölüm sadece bir numaraydı (uydurmaydı/kurguydu).' },
    { id: 825, category: 'fiiller', germanWord: 'fokussieren', pronunciation: 'fo-ku-sii-rın', germanSentence: 'Lass uns auf das Wesentliche fokussieren.', turkishWord: 'odaklanmak', turkishSentence: 'Hadi öze (önemli olana) odaklanalım.' },
    { id: 826, category: 'sıfatlar', germanWord: 'episch', pronunciation: 'e-piş', germanSentence: 'Das war ein epischer Kampf!', turkishWord: 'destansı', turkishSentence: 'Bu destansı bir savaştı!' },
    { id: 827, category: 'sıfatlar', germanWord: 'ethisch', pronunciation: 'e-tiş', germanSentence: 'Gibt es dafür ethische Bedenken?', turkishWord: 'etik, ahlaki', turkishSentence: 'Bunun için ahlaki(etik) çekinceler var mı?' },
    { id: 828, category: 'sıfatlar', germanWord: 'exorbitant', pronunciation: 'ek-zor-bi-tant', germanSentence: 'Die Preise sind exorbitant gestiegen.', turkishWord: 'aşırı, fahiş, ölçüsüz', turkishSentence: 'Fiyatlar fahiş(ölçüsüz) bir şekilde yükseldi.' },
    { id: 829, category: 'sıfatlar', germanWord: 'explizit', pronunciation: 'eks-pli-tsiit', germanSentence: 'Ich habe das doch explizit gesagt!', turkishWord: 'açıkça, sarih, belirgin', turkishSentence: 'Bunu açıkça söyledim ya!' },
    { id: 830, category: 'sıfatlar', germanWord: 'exzessiv', pronunciation: 'ek-tse-siif', germanSentence: 'Er treibt exzessiv Sport.', turkishWord: 'aşırı, taşkın, haddinden fazla', turkishSentence: 'O haddinden fazla (aşırı) spor yapıyor.' }
];

export default data17;
