const data13 = [
    // --- İsimler ---
    { id: 501, category: 'isimler', germanWord: 'der Aufschwung', pronunciation: 'der auf-şvunk', germanSentence: 'Die Wirtschaft erlebt einen unerwarteten Aufschwung.', turkishWord: 'kalkınma, canlanma, yükseliş', turkishSentence: 'Ekonomi beklenmedik bir yükseliş/canlanma yaşıyor.' },
    { id: 502, category: 'isimler', germanWord: 'das Bedenken', pronunciation: 'das be-den-kın', germanSentence: 'Alle ethischen Bedenken wurden ignoriert.', turkishWord: 'çekince, endişe', turkishSentence: 'Tüm etik çekinceler göz ardı edildi.' },
    { id: 503, category: 'isimler', germanWord: 'die Branche /-n', pronunciation: 'di bran-şı', germanSentence: 'In dieser Branche ist die Konkurrenz sehr groß.', turkishWord: 'sektör, branş', turkishSentence: 'Bu sektörde rekabet çok büyüktür.' },
    { id: 504, category: 'isimler', germanWord: 'das Dilemma', pronunciation: 'das di-le-ma', germanSentence: 'Wir stecken in einem moralischen Dilemma.', turkishWord: 'ikilem', turkishSentence: 'Ahlaki bir ikilem içindeyiz.' },
    { id: 505, category: 'isimler', germanWord: 'die Ebene /-n', pronunciation: 'di e-be-nı', germanSentence: 'Das muss auf politischer Ebene geklärt werden.', turkishWord: 'seviye, düzey, düzlem', turkishSentence: 'Bu politik düzeyde (seviyede) çözülmelidir.' },
    { id: 506, category: 'isimler', germanWord: 'der Einblick /-e', pronunciation: 'der ayn-blik', germanSentence: 'Der Film bietet einen guten Einblick in sein Leben.', turkishWord: 'içyüzünü kavrama, bakış', turkishSentence: 'Film, onun hayatına dair iyi bir bakış/içyüzü sunuyor.' },
    { id: 507, category: 'isimler', germanWord: 'das Engagement', pronunciation: 'das an-gaa-jı-man', germanSentence: 'Wir danken Ihnen für Ihr soziales Engagement.', turkishWord: 'katılım, üstlenme, çaba', turkishSentence: 'Sosyal katılımınız / çabanız için teşekkür ederiz.' },
    { id: 508, category: 'isimler', germanWord: 'die Entfaltung', pronunciation: 'di ent-fal-tung', germanSentence: 'Es geht um die freie Entfaltung der Persönlichkeit.', turkishWord: 'gelişim, serpilme, açığa çıkma', turkishSentence: 'Söz konusu olan, kişiliğin özgürce gelişimidir.' },
    { id: 509, category: 'isimler', germanWord: 'die Erwartung /-en', pronunciation: 'di er-var-tung', germanSentence: 'Er hat unsere Erwartungen weit übertroffen.', turkishWord: 'beklenti', turkishSentence: 'O bizim beklentilerimizi fazlasıyla aştı.' },
    { id: 510, category: 'isimler', germanWord: 'das Fazit', pronunciation: 'das fa-tsit', germanSentence: 'Das Fazit der Studie ist erschreckend.', turkishWord: 'sonuç, netice, özet', turkishSentence: 'Araştırmanın sonucu (özeti) korkutucudur.' },

    // --- Fiiller ---
    { id: 511, category: 'fiiller', germanWord: 'abzeichnen (sich)', pronunciation: 'ap-tsayh-nın', germanSentence: 'Es zeichnet sich langsam eine Lösung ab.', turkishWord: 'belirmek, şekillenmek', turkishSentence: 'Yavaş yavaş bir çözüm beliriyor.' },
    { id: 512, category: 'fiiller', germanWord: 'ankurbeln', pronunciation: 'an-kur-bıln', germanSentence: 'Die Regierung will die Wirtschaft ankurbeln.', turkishWord: 'canlandırmak, hızlandırmak, harekete geçirmek', turkishSentence: 'Hükümet ekonomiyi canlandırmak istiyor.' },
    { id: 513, category: 'fiiller', germanWord: 'beeinträchtigen', pronunciation: 'be-ayn-treh-ti-gın', germanSentence: 'Der Lärm beeinträchtigt meine Konzentration.', turkishWord: 'zedelemek, zarar vermek, olumsuz etkilemek', turkishSentence: 'Gürültü konsantrasyonumu olumsuz etkiliyor.' },
    { id: 514, category: 'fiiller', germanWord: 'demoralisieren', pronunciation: 'de-mo-ra-li-zii-rın', germanSentence: 'Die ständigen Misserfolge haben ihn demoralisiert.', turkishWord: 'moralini bozmak', turkishSentence: 'Sürekli olan başarısızlıklar onun moralini bozdu.' },
    { id: 515, category: 'fiiller', germanWord: 'entziffern', pronunciation: 'ent-tsi-fırn', germanSentence: 'Dieses alte Dokument ist schwer zu entziffern.', turkishWord: 'okumak, şifresini çözmek', turkishSentence: 'Bu eski belgeyi okumak(sökmek) zordur.' },
    { id: 516, category: 'fiiller', germanWord: 'kalkulieren', pronunciation: 'kal-ku-lii-rın', germanSentence: 'Man hat das Risiko schlecht kalkuliert.', turkishWord: 'hesaplamak', turkishSentence: 'Risk kötü hesaplandı.' },
    { id: 517, category: 'fiiller', germanWord: 'kritisieren', pronunciation: 'kri-ti-zii-rın', germanSentence: 'Das Vorgehen wurde scharf kritisiert.', turkishWord: 'eleştirmek', turkishSentence: 'İzlenen yol (yöntem) sert bir şekilde eleştirildi.' },
    { id: 518, category: 'fiiller', germanWord: 'neutralisieren', pronunciation: 'noy-tra-li-zii-rın', germanSentence: 'Das Gift wurde erfolgreich neutralisiert.', turkishWord: 'etkisiz hale getirmek, nötrleştirmek', turkishSentence: 'Zehir başarıyla etkisiz hale getirildi (nötrleştirildi).' },
    { id: 519, category: 'fiiller', germanWord: 'offenbaren', pronunciation: 'o-fın-baa-rın', germanSentence: 'Er wollte ihr sein dunkles Geheimnis offenbaren.', turkishWord: 'ifşa etmek, ortaya dökmek', turkishSentence: 'Ona karanlık sırrını ifşa etmek (açıklamak) istedi.' },
    { id: 520, category: 'fiiller', germanWord: 'pendeln', pronunciation: 'pen-dıln', germanSentence: 'Jeden Tag muss er zwei Stunden pendeln.', turkishWord: 'mekik dokumak (işle ev arası gidip gelmek)', turkishSentence: 'Her gün iki saat git-gel yapmak (mekik dokumak) zorunda.' },

    // --- Sıfatlar ---
    { id: 521, category: 'sıfatlar', germanWord: 'pauschal', pronunciation: 'pau-şaal', germanSentence: 'Das ist ein sehr pauschales Urteil.', turkishWord: 'genelleştirilmiş, yuvarlak', turkishSentence: 'Bu çok yuvarlak(genelleştirilmiş) bir yargı.' },
    { id: 522, category: 'sıfatlar', germanWord: 'provokant', pronunciation: 'pro-vo-kant', germanSentence: 'Seine Frage war bewusst provokant gestellt.', turkishWord: 'kışkırtıcı, tahrik edici', turkishSentence: 'Sorusu bilinçli olarak kışkırtıcı sorulmuştu.' },
    { id: 523, category: 'sıfatlar', germanWord: 'redundant', pronunciation: 're-dun-dant', germanSentence: 'Viele dieser Daten sind mittlerweile redundant.', turkishWord: 'gereksiz (tekrarlı), fuzuli', turkishSentence: 'Bu verilerin çoğu artık gereksiz (tekrarlanmış/fazla).' },
    { id: 524, category: 'sıfatlar', germanWord: 'souverän', pronunciation: 'zu-ve-reen', germanSentence: 'Er hat die Situation sehr souverän gemeistert.', turkishWord: 'kendinden emin, egemen, hakim', turkishSentence: 'Durumun çok kendinden emin bir şekilde üstesinden geldi.' },
    { id: 525, category: 'sıfatlar', germanWord: 'transparent', pronunciation: 'trans-pa-rent', germanSentence: 'Dieser Prozess muss transparenter werden.', turkishWord: 'şeffaf', turkishSentence: 'Bu süreç daha şeffaf hale gelmelidir.' },
    { id: 526, category: 'sıfatlar', germanWord: 'unabdingbar', pronunciation: 'un-ap-ding-baar', germanSentence: 'Vertrauen ist unabdingbar für eine Beziehung.', turkishWord: 'vazgeçilmez, çok gerekli', turkishSentence: 'Güven bir ilişki için elzemdir (vazgeçilmezdir).' },
    { id: 527, category: 'sıfatlar', germanWord: 'voreilig', pronunciation: 'for-ay-lik', germanSentence: 'Wir sollten keine voreiligen Schlüsse ziehen.', turkishWord: 'aceleci, erken', turkishSentence: 'Aceleci çıkarımlar (sonuçlar) yapmamalıyız.' },
    { id: 528, category: 'sıfatlar', germanWord: 'zart', pronunciation: 'tsaart', germanSentence: 'Ihre Haut ist sehr zart und empfindlich.', turkishWord: 'narin, nazik, yumuşak', turkishSentence: 'Cildi çok narin ve hassastır.' },
    { id: 529, category: 'sıfatlar', germanWord: 'zweiseitig', pronunciation: 'tsvay-zay-tik', germanSentence: 'Das Dokument ist zweiseitig bedruckt.', turkishWord: 'iki taraflı, çift taraflı', turkishSentence: 'Belge çift taraflı basılmış.' },
    { id: 530, category: 'sıfatlar', germanWord: 'zynisch', pronunciation: 'tsüü-niş', germanSentence: 'Dein zynischer Humor verletzt manchmal andere.', turkishWord: 'alaycı, kinik', turkishSentence: 'Alaycı mizahın bazen diğerlerini kırıyor.' },

    // --- Bağlaçlar / Zarflar ---
    { id: 531, category: 'bağlaçlar', germanWord: 'allenfalls', pronunciation: 'a-lın-fals', germanSentence: 'Ich kann dir allenfalls zehn Euro leihen.', turkishWord: 'olsa olsa, en fazla', turkishSentence: 'Sana olsa olsa on Euro borç verebilirim.' },
    { id: 532, category: 'bağlaçlar', germanWord: 'demgemäß', pronunciation: 'dem-ge-mees', germanSentence: 'Der Vertrag wurde demgemäß unterschrieben.', turkishWord: 'buna göre, bu doğrultuda', turkishSentence: 'Sözleşme buna göre(bu doğrultuda) imzalandı.' },
    { id: 533, category: 'bağlaçlar', germanWord: 'ebenso', pronunciation: 'e-bın-zo', germanSentence: 'Sie ist klug und ebenso attraktiv.', turkishWord: 'aynı derecede', turkishSentence: 'O zeki ve aynı derecede çekici.' },
    { id: 534, category: 'bağlaçlar', germanWord: 'folgedessen', pronunciation: 'fol-ge-de-sın', germanSentence: 'Das Projekt scheiterte, folgedessen wurde er entlassen.', turkishWord: 'bunun neticesinde', turkishSentence: 'Proje başarısız oldu, bunun neticesinde o kovuldu.' },
    { id: 535, category: 'bağlaçlar', germanWord: 'jeher', pronunciation: 'yee-her', germanSentence: 'Das war schon von jeher ihr großer Traum.', turkishWord: 'öteden beri, eskiden beri', turkishSentence: 'Bu öteden beri onun en büyük hayaliydi.' },
    { id: 536, category: 'bağlaçlar', germanWord: 'keineswegs', pronunciation: 'kay-nıs-veyks', germanSentence: 'Das ist keineswegs die beste Lösung.', turkishWord: 'hiç de, asla', turkishSentence: 'Bu asla en iyi çözüm değildir.' },
    { id: 537, category: 'bağlaçlar', germanWord: 'mehrheitlich', pronunciation: 'meer-hayt-lih', germanSentence: 'Der Vorschlag wurde mehrheitlich abgelehnt.', turkishWord: 'çoğunlukla', turkishSentence: 'Teklif çoğunlukla reddedildi.' },
    { id: 538, category: 'bağlaçlar', germanWord: 'notgedrungen', pronunciation: 'noot-ge-drun-gın', germanSentence: 'Er musste das Auto notgedrungen verkaufen.', turkishWord: 'zaruri olarak, zorunluluktan', turkishSentence: 'Arabayı zaruri olarak (mecburen) satmak zorunda kaldı.' },
    { id: 539, category: 'bağlaçlar', germanWord: 'ohnehin', pronunciation: 'o-nı-hin', germanSentence: 'Ich hatte ohnehin nicht vor, lange zu bleiben.', turkishWord: 'zaten, her halükarda', turkishSentence: 'Zaten uzun süre kalmayı planlamıyordum.' },
    { id: 540, category: 'bağlaçlar', germanWord: 'womöglich', pronunciation: 'vo-möök-lih', germanSentence: 'Womöglich haben wir uns komplett geirrt.', turkishWord: 'olabilir ki, belki de', turkishSentence: 'Belki de (durum gösteriyor ki) tamamen yanıldık.' },

    // --- İsimler ---
    { id: 541, category: 'isimler', germanWord: 'der Gefährte /-n', pronunciation: 'der ge-feer-tı', germanSentence: 'Sein treuer Gefährte war immer an seiner Seite.', turkishWord: 'yoldaş', turkishSentence: 'Sadık yoldaşı her zaman yanındaydı.' },
    { id: 542, category: 'isimler', germanWord: 'der Haushalt /-e', pronunciation: 'der haus-halt', germanSentence: 'Der Staatshaushalt muss in Ordnung gebracht werden.', turkishWord: 'bütçe, ev idaresi', turkishSentence: 'Devlet bütçesi düzene sokulmalıdır.' },
    { id: 543, category: 'isimler', germanWord: 'die Hierarchie /-n', pronunciation: 'di hi-raar-şii', germanSentence: 'Die flache Hierarchie motiviert die Angestellten.', turkishWord: 'hiyerarşi', turkishSentence: 'Yatay hiyerarşi çalışanları motive ediyor.' },
    { id: 544, category: 'isimler', germanWord: 'die Identität /-en', pronunciation: 'di i-den-ti-teet', germanSentence: 'Sie ist noch auf der Suche nach ihrer Identität.', turkishWord: 'kimlik', turkishSentence: 'O hala kendi kimliğini arıyor.' },
    { id: 545, category: 'isimler', germanWord: 'die Illusion /-en', pronunciation: 'di i-lu-zi-yon', germanSentence: 'Mach dir da bitte keine falschen Illusionen.', turkishWord: 'yanılgı, hayal', turkishSentence: 'Lütfen bu konuda kendine yanlış hayaller/yanılgılar yaratma.' },
    { id: 546, category: 'isimler', germanWord: 'der Instinkt /-e', pronunciation: 'der in-stinkt', germanSentence: 'Sie handelte aus reinem Instinkt.', turkishWord: 'içgüdü', turkishSentence: 'O tamamen içgüdüsel hareket etti.' },
    { id: 547, category: 'isimler', germanWord: 'das Instrument /-e', pronunciation: 'das in-stru-ment', germanSentence: 'Geld ist ein mächtiges Instrument für Veränderungen.', turkishWord: 'enstrüman, araç', turkishSentence: 'Para, değişim için güçlü bir araçtır(enstrümandır).' },
    { id: 548, category: 'isimler', germanWord: 'die Korruption', pronunciation: 'di ko-rup-tsion', germanSentence: 'Korruption schadet der gesamten Gesellschaft.', turkishWord: 'yozlaşma, rüşvet', turkishSentence: 'Yozlaşma (rüşvet) tüm topluma zarar verir.' },
    { id: 549, category: 'isimler', germanWord: 'das Kriterium /-ien', pronunciation: 'das kri-te-rium', germanSentence: 'Dies war das entscheidende Kriterium bei der Wahl.', turkishWord: 'ölçüt', turkishSentence: 'Seçimde belirleyici ölçüt buydu.' },
    { id: 550, category: 'isimler', germanWord: 'die Lobby', pronunciation: 'di lo-bi', germanSentence: 'Die Auto-Lobby hat großen politischen Einfluss.', turkishWord: 'lobi, kulis', turkishSentence: 'Otomobil lobisinin büyük bir politik gücü/etkisi var.' },

    // --- Fiiller ---
    { id: 551, category: 'fiiller', germanWord: 'projizieren', pronunciation: 'pro-yi-tsii-rın', germanSentence: 'Er projiziert seine eigenen Fehler auf andere.', turkishWord: 'yansıtmak, yansıtım yapmak (psikolojik)', turkishSentence: 'O kendi hatalarını başkalarına yansıtıyor.' },
    { id: 552, category: 'fiiller', germanWord: 'prozessieren', pronunciation: 'pro-tse-sii-rın', germanSentence: 'Die Konzerne prozessieren schon seit Jahren.', turkishWord: 'davalaşmak, mahkemelik olmak', turkishSentence: 'Şirketler yıllardır davaşıyor.' },
    { id: 553, category: 'fiiller', germanWord: 'rekonstruieren', pronunciation: 're-kon-stru-ii-rın', germanSentence: 'Die Polizei versucht, den Tathergang zu rekonstruieren.', turkishWord: 'yeniden kurmak, yeniden canlandırmak', turkishSentence: 'Polis olay anını yeniden canlandırmaya çalışıyor.' },
    { id: 554, category: 'fiiller', germanWord: 'respektieren', pronunciation: 'res-pek-tii-rın', germanSentence: 'Du musst ihre Entscheidung respektieren.', turkishWord: 'saygı göstermek', turkishSentence: 'Onun kararına saygı duymalısın.' },
    { id: 555, category: 'fiiller', germanWord: 'rückerstatten', pronunciation: 'rük-er-şta-tın', germanSentence: 'Die Kosten werden vollständig rückerstattet.', turkishWord: 'masrafları iade etmek', turkishSentence: 'Masraflar tamamen iade edilecektir.' },
    { id: 556, category: 'fiiller', germanWord: 'sabotieren', pronunciation: 'za-bo-tii-rın', germanSentence: 'Jemand hat unsere Pläne absichtlich sabotiert.', turkishWord: 'sabote etmek', turkishSentence: 'Biri planlarımızı kasıtlı olarak sabote etti.' },
    { id: 557, category: 'fiiller', germanWord: 'sanieren', pronunciation: 'za-nii-rın', germanSentence: 'Das alte Gebäude muss dringend saniert werden.', turkishWord: 'restore etmek, yenilemek, iyileştirmek', turkishSentence: 'Eski bina acilen restore edilmelidir.' },
    { id: 558, category: 'fiiller', germanWord: 'schwinden', pronunciation: 'şvin-dın', germanSentence: 'Seine Kräfte begannen langsam zu schwinden.', turkishWord: 'azalmak, kaybolmak (güç vb.)', turkishSentence: 'Gücü yavaş yavaş kaybolmaya başladı.' },
    { id: 559, category: 'fiiller', germanWord: 'siegessicher', pronunciation: 'zii-ges-zi-hır', germanSentence: 'Das Team geht siegessicher ins Finale. (adj. used as adv.)', turkishWord: 'zaferden emin', turkishSentence: 'Takım finale zaferinden emin bir şekilde giriyor.' },
    { id: 560, category: 'fiiller', germanWord: 'tasten', pronunciation: 'tas-tın', germanSentence: 'Er tastete im Dunkeln nach seinem Handy.', turkishWord: 'el yordamıyla aramak, yoklamak', turkishSentence: 'O karanlıkta el yordamıyla telefonunu aradı.' },

    // --- Sıfatlar ---
    { id: 561, category: 'sıfatlar', germanWord: 'akkurat', pronunciation: 'a-ku-raat', germanSentence: 'Seine Buchführung ist stets akkurat.', turkishWord: 'titiz, kusursuz, tam', turkishSentence: 'Onun muhasebesi daima kusursuzdur.' },
    { id: 562, category: 'sıfatlar', germanWord: 'akribisch', pronunciation: 'a-krii-biş', germanSentence: 'Die Daten wurden akribisch gesammelt.', turkishWord: 'titizlikle, kılı kırk yararak', turkishSentence: 'Veriler büyük bir titizlikle toplandı.' },
    { id: 563, category: 'sıfatlar', germanWord: 'brisant', pronunciation: 'bri-zant', germanSentence: 'Das Dokument enthält äußerst brisante Informationen.', turkishWord: 'patlamaya hazır, çok tehlikeli, güncel', turkishSentence: 'Belge son derece hassas(tehlikeli/güncel) bilgiler içeriyor.' },
    { id: 564, category: 'sıfatlar', germanWord: 'chronologisch', pronunciation: 'kro-no-loo-giş', germanSentence: 'Bitte ordnen Sie die Ereignisse chronologisch.', turkishWord: 'kronolojik, tarihsel', turkishSentence: 'Lütfen olayları tarihsel/kronolojik sıralayın.' },
    { id: 565, category: 'sıfatlar', germanWord: 'fiktiv', pronunciation: 'fik-tiif', germanSentence: 'Es handelt sich um einen völlig fiktiven Charakter.', turkishWord: 'hayal ürünü, kurgusal', turkishSentence: 'Tamamen kurgusal bir karakter söz konusu.' },
    { id: 566, category: 'sıfatlar', germanWord: 'flexibel', pronunciation: 'flek-sii-bıl', germanSentence: 'Wir suchen Mitarbeiter, die zeitlich flexibel sind.', turkishWord: 'esnek', turkishSentence: 'Zaman açısından esnek olan çalışanlar arıyoruz.' },
    { id: 567, category: 'sıfatlar', germanWord: 'gigantisch', pronunciation: 'gi-gan-tiş', germanSentence: 'Der Schuldenberg ist gigantisch geworden.', turkishWord: 'dev, devasa', turkishSentence: 'Borç dağı devasa boyuta ulaştı.' },
    { id: 568, category: 'sıfatlar', germanWord: 'inhaltsleer', pronunciation: 'in-halts-leer', germanSentence: 'Ihre Rede war schön, aber völlig inhaltsleer.', turkishWord: 'içi boş, anlamsız', turkishSentence: 'Konuşması güzeldi, ama tamamen içi boştu.' },
    { id: 569, category: 'sıfatlar', germanWord: 'innovativ', pronunciation: 'i-no-va-tiif', germanSentence: 'Dieses Startup verfolgt innovative Ansätze.', turkishWord: 'yenilikçi', turkishSentence: 'Bu girişim(startup) yenilikçi yaklaşımlar izliyor.' },
    { id: 570, category: 'sıfatlar', germanWord: 'intakt', pronunciation: 'in-takt', germanSentence: 'Trotz des Alters ist der Motor voll intakt.', turkishWord: 'sağlam, hasarsız, işler durumda', turkishSentence: 'Yaşına rağmen motor tamamen sağladım (işliyor).' }
];

export default data13;
