const data20 = [
    // --- Sürekli İlerleyiş (B2-C1 Kelimeleri) ---
    { id: 951, category: 'sıfatlar', germanWord: 'paranoid', pronunciation: 'pa-ra-no-iit', germanSentence: 'Er leidet unter paranoiden Wahnvorstellungen.', turkishWord: 'paranoyak, kuşkucu', turkishSentence: 'O paranoyak sanrılardan (kuruntulardan) muzdarip.' },
    { id: 952, category: 'sıfatlar', germanWord: 'passioniert', pronunciation: 'pa-siyo-niirt', germanSentence: 'Er ist ein passionierter Musiker.', turkishWord: 'tutkulu', turkishSentence: 'O tutkulu bir müzisyendir.' },
    { id: 953, category: 'sıfatlar', germanWord: 'pathetisch', pronunciation: 'pa-tee-tiş', germanSentence: 'Die Rede klang für viele zu pathetisch.', turkishWord: 'çok duygulu, dokunaklı, abartılı (duygu)', turkishSentence: 'Konuşma birçoklarına fazla dokunaklı(abartılı) geldi.' },
    { id: 954, category: 'sıfatlar', germanWord: 'pingelig', pronunciation: 'pin-ge-lik', germanSentence: 'Er ist sehr pingelig, was Sauberkeit angeht.', turkishWord: 'kılı kırk yaran, titiz, mızmız', turkishSentence: 'O temizlik konusunda oldukça titiz(mızmız)dir.' },
    { id: 955, category: 'sıfatlar', germanWord: 'pragmatisch', pronunciation: 'prag-maa-tiş', germanSentence: 'Wir müssen eine pragmatische Lösung finden.', turkishWord: 'pragmatik, faydacı, pratik', turkishSentence: 'Pratik(faydacı) bir çözüm bulmalıyız.' },
    { id: 956, category: 'sıfatlar', germanWord: 'prätentiös', pronunciation: 'pre-ten-tsi-yöös', germanSentence: 'Ihr Stil ist oft prätentiös und künstlich.', turkishWord: 'gösterişçi, iddialı biçimde taslanmış', turkishSentence: 'Onun tarzı genellikle gösterişçi ve yapaydır.' },
    { id: 957, category: 'sıfatlar', germanWord: 'renitent', pronunciation: 're-ni-tent', germanSentence: 'Die renitenten Schüler wurden bestraft.', turkishWord: 'dikbaşlı, inatçı', turkishSentence: 'Dikbaşlı(asi) öğrenciler cezalandırıldı.' },
    { id: 958, category: 'sıfatlar', germanWord: 'repressiv', pronunciation: 're-pre-siif', germanSentence: 'Das ist ein sehr repressives Regime.', turkishWord: 'baskıcı', turkishSentence: 'Bu oldukça baskıcı bir rejimdir.' },
    { id: 959, category: 'sıfatlar', germanWord: 'resolut', pronunciation: 're-zo-luut', germanSentence: 'Sie trat sehr resolut auf.', turkishWord: 'kararlı, azimli, sert', turkishSentence: 'O oldukça kararlı bir tutum sergiledi.' },
    { id: 960, category: 'sıfatlar', germanWord: 'substanziell', pronunciation: 'zup-s-tan-tsi-yel', germanSentence: 'Wir brauchen substanzielle Veränderungen.', turkishWord: 'önemli, esaslı, maddesel', turkishSentence: 'Esaslı (önemli) değişikliklere ihtiyacımız var.' },

    // --- İsimler ---
    { id: 961, category: 'isimler', germanWord: 'das Spektakel /-', pronunciation: 'şpek-taa-kıl', germanSentence: 'Dieses Lichtfest ist ein riesiges Spektakel.', turkishWord: 'temaşa, görkemli gösteri, patırtı', turkishSentence: 'Bu ışık festivali devasa bir görsel şölendir(temaşadır).' },
    { id: 962, category: 'isimler', germanWord: 'die Stagnation', pronunciation: 'ştag-na-tsiyon', germanSentence: 'Wirtschaftliche Stagnation führt oft zu Arbeitslosigkeit.', turkishWord: 'durgunluk', turkishSentence: 'Ekonomik durgunluk sıklıkla işsizliğe yol açar.' },
    { id: 963, category: 'isimler', germanWord: 'das Tabu /-s', pronunciation: 'ta-buu', germanSentence: 'In dieser Familie ist Geld ein absolutes Tabu.', turkishWord: 'tabu', turkishSentence: 'Bu ailede para kesin bir tabudur.' },
    { id: 964, category: 'isimler', germanWord: 'die Toleranz', pronunciation: 'to-le-rants', germanSentence: 'Toleranz bedeutet, andere Meinungen zu akzeptieren.', turkishWord: 'hoşgörü', turkishSentence: 'Hoşgörü, diğer görüşleri kabul etmek demektir.' },
    { id: 965, category: 'isimler', germanWord: 'der Utopist /-en', pronunciation: 'u-to-pist', germanSentence: 'Man nennt ihn einen hoffnungslosen Utopisten.', turkishWord: 'hayalperest, ütopyacı', turkishSentence: 'Ona umutsuz bir ütopyacı(hayalperest) diyorlar.' },
    { id: 966, category: 'isimler', germanWord: 'das Vakuum', pronunciation: 'va-ku-um', germanSentence: 'Die Machtübergabe hinterließ ein politisches Vakuum.', turkishWord: 'boşluk, vakum', turkishSentence: 'Güç devri siyasi bir boşluk bıraktı.' },
    { id: 967, category: 'isimler', germanWord: 'der Vorwand /"e', pronunciation: 'for-vant', germanSentence: 'Er kam unter einem Vorwand in ihr Haus.', turkishWord: 'bahane', turkishSentence: 'Bir bahane altında onun(kadının) evine geldi.' },
    { id: 968, category: 'isimler', germanWord: 'der Zyklus', pronunciation: 'tsü-klus', germanSentence: 'Die Natur folgt einem ewigen Zyklus.', turkishWord: 'döngü, periyot', turkishSentence: 'Doğa sonsuz bir döngüyü takip eder.' },
    { id: 969, category: 'isimler', germanWord: 'das Paradoxon', pronunciation: 'pa-ra-dok-zon', germanSentence: 'Das Zeitreisen-Paradoxon ist faszinierend.', turkishWord: 'paradoks', turkishSentence: 'Zaman yolculuğu paradoksu büyüleyicidir.' },
    { id: 970, category: 'isimler', germanWord: 'die Resilienz', pronunciation: 're-zi-liyents', germanSentence: 'Psychische Resilienz hilft in schweren Zeiten.', turkishWord: 'dirençlilik, esneklik (psikolojik)', turkishSentence: 'Psikolojik direnç zor zamanlarda yardımcı olur.' },

    // --- Fiiller ---
    { id: 971, category: 'fiiller', germanWord: 'perfektionieren', pronunciation: 'per-fek-tsi-yo-nii-rın', germanSentence: 'Er versuchte, seine Technik zu perfektionieren.', turkishWord: 'mükemmelleştirmek', turkishSentence: 'Tekniğini mükemmelleştirmeye çalıştı.' },
    { id: 972, category: 'fiiller', germanWord: 'plagieren', pronunciation: 'pla-gii-rın', germanSentence: 'Wer in der Doktorarbeit plagiert, wird exmatrikuliert.', turkishWord: 'intihal yapmak', turkishSentence: 'Doktora tezinde intihal yapan okuldan atılır.' },
    { id: 973, category: 'fiiller', germanWord: 'polarisieren', pronunciation: 'po-la-ri-zii-rın', germanSentence: 'Dieser Politiker polarisiert wie kein anderer.', turkishWord: 'kutuplaştırmak, ayırmak', turkishSentence: 'Bu politikacı başka kimsenin yapmadığı kadar kutuplaştırıyor.' },
    { id: 974, category: 'fiiller', germanWord: 'prophylaktisch (adv)', pronunciation: 'pro-fi-lak-tiş', germanSentence: 'Wir geben ihm das Medikament prophylaktisch.', turkishWord: 'önleyici olarak (hastalık vs.)', turkishSentence: 'İlacı ona önleyici olarak (tedbiren) veriyoruz.' },
    { id: 975, category: 'fiiller', germanWord: 'quantifizieren', pronunciation: 'kvan-ti-fi-tsii-rın', germanSentence: 'Den genauen Schaden kann man noch nicht quantifizieren.', turkishWord: 'nicelleştirmek, sayıyla ifade etmek', turkishSentence: 'Kesin hasar henüz ölçülemez(sayısal olarak ifade edilemez).' },
    { id: 976, category: 'fiiller', germanWord: 'revellieren', pronunciation: 're-ve-lii-rın', germanSentence: 'Das Volk begann gegen den König zu rebellieren.', turkishWord: 'isyan etmek, ayaklanmak', turkishSentence: 'Halk krala karşı ayaklanmaya başladı. (Not: Asıl kök rebellieren)' },
    { id: 977, category: 'fiiller', germanWord: 'rehabilitieren', pronunciation: 're-ha-bi-li-tii-rın', germanSentence: 'Er möchte seinen guten Ruf rehabilitieren.', turkishWord: 'itibarını iade etmek, aklamak, rehabilite etmek', turkishSentence: 'İyi ününü (itibarını) geri kazanmak/aklamak istiyor.' },
    { id: 978, category: 'fiiller', germanWord: 'resonieren', pronunciation: 're-zo-nii-rın', germanSentence: 'Diese Idee räsoniert nicht mit meinen Werten.', turkishWord: 'yankı bulmak, uyumlu olmak', turkishSentence: 'Bu fikir benim değerlerimle uyuşmuyor/yankı bulmuyor.' },
    { id: 979, category: 'fiiller', germanWord: 'retuschieren', pronunciation: 're-tu-şii-rın', germanSentence: 'Die Falten auf dem Foto wurden retuschiert.', turkishWord: 'rötuş yapmak, düzeltmek (görsel)', turkishSentence: 'Fotoğraftaki kırışıklıklar rötuşlandı(düzeltildi).' },
    { id: 980, category: 'fiiller', germanWord: 'sublimieren', pronunciation: 'zup-li-mii-rın', germanSentence: 'Triebe können in Kunst sublimiert werden.', turkishWord: 'yüceltmek (psikoloji), süblimleşmek', turkishSentence: 'Dürtüler sanata dönüştürülerek/yüceltilerek dışavurulabilir.' },

    // --- Sıfatlar/Zarflar Son ---
    { id: 981, category: 'sıfatlar', germanWord: 'simultan', pronunciation: 'zi-mul-taan', germanSentence: 'Der Übersetzer arbeitet simultan.', turkishWord: 'eşzamanlı, simültane', turkishSentence: 'Çevirmen eşzamanlı çalışıyor.' },
    { id: 982, category: 'sıfatlar', germanWord: 'souverän', pronunciation: 'zu-ve-reen', germanSentence: 'Sie meisterte die Kritik völlig souverän.', turkishWord: 'hakim, bağımsız, kendinden emin', turkishSentence: 'Eleştirinin üstesinden tamamen kendinden emin bir şekilde geldi.' },
    { id: 983, category: 'sıfatlar', germanWord: 'subjektiv', pronunciation: 'zup-yek-tiif', germanSentence: 'Die Bewertung ist extrem subjektiv.', turkishWord: 'öznel', turkishSentence: 'Değerlendirme son derece öznel.' },
    { id: 984, category: 'sıfatlar', germanWord: 'trivial', pronunciation: 'tri-vi-yaal', germanSentence: 'Dieses Problem ist leider nicht trivial.', turkishWord: 'basit, sıradan, önemsiz', turkishSentence: 'Bu sorun maalesef basit (sıradan) değil.' },
    { id: 985, category: 'sıfatlar', germanWord: 'vakant', pronunciation: 'va-kant', germanSentence: 'Diese Stelle ist seit Monaten vakant.', turkishWord: 'boş, açık (kadro vb.)', turkishSentence: 'Bu kadro/pozisyon aylardır boş.' },
    { id: 986, category: 'sıfatlar', germanWord: 'vital', pronunciation: 'vi-taal', germanSentence: 'Wasser ist von vitaler Bedeutung.', turkishWord: 'hayati, yaşamsal', turkishSentence: 'Su hayati öneme sahiptir.' },
    { id: 987, category: 'sıfatlar', germanWord: 'zeitgemäß', pronunciation: 'tsayt-ge-mees', germanSentence: 'Die Methoden sind nicht mehr zeitgemäß.', turkishWord: 'çağdaş, zamana uygun', turkishSentence: 'Yöntemler artık çağdaş değil.' },
    { id: 988, category: 'bağlaçlar', germanWord: 'demzufolge', pronunciation: 'dem-tsu-fol-gı', germanSentence: 'Es gab einen Streik, demzufolge fielen Züge aus.', turkishWord: 'buna göre, bunun üzerine', turkishSentence: 'Grev vardı, bunun üzerine trenler iptal oldu.' },
    { id: 989, category: 'bağlaçlar', germanWord: 'obschon', pronunciation: 'op-şoon', germanSentence: 'Obschon sie müde war, arbeitete sie weiter.', turkishWord: '-mesine rağmen, gerçi', turkishSentence: 'Yorgun olmasına rağmen çalışmaya devam etti.' },
    { id: 990, category: 'bağlaçlar', germanWord: 'widrigenfalls', pronunciation: 'vid-ri-gın-fals', germanSentence: 'Tun Sie, was verlangt wird, widrigenfalls...', turkishWord: 'aksi taktirde', turkishSentence: 'İsteneni yapın, aksi takdirde...' },

    // --- Ufak Kapanış Eklemeleri (Tam 1000 için) ---
    { id: 991, category: 'isimler', germanWord: 'das Privileg', pronunciation: 'pri-vi-leyg', germanSentence: 'Es ist ein Privileg, hier zu sein.', turkishWord: 'ayrıcalık', turkishSentence: 'Burada olmak bir ayrıcalıktır.' },
    { id: 992, category: 'isimler', germanWord: 'der Protagonist', pronunciation: 'pro-ta-go-nist', germanSentence: 'Der Protagonist des Romans ist ein Detektiv.', turkishWord: 'baş karakter, ana kahraman', turkishSentence: 'Romanın baş karakteri bir detektiftir.' },
    { id: 993, category: 'isimler', germanWord: 'die Sanktion', pronunciation: 'zank-tsion', germanSentence: 'Strenge Sanktionen wurden verhängt.', turkishWord: 'yaptırım', turkishSentence: 'Katı yaptırımlar uygulandı.' },
    { id: 994, category: 'isimler', germanWord: 'die Solidarität', pronunciation: 'zo-li-da-ri-teet', germanSentence: 'Wir zeigen Solidarität mit den Opfern.', turkishWord: 'dayanışma', turkishSentence: 'Kurbanlarla dayanışma gösteriyoruz.' },
    { id: 995, category: 'fiiller', germanWord: 'revidieren', pronunciation: 're-vi-dii-rın', germanSentence: 'Ich muss meine frühere Meinung revidieren.', turkishWord: 'gözden geçirip düzeltmek', turkishSentence: 'Önceki düşüncemi(fikrimi) düzeltmek zorundayım.' },
    { id: 996, category: 'fiiller', germanWord: 'suggerieren', pronunciation: 'zu-ge-rii-rın', germanSentence: 'Was wollen Sie mir damit suggerieren?', turkishWord: 'telkin etmek, ima etmek, etkilemek', turkishSentence: 'Bununla bana ne ima/telkin etmek istiyorsunuz?' },
    { id: 997, category: 'fiiller', germanWord: 'trivilisieren', pronunciation: 'tri-vi-ya-li-zii-rın', germanSentence: 'Versuch nicht, das Problem zu trivialisieren.', turkishWord: 'basitleştirmek, önemsizleştirmek', turkishSentence: 'Sorunu önemsizleştirmeye/basite indirgemeye çalışma.' },
    { id: 998, category: 'sıfatlar', germanWord: 'zynisch', pronunciation: 'tsüü-niş', germanSentence: 'Das war ein sehr zynischer Kommentar.', turkishWord: 'alaycı, kinik, iğneleyici', turkishSentence: 'Bu çok alaycı(kinik) bir yorumdu.' },
    { id: 999, category: 'sıfatlar', germanWord: 'abstrakt', pronunciation: 'ap-strakt', germanSentence: 'Dieses Gemälde ist völlig abstrakt.', turkishWord: 'soyut', turkishSentence: 'Bu tablo tamamen soyuttur.' },
    { id: 1000, category: 'sıfatlar', germanWord: 'ultimativ', pronunciation: 'ul-ti-maa-tif', germanSentence: 'Das ist das ultimative B2-C1 Vokabular.', turkishWord: 'son, nihai, kusursuz', turkishSentence: 'Bu nihai (kusursuz) B2-C1 kelime dağarcığıdır.' }
];

export default data20;
