const data7 = [
    // --- İsimler ---
    { id: 296, category: 'isimler', germanWord: 'der Maßstab /"e', pronunciation: 'der maas-ştaap', germanSentence: 'Wir müssen strengere Maßstäbe anlegen.', turkishWord: 'ölçüt, standart, kıstas', turkishSentence: 'Daha sıkı standartlar(ölçütler) belirlemeliyiz.' },
    { id: 297, category: 'isimler', germanWord: 'der Missbrauch', pronunciation: 'der mis-brauh', germanSentence: 'Der Missbrauch von Medikamenten ist gefährlich.', turkishWord: 'kötüye kullanma, suistimal', turkishSentence: 'İlaçların kötüye kullanımı tehlikelidir.' },
    { id: 298, category: 'isimler', germanWord: 'der Nachfolger /-', pronunciation: 'der nah-fol-gır', germanSentence: 'Wer wird sein offizieller Nachfolger?', turkishWord: 'halef, yerine geçen', turkishSentence: 'Onun resmi halefi(yerine geçen) kim olacak?' },
    { id: 299, category: 'isimler', germanWord: 'die Phase /-n', pronunciation: 'di faa-zı', germanSentence: 'Wir befinden uns in einer kritischen Phase.', turkishWord: 'evre, aşama', turkishSentence: 'Kritik bir evrede (aşamada) bulunuyoruz.' },
    { id: 300, category: 'isimler', germanWord: 'das Privileg /-ien', pronunciation: 'das pri-vi-leyg', germanSentence: 'Es ist ein Privileg, hier arbeiten zu dürfen.', turkishWord: 'ayrıcalık, imtiyaz', turkishSentence: 'Burada çalışma iznine sahip olmak bir ayrıcalıktır.' },
    { id: 301, category: 'isimler', germanWord: 'der Rahmen', pronunciation: 'der raa-mın', germanSentence: 'Das sprengt den finanziellen Rahmen.', turkishWord: 'çerçeve, sınır', turkishSentence: 'Bu, finansal çerçeveyi aşıyor.' },
    { id: 302, category: 'isimler', germanWord: 'das Ressort /-s', pronunciation: 'das re-soor', germanSentence: 'Dieses Thema fällt in mein Ressort.', turkishWord: 'yetki alanı, departman/bakanlık', turkishSentence: 'Bu konu benim yetki alanıma giriyor.' },
    { id: 303, category: 'isimler', germanWord: 'die Routine /-n', pronunciation: 'di ru-tii-nı', germanSentence: 'Der Alltag ist geprägt von viel Routine.', turkishWord: 'rutin, alışkanlık', turkishSentence: 'Günlük yaşam birçok rutinle şekillenmiştir.' },
    { id: 304, category: 'isimler', germanWord: 'der Schwerpunkt /-e', pronunciation: 'der şveer-punkt', germanSentence: 'Der Schwerpunkt der Arbeit liegt auf der IT.', turkishWord: 'ağırlık noktası, odak', turkishSentence: 'Çalışmanın odak noktası IT(bilişim) alanıdır.' },
    { id: 305, category: 'isimler', germanWord: 'das Spektrum /-ren', pronunciation: 'das şpek-t-rum', germanSentence: 'Er bietet ein breites Spektrum an Diensten.', turkishWord: 'yelpaze, çeşitlilik, tayf', turkishSentence: 'O geniş bir hizmet yelpazesi sunuyor.' },

    // --- Fiiller ---
    { id: 306, category: 'fiiller', germanWord: 'kommentieren', pronunciation: 'ko-men-tii-rın', germanSentence: 'Ich möchte dieses Gerücht nicht kommentieren.', turkishWord: 'yorumlamak, yorum yapmak', turkishSentence: 'Bu dedikoduyu yorumlamak istemiyorum.' },
    { id: 307, category: 'fiiller', germanWord: 'kritisieren', pronunciation: 'kri-ti-zii-rın', germanSentence: 'Man sollte nicht immer nur alles kritisieren.', turkishWord: 'eleştirmek', turkishSentence: 'Sürekli her şeyi sadece eleştirmemek gerekir.' },
    { id: 308, category: 'fiiller', germanWord: 'manifestieren (sich)', pronunciation: 'ma-ni-fes-tii-rın', germanSentence: 'Die Krankheit manifestiert sich durch Fieber.', turkishWord: 'ortaya çıkmak, kendini belli etmek', turkishSentence: 'Hastalık kendini ateşle belli ediyor.' },
    { id: 309, category: 'fiiller', germanWord: 'modifizieren', pronunciation: 'mo-di-fi-tsii-rın', germanSentence: 'Wir müssen das Programm leicht modifizieren.', turkishWord: 'değiştirmek, modifiye etmek', turkishSentence: 'Programı hafifçe değiştirmeliyiz.' },
    { id: 310, category: 'fiiller', germanWord: 'nachgeben', pronunciation: 'nah-gey-bın', germanSentence: 'Der Klügere gibt meistens nach.', turkishWord: 'teslim olmak, taviz vermek, boyun eğmek', turkishSentence: 'Akıllı olan genelde taviz verir (pes eder).' },
    { id: 311, category: 'fiiller', germanWord: 'optimieren', pronunciation: 'op-ti-mii-rın', germanSentence: 'Der Workflow wurde vollständig optimiert.', turkishWord: 'en iyi duruma getirmek, optimize etmek', turkishSentence: 'İş akışı tamamen optimize edildi.' },
    { id: 312, category: 'fiiller', germanWord: 'provozieren', pronunciation: 'pro-vo-tsii-rın', germanSentence: 'Lass dich nicht von ihm provozieren.', turkishWord: 'kışkırtmak, tahrik etmek', turkishSentence: 'Onun seni kışkırtmasına izin verme.' },
    { id: 313, category: 'fiiller', germanWord: 'resultieren (aus)', pronunciation: 're-zul-tii-rın', germanSentence: 'Ihre Angst resultiert aus schlechten Erfahrungen.', turkishWord: 'kaynaklanmak, -den ileri gelmek', turkishSentence: 'Onun korkusu kötü tecrübelerden kaynaklanıyor.' },
    { id: 314, category: 'fiiller', germanWord: 'schmälern', pronunciation: 'şmey-lırn', germanSentence: 'Das soll deinen Erfolg keineswegs schmälern.', turkishWord: 'küçültmek, azaltmak (değer/saygınlık)', turkishSentence: 'Bu, başarın değerini asla düşürmemeli(azaltmamalı).' },
    { id: 315, category: 'fiiller', germanWord: 'übermitteln', pronunciation: 'ü-bır-mi-tıln', germanSentence: 'Bitte übermitteln Sie ihm meine besten Wünsche.', turkishWord: 'iletmek, ulaştırmak', turkishSentence: 'Lütfen ona en iyi dileklerimi iletin.' },

    // --- Sıfatlar ---
    { id: 316, category: 'sıfatlar', germanWord: 'obligatorisch', pronunciation: 'ob-li-ga-to-riş', germanSentence: 'Der Besuch dieser Vorlesung ist obligatorisch.', turkishWord: 'zorunlu, mecburi', turkishSentence: 'Bu derse/sempozyuma katılım zorunludur.' },
    { id: 317, category: 'sıfatlar', germanWord: 'partiell', pronunciation: 'par-tsi-yel', germanSentence: 'Eine partielle Sonnenfinsternis war zu sehen.', turkishWord: 'kısmi, bölümsel', turkishSentence: 'Kısmi bir güneş tutulması görülebiliyordu.' },
    { id: 318, category: 'sıfatlar', germanWord: 'prinzipiell', pronunciation: 'prin-tsi-pi-yel', germanSentence: 'Prinzipiell bin ich mit dem Vorschlag einverstanden.', turkishWord: 'prensip olarak, ilkece', turkishSentence: 'Prensip olarak (ilkece) bu teklifi kabul ediyorum.' },
    { id: 319, category: 'sıfatlar', germanWord: 'qualitativ', pronunciation: 'kva-li-ta-tif', germanSentence: 'Das Produkt ist qualitativ sehr hochwertig.', turkishWord: 'niteliksel, kalite bakımından', turkishSentence: 'Bu ürün kalite bakımından çok yüksek (üst düzey).' },
    { id: 320, category: 'sıfatlar', germanWord: 'relevant', pronunciation: 're-le-vant', germanSentence: 'Diese Information ist für uns nicht relevant.', turkishWord: 'önemli, ilgili, ilişkili', turkishSentence: 'Bu bilgi bizim için önemli (ilgili) değil.' },
    { id: 321, category: 'sıfatlar', germanWord: 'subjektiv', pronunciation: 'zup-yek-tiif', germanSentence: 'Schmerz ist immer ein sehr subjektives Gefühl.', turkishWord: 'öznel, subjektif', turkishSentence: 'Acı her zaman oldukça öznel bir histir.' },
    { id: 322, category: 'sıfatlar', germanWord: 'trivial', pronunciation: 'tri-vi-yaal', germanSentence: 'Das Problem ist leider nicht so trivial.', turkishWord: 'basit, sıradan, önemsiz', turkishSentence: 'Sorun maalesef o kadar basit değil.' },
    { id: 323, category: 'sıfatlar', germanWord: 'üppig', pronunciation: 'ü-pik', germanSentence: 'Das Festessen war wirklich sehr üppig.', turkishWord: 'gür, bol, gösterişli', turkishSentence: 'Ziyafet yemeği gerçekten çok bol ve gösterişliydi.' },
    { id: 324, category: 'sıfatlar', germanWord: 'verbindlich', pronunciation: 'fer-bint-lih', germanSentence: 'Die Anmeldung ist verbindlich.', turkishWord: 'bağlayıcı, kesin', turkishSentence: 'Kayıt işlemi bağlayıcıdır (kesindir).' },
    { id: 325, category: 'sıfatlar', germanWord: 'widersprüchlich', pronunciation: 'vi-dır-şpruh-lih', germanSentence: 'Die Zeugenaussagen waren völlig widersprüchlich.', turkishWord: 'çelişkili, tutarsız', turkishSentence: 'Tanık ifadeleri tamamen çelişkiliydi.' },

    // --- Bağlaçlar / Zarflar ---
    { id: 326, category: 'bağlaçlar', germanWord: 'nötigenfalls', pronunciation: 'nö-ti-gın-fals', germanSentence: 'Nötigenfalls rufen wir die Polizei.', turkishWord: 'gerekirse, lüzumu halinde', turkishSentence: 'Gerekirse polisi ararız.' },
    { id: 327, category: 'bağlaçlar', germanWord: 'zumeist', pronunciation: 'tsu-mayst', germanSentence: 'Die Studenten sind zumeist sehr motiviert.', turkishWord: 'çoğunlukla, genellikle', turkishSentence: 'Öğrenciler genellikle çok motive.' },
    { id: 328, category: 'bağlaçlar', germanWord: 'vielerorts', pronunciation: 'fii-lır-orts', germanSentence: 'Vielerorts fehlte es an Trinkwasser.', turkishWord: 'çoğu yerde, birçok yerde', turkishSentence: 'Birçok yerde içme suyu eksikti.' },
    { id: 329, category: 'bağlaçlar', germanWord: 'vollends', pronunciation: 'fo-lents', germanSentence: 'Sie war vollends von ihm überzeugt.', turkishWord: 'tamamen, bütünüyle', turkishSentence: 'Ona tamamen/bütünüyle ikna olmuştu(güveniyordu).' },
    { id: 330, category: 'bağlaçlar', germanWord: 'zunächst', pronunciation: 'tsu-nekst', germanSentence: 'Das sah zunächst wie ein Unfall aus.', turkishWord: 'ilk olarak, başta', turkishSentence: 'Bu başta bir kaza gibi görünüyordu.' }
];

export default data7;
